### ISSUE TITLE
Styling issue on mobile devices

### ISSUE THREAD

**Issue by jacobnbrum** [plaid/link#100]
This issue seems to be similar to issue #38.

Basically I set up plaid link using the simple integration and when I load the page on mobile devices, specifically iPhones (tried on 6, 5) the page loads with very small buttons and text (see attached image).

![image](https://cloud.githubusercontent.com/assets/9966112/17561259/402e4dbe-5ef3-11e6-9529-b8694f13b22f.png)

Is there a setting I need to tweak to fix this? Thanks

**Comment by sinanku** [comment]
<meta name="viewport" content="width=device-width, initial-scale=1">

within in your <head> tag should work :)

<img width="375" alt="screen shot 2016-08-29 at 3 13 23 pm" src="https://cloud.githubusercontent.com/assets/1269987/18063942/2aa80ef0-6dfb-11e6-9dee-043877ca1d26.png">

**Comment by jacobnbrum** [comment]
@sinanku Thanks for the response, but I am still experiencing the same issue where the bank buttons have a weird styling glitch.

![image](https://cloud.githubusercontent.com/assets/9966112/18097745/36825e08-6ead-11e6-8f03-b01b084e9da8.png)

**Comment by sinanku** [comment]
Could you post a code sample?  And are you using WKWebView?

**Comment by michaelckelly** [comment]
@jacobnbrum @sinanku - We've been working to overhaul Plaid Link on mobile devices and would appreciate your feedback on the [Link mobile beta][1].

[1]: https://github.com/plaid/link/blob/master/mobile-beta/README.md

**Comment by sinanku** [comment]
@michaelckelly very nice! The UI looks (and likely feels) more slick 👌  The current dev implementation I have is using the WKWebView & iFrame (so it's time to update).  Congrats to the Plaid team!

**Comment by sinanku** [comment]
`    func userContentController(userContentController: WKUserContentController, didReceiveScriptMessage message: WKScriptMessage) {
        
        // print("Received \(message.body)")
        // convert the json to an nsdict
        
        let _ = String(message.body["access_token"].map({ (unwrap) -> () in
           self.updateUserPlaidToken(unwrap)
        }))
        let _ = String(message.body["stripe_bank_account_token"].map({ (unwrap) -> () in
            self.linkBankToStripe(unwrap)
        }))
        
    }`

This is the current implementation I have using a message handler.  To clarify, instead of messages there are now URL schemes that handle the data passage?

**Comment by michaelckelly** [comment]
@sinanku - Thanks for the kind words and thanks for taking it for a spin.

Although not implemented in Swift (or with a WKWebView), the UIWebView sample code should help clarify the behavior - https://github.com/plaid/link/blob/master/mobile-beta/uiwebview/JavaScript%20WebView/LinkViewController.m#L12-L128

> To clarify, instead of messages there are now URL schemes that handle the data passage?

Correct.

**Comment by pbernasconi** [comment]
@obibring @nickpad – Link mobile has now been released with a completely revamped mobile web experience. We're already starting to see high mobile conversion rates, and will no longer be officially support the older versions of Link. Please checkout our [blog post](https://blog.plaid.com/announcing-a-new-mobile-experience-for-link/) and the [Link docs](https://plaid.com/docs/quickstart/#getting-started) for more information and integrating!
