### ISSUE TITLE
Directly open the Plaid Link without the "open Plaid Link" Button, UIWebView

### ISSUE THREAD

**Issue by taktikal17** [plaid/link#101]
Hi, 

I would like to know if I can open the view "Select your bank" without needing to click on the button "open Plaid Link " with the UIWebView.

Thank you!

**Comment by keakalamudo** [comment]
@taktikal17 Comment out the button code and in the script tag just call sandboxHandler.open()

**Comment by taktikal17** [comment]
Hey @keakalamudo,

Thank you for the answer!
I tried this : 

` <body id="plaidLinkButton" onload="sandboxHandler.open();" >
        
        <script src="https://cdn.plaid.com/link/stable/link-initialize.js"></script>
        <script>
            var appScheme = 'linkApp';
            
            var sandboxHandler = Plaid.create({
                                              env: 'tartan',
                                              clientName: 'Client Name',
                                              key: 'test_key',
                                              product: 'auth',
                                              onSuccess: function(public_token) {
                                              var action = 'handlePublicToken';
                                              var url = appScheme + '://' + action + '#' + public_token;
                                              window.location.href = url; // send public_token back to the ViewController delegate
                                              },
                                              onExit: function() {
                                              var action = 'handleOnExit';
                                              var url = appScheme + '://' + action;
                                              window.location.href = url;
                                              },
                                              onLoad: function() {
                                              var action = 'handleOnLoad';
                                              var url = appScheme + '://' + action;
                                              window.location.href = url;
                                              }
                                              });
                                              
                                              document.getElementById('plaidLinkButton').onclick = function() {
                                                  // Trigger the "Institution Select" view
                                                  sandboxHandler.open();
                                              };
        </script>
</body>`

On xcode, I received this : 2016-08-26 20:11:00.193 uiwebview[78151:11503796] handleOnLoad

But nothing appears on the screen after clicking on the button "open link".

What should I do please?

Thank you!

**Comment by keakalamudo** [comment]
Sure thing. The 'sanboxHandler.open()' will only be triggered when you click the 'plaidLinkButton'. So instead you want to take out from within that function. 

` <script src="https://cdn.plaid.com/link/stable/link-initialize.js"></script>
    <script>
        var appScheme = 'linkApp';

        var sandboxHandler = Plaid.create({
                                          env: 'tartan',
                                          clientName: 'Client Name',
                                          key: 'test_key',
                                          product: 'auth',
                                          onSuccess: function(public_token) {
                                          var action = 'handlePublicToken';
                                          var url = appScheme + '://' + action + '#' + public_token;
                                          window.location.href = url; // send public_token back to the ViewController delegate
                                          },
                                          onExit: function() {
                                          var action = 'handleOnExit';
                                          var url = appScheme + '://' + action;
                                          window.location.href = url;
                                          },
                                          onLoad: function() {
                                          var action = 'handleOnLoad';
                                          var url = appScheme + '://' + action;
                                          window.location.href = url;
                                          }
                                          });

                                          //document.getElementById('plaidLinkButton').onclick = function() {
                                              // Trigger the "Institution Select" view
                                             //};

 sandboxHandler.open();

    </script>`

**Comment by keakalamudo** [comment]
```
 <script src="https://cdn.plaid.com/link/stable/link-initialize.js"></script>
    <script>
        var appScheme = 'linkApp';

        var sandboxHandler = Plaid.create({
                                          env: 'tartan',
                                          clientName: 'Client Name',
                                          key: 'test_key',
                                          product: 'auth',
                                          onSuccess: function(public_token) {
                                          var action = 'handlePublicToken';
                                          var url = appScheme + '://' + action + '#' + public_token;
                                          window.location.href = url; // send public_token back to the ViewController delegate
                                          },
                                          onExit: function() {
                                          var action = 'handleOnExit';
                                          var url = appScheme + '://' + action;
                                          window.location.href = url;
                                          },
                                          onLoad: function() {
                                          var action = 'handleOnLoad';
                                          var url = appScheme + '://' + action;
                                          window.location.href = url;
                                          }
                                          });

                                          //document.getElementById('plaidLinkButton').onclick = function() {
                                              // Trigger the "Institution Select" view
                                             //};

 sandboxHandler.open();

    </script>`
```

**Comment by taktikal17** [comment]
Hey @keakalamudo !
Thank you so much!! It is perfect!!!
