### ISSUE TITLE
account name in onSuccess metadata

### ISSUE THREAD

**Issue by elliotdickison** [plaid/link#102]
Would it be possible to surface account name via the `metadata` parameter that's passed to onSuccess (if `selectAccount` is set to true)? Looking at the responses received during the auth process, I can see that the name and other details such as balance are already returned to the client after a successful authentication. Is there any reason that data is not surfaced via the current API?

**Comment by elliotdickison** [comment]
P.S. Thanks for an awesome service and API!

**Comment by pbernasconi** [comment]
Thanks for raising this idea @elliotdickison – We'll get back to you shortly with a concrete answer, however it sounds like a reasonable and valuable addition to the metadata object!

**Comment by pbernasconi** [comment]
@elliotdickison Thanks for your recommendation - we took it into consideration and implemented it in the latest Link release.

You can [checkout the updated docs `onSuccess` metadata]() docs, or see the code sample below for an example integration:


```js
Plaid.create({
  ...,
  onSuccess: function(public_token, metadata) {
    // save the public_token to exchange it for an access_token
    console.log('public_token: ' + public_token);
    // save the account id and show the account name to the user
    console.log('account id: '   + metadata.account.id);
    console.log('account name: ' + metadata.account.name);
  }
});
```

**Comment by derekantrican** [comment]
@pbernasconi It seems your hyperlink for `onSuccess` metadata docs links back to this issue. Is there documentation for the metadata structure located somewhere?
