### ISSUE TITLE
Paste into password field

### ISSUE THREAD

**Issue by toddgower** [plaid/link#104]
Is there any possibility of allowing paste into the password fields? I understand the reasons for not allowing it, but we have a bunch of users who feel very strongly about using a password manager and pasting their passwords in.

**Comment by pbernasconi** [comment]
Hi @toddgower thanks for raising this issue! Could you give me a bit more context about what browser, device and OS you see this happening? We don't purposefully block copy-pasting on Link, so I'm not sure why this is occurring. I additionally just testing using the 1Password chrome extension and automatic username and password filling seem to be working normally.

**Comment by toddgower** [comment]
Sorry, probably should've provided that info to begin with! I'm using Plaid Link in a UIWebView in an iOS app. It seems to be happening on both iOS 8 and 9.  The gif shows the trouble I'm having. Additionally, once I've done a long press in the password field (which normally brings up the option that allows you to paste), typing becomes disabled in the field.
![plaid_link_paste](https://cloud.githubusercontent.com/assets/11283929/18096079/0a55db30-6ea7-11e6-9ab7-84962a38b7b1.gif)

**Comment by sanity** [comment]
Just want to +1 this, it is also causing problems for our users.

**Comment by pbernasconi** [comment]
@toddgower @sanity – We've been working to overhaul Plaid Link on mobile devices and would appreciate your feedback on the [Link mobile beta][1].

Link no longer opens in an iFrame on mobile, so I believe this issue should be solved with the mobile redesign and refactor! Please let me know if you are still encountering this issue!

[1]: https://github.com/plaid/link/blob/master/mobile-beta/README.md
