### ISSUE TITLE
Is there a way to customize Plaid Link UI?

### ISSUE THREAD

**Issue by igorroyzis** [plaid/link#105]
Is there a way to customize Plaid Link UI?

thanks,
Igor

www.dvdendo.com

**Comment by pbernasconi** [comment]
@igorroyzis – thanks for your interest in customizing Link. We are currently considering various option for customizing certain styles and features of Link, and will be investigating this further in the coming months.

As a start, would you mind providing us with a list of features and styles that you consider important to customize?

**Comment by gentle-noah** [comment]
@pbernasconi - I would love to be able to style the button, the holder for the bank selection, and the border radius of all UI elements involved.

**Comment by bowenisdum** [comment]
It would be nice to define some plaid link view protocols that custom views must adheres to, and when initiating the plaidlinkviewcontroller just pass those views in, and give the users the freedom to do whatever they want with it.

**Comment by margaretlouise** [comment]
We would love the ability to filter different account types - for example, listing only credit cards.

**Comment by feitla** [comment]
We would like to modify the `.Overlay` background-color style that is applied

**Comment by pbernasconi** [comment]
@feitla You can customize the background color of the Overlay in our Dashboard at https://dashboard.plaid.com/link/background-color

**Comment by vsanta** [comment]
Slightly different take on this question: Does Plaid exposes the API so I could get the same value of Plaid Link but have a fully customized UI? In my mind it could be something like a list of institutions, a login, account list and the create item.

**Comment by michaelckelly** [comment]
@vsanta - That's not something that is supported. You'll need to use Link to create Items with Plaid's API.
