### ISSUE TITLE
ENOTFOUND error in plaidClient.exchangeToken

### ISSUE THREAD

**Issue by jingxuanhu** [plaid/link#106]
When I use plaid link, I get an error in plaidClient.exchangeToken method response.

The error message is:
{"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"tartan.plaid.com","host":"tartan.plaid.com","port":443}

Anybody know why I got this error?
Thanks!

**Comment by michaelckelly** [comment]
@jingxuanhu - Are you still experiencing this issue?

**Comment by jingxuanhu** [comment]
Hi Michael,

I am not working on that project for a while. So I am not sure whether the problem has been fixed or not.
Please go on close the issue. If I encounter problems in future I will comment on the issue.

Thanks!
Jingxuan
