### ISSUE TITLE
Addition Limit Exceeded

### ISSUE THREAD

**Issue by ducduong** [plaid/link#110]
![simulator screen shot oct 12 2016 11 38 34 am](https://cloud.githubusercontent.com/assets/13758/19316762/b009a670-9070-11e6-9b1a-0f4687ceac03.png)

I'm integrating Plaid Link to my react native app using WebViewBridge. Whenever I added a new user (real user), I get that message even I don't have any user account.

Does anyone have any suggestion?

**Comment by pbernasconi** [comment]
@ducduong Thanks for raising this issue. Please contact support@plaid.com to upgrade your account and enable you to add real credentials to Plaid.

**Comment by ducduong** [comment]
@pbernasconi thank you. So it's a problem with my account, next technical issue. I was thinking we can add up to a hundred accounts before we switch to a paid plan.
