### ISSUE TITLE
Pop up issues on mobile Safari

### ISSUE THREAD

**Issue by rubendinho** [plaid/link#116]
I am using the newest mobile integration and am having issues with the pop-up not opening on mobile browsers (tested on latest iOS Safari and Firefox on iPhone 6).  There is no feedback either - just nothing happens. When testing on desktop, the new mobile link modal loads fine.  

Has anyone else experienced issues?

**Comment by pbernasconi** [comment]
Thanks for raising this issue @rubendinho. We tested Link on several mobile devices on Safari and Firefox and haven't encountered the issue you've described. Could you please provide us with a bit more context regarding the device, OS version, Browser version, etc. Also some sample code would be very helpful in debugging.

One potential cause of this problem might be the face that you've disabled pop-ups in Safari or Firefox. We'll look into that more in the mean time.

**Comment by rubendinho** [comment]
I am using Safari on an iPhone 6 running iOS 10.1.1.  I am triggering Link using AJAX and my logs don't show any errors, which suggests that the pop-up is being suppressed.  No problems with Firefox and Chrome for iOS.

I did try the Link demo via Safari and did NOT experience any problems, which suggests that my AJAX code may be to blame.

**Comment by rubendinho** [comment]
Moving the plaid custom integration from AJAX into a <script> tag in the body seems to be have fixed this issue for now.

**Comment by bgallz** [comment]
@rubendinho - would you mind sharing what changes specifically you made to fix this? I believe I am having the same problem, but moving the integration from an Ajax request to a <script> tag does not seem to solve this.

I am testing with iOS 10.1.1 on Safari.

Currently:
1. User clicks connect button
2. Ajax request performs "Plaid.create({ ... }).open()"

(This works fine on Safari desktop and Chrome on iOS)

Attempted solution
1. jQuery binds connect button to this Javascript function directly:
`$('.connect-button').click(function(){
    Plaid.create({ ... }).open();
});`

Thanks for any help!

**Comment by pbernasconi** [comment]
@bgallz – opening Link inside of an AJAX request will likely cause the browser to think the request is unsafe, and therefore stop the Link tab from opening. There isn't a good way to avoid this, except by only opening Link using a user click event.

**Comment by btg5679** [comment]
Check your pop-up blocker on Safari.  That was the issue for me.  Turned if off via Settings - Safari and it worked just fine.

**Comment by pbernasconi** [comment]
@btg5679 also checkout this Help Center article for more details: 

https://support.plaid.com/customer/en/portal/articles/2870155-prevent-link-from-being-blocked-on-mobile-browsers
