### ISSUE TITLE
Plaid not working in android 4.0.4 Samsung tab 10.1. app getting freez

### ISSUE THREAD

**Issue by waqasayub** [plaid/link#117]
**Note:** This repository is no longer Plaid's primary support channel for Link.
If your issue is time-sensitive, you can contact our support team at
support@plaid.com.

*Please do not include your API `secret` in any support request.*
![screenshot_2016-12-05-10-23-54](https://cloud.githubusercontent.com/assets/3656235/20874577/266c9cb4-baab-11e6-8df9-ebeea7c933ad.jpg)

**Comment by pbernasconi** [comment]
Thanks for raising this issue @waqasayub  – in order for us to better debug your issue, could you please provide some more information. Mostly we would require some sample code of your integration, as well as the [User Agent string](https://en.wikipedia.org/wiki/User_agent) that you are seeing this bug on.

**Comment by pbernasconi** [comment]
@waqasayub can you also confirm that you're using the latest version of Link (eg: the new Link url: `https://cdn.plaid.com/link/v2/stable/link-initialize.js`) – we've overhauled the entire mobile experience, and fixed most mobile issues in the process.
