### ISSUE TITLE
Autofocus (feature request)

### ISSUE THREAD

**Issue by aesopwolf** [plaid/link#119]
I think it makes sense for the input field "Search for your bank" to have an autofocus attribute. This would reduce a click when users select "View More" on the previous screen.

![image](https://cloud.githubusercontent.com/assets/6847633/21129455/70903b6e-c0b6-11e6-9a9f-2968ab709d70.png)

**Comment by pbernasconi** [comment]
Thanks for raising this issue @aesopwolf. We're in the process of investigating new approaches for searching and selecting institutions in Link, and will keep this thread updated as this changes.
