### ISSUE TITLE
Feature request: filter bank accounts by type

### ISSUE THREAD

**Issue by benissimo** [plaid/link#121]
Stripe only supports ACH payments with checking accounts. The Plaid Link modal lists _all_ of a user's bank accounts, not just checking. But if the user selects a savings account, while we can provision that account with Stripe, when we proceed to make an ACH payment, the payment will fail. Therefore it would be helpful to have a configuration option for Plaid Link, something like "account_type: 'checking'" which, when set, filtered the available bank account to choose from.

Alternately, it would be nice to have the selected bank account's type ("checking", "savings", etc.) as a parameter in the callback that fires when a bank account is selected. This way we could decide on our end how to handle it. (Message the user, store the bank account in our system but set a flag indicating it's not checking (and thus not available for ACH), etc.)

**Comment by michaelckelly** [comment]
@benissimo - Stripe should support ACH payments with Savings accounts too, though there are limitations against withdrawals for savings accounts in the US.

When using Auth, the Select Account view will only display `depository` type accounts. When using any other product, the Select Account view will display all available accounts for the user.

**Comment by benissimo** [comment]
@michaelckelly Stripe does not support ACH payments with Savings accounts. We are using the bank account as the source of funds (so yes, they need to be withdrawn from the bank account, not deposited). Our current workaround is just to display text before/after prompting the user that they should choose a checking account. It would be very helpful to have a way to filter which bank accounts are displayed.

**Comment by mauriciocoder** [comment]
That feature request makes totally sense. It should be a way for customizing the Plaid Link (via dashboard perhaps?) for checking account only.

**Comment by jonnymacs** [comment]
+1 this feature is pretty obvious in my opinion. After talking to our plaid rep I am told it is being discussed, but no timeline. Doesn't seem like a difficult feature to add so hopefully it gets done soon.

**Comment by shawnwall** [comment]
I also am in need of this feature in link

**Comment by dperconti** [comment]
I am in dire need of this feature as well.

**Comment by inoda** [comment]
Same here.
