### ISSUE TITLE
Scaling the mobile page to the device height on ios

### ISSUE THREAD

**Issue by Radzell** [plaid/link#122]
When I use the plaid link example in my application every time I go to add a bank I end up having to scroll to see the continue button. Is there some way making that so I don't have to scroll that view.

**Comment by pbernasconi** [comment]
Thanks for raising this issue @Radzell – Would you mind giving me more information about your mobile device including:
- OS
- Device (and version)
- Browser (and version)

Once we have this information we'll be able to debug your issue.

**Comment by michaelckelly** [comment]
@Radzell - I'm going to go ahead and close this issue. Please re-open if you're still encountering this issue / have any additional information that you can share to help us get it resolved!
