### ISSUE TITLE
Link does not work within Facebook Messenger bot webview on iOS

### ISSUE THREAD

**Issue by amandhesi** [plaid/link#127]
We are facing a critical issue using Plaid Link triggered within a Messenger bot webview which does not allow our users to successfully complete Plaid authentication from within Messenger.

**Approach 1**: When using the javascript version of Plaid Link (both with simple and custom integration), once a user successfully logs into their bank account within the webview, the `onSuccess()` function never gets called (neither do `onExit()` or `onLoad()`). This means we are never able to successfully retrieve the user's `public_token` and pass it to our server.

**Approach 2**: We also tried using the webview integration of Plaid Link. However, since communication between the webview and the app is done via HTTP redirects with scheme `plaidLink://`, and we don't control the Messenger app, we are unable to intercept these redirects. This makes this method useless for services built on any 3rd party apps.

Note that when we tried approach 1 about 2 months ago, it worked flawlessly. It also works flawlessly when we open the same URL from Chrome or Safari outside of Messenger.

For some more context, our `onSuccess()` function attempts to redirect to a url and pass the `public_token` as a GET parameter using `window.location.replace()`.

**Comment by michaelckelly** [comment]
@amandhesi - Can you please go ahead and [open a support ticket][1] for this? That will be the fastest way for our team to help you get to the bottom of this. Including sample integration code would be helpful, too!

[1]: https://dashboard.plaid.com/support/new

**Comment by mdriscoll** [comment]
I ran into this as well. Any update on fixing it?

**Comment by deriyuval** [comment]
A temporary workaround would be to use the v1 script.
"https://cdn.plaid.com/link/v1/stable/link-initialize.js"
It doesn't open another tab on safari so all the callbacks are initiated correctly.

hope they fix this soon

**Comment by gouarv** [comment]
hi,
I want to open FB messenger page in our app web view, but this url is not redriect to proper URL.
Let me know how i open www.messenger.com in our app webview?

**Comment by pbernasconi** [comment]
@gouarv – WebViews are a special case in Link, and therefore require the `forceIframe: true` flag, which will ensure that your Link integration stays within your WebView application. Please let us know if that doesn't work and we'd be happy to look into this further.

**Comment by gouarv** [comment]
Thanks for your revert!
forceIframe: true flag-> iOS/ X code have not any property of forceIframe: true flag. i am load simple URL in webview Check Code if any help
 NSURL *websiteUrl = [NSURL URLWithString:@"http://www.messenger.com"];
    NSURLRequest *urlRequest = [NSURLRequest requestWithURL:websiteUrl];
    [mainWeview loadRequest:urlRequest];

I have attached two screens one is for at browser with URL : http://www.messenger.com
![screen shot 2017-06-21 at 12 47 43 pm](https://user-images.githubusercontent.com/20704074/27371865-126b165c-5680-11e7-99dc-f1d16c76d4f5.png)
![screen shot 2017-06-21 at 12 49 05 pm](https://user-images.githubusercontent.com/20704074/27371866-1272242e-5680-11e7-80f6-15831ae4b760.png)


second is open in iOS device web view with same URL.

**Comment by gouarv** [comment]
One more thing if we create Facebook messenger bot, so its helpfull for us and its open properly in iOS Webview?

**Comment by jdudek** [comment]
Link should work properly in Facebook Messenger app if the `forceIframe: true` flag is passed into `Plaid.create`. There are two distinct cases of running Link in webviews:
1) A webview application (such as one that runs in Messenger) needs to open Link. In this case we recommend the `forceIframe` flag which prevents navigating away from the current page.
2) Link is embedded directly in a native app, utilizing the `isWebview` flag. This will trigger the `plaidLink://` communication method. It will *not* work for Messenger apps nor other apps embedded within webviews.

There have been issues with username/password input in `forceIframe: true` mode, but they should have all been resolved in latest release (2.0.35).
