### ISSUE TITLE
Android lower version not work

### ISSUE THREAD

**Issue by vinay15390** [plaid/link#131]
Hello sir,

I am using API level 19 android device , we are facing some problem where load plaid url link but on click a particular bank then not open and show msg "Enter your credentials ". same demo use in higer level device then no any facing problem. 

So please suggest me for lower version(19, 17 API Level) problem.

**Comment by pbernasconi** [comment]
Thanks for raising this issue @vinay15390 – Just to clarify, are you talking about Android version 1.9. I don't believe that is a valid Android version, but there are however versions:
- Donut (1.6)
- Eclair (2.0)

Are you having issues with those versions and Plaid Link? Also if you could specify the exact device you're testing Link on, it would help greatly in finding a solution to your issue

**Comment by vinay15390** [comment]
i am talking about Android version 17(Jelly been) and 19(Kit kat). so please resolve my problem.

**Comment by michaelckelly** [comment]
@vinay15390 - If you're still experiencing an issue here, please go ahead and re-open. Please ensure you're using the latest available version of Link (see the [docs](https://plaid.com/docs) for more).
