### ISSUE TITLE
Publish the source

### ISSUE THREAD

**Issue by jpokrzyk** [plaid/link#132]
Why don't you guys just publish the source code for this? Just curious. Even if you're just mirroring another repo up here and not accepting any issues/PRs it would still be a great benefit to developers.

I wanted to change a few things to get it working in a react-native webview so I just pulled down the js from the CDN and formatted it and made my changes to the compiled(ish) source. And then put it back on my own CDN.

It's not a huge deal for me to keep doing that with each version. But it would have been so much easier I could have just forked (what looks like) a pretty standard react/webpack app.

**Comment by michaelckelly** [comment]
@jpokrzyk  - Thanks for opening this issue! Right now, Link is only supported when it's hosted by Plaid (as opposed to an external CDN). Thanks for sharing the feedback around self-hosting, though.

We work hard to make Link work well on a wide range of platforms -- if the experience could be better (or more straightforward) with React Native Webviews, please [let us know][1]! We'd love to fix any bugs that might exist and find ways to make the integration easier. If you have some sample code, we'd love to share that for other developers!

[1]: https://dashboard.plaid.com/support/new

**Comment by ericlewis** [comment]
+1 for this on the new Link iOS source, would love to give back.
