### ISSUE TITLE
Update mode for Link iOS

### ISSUE THREAD

**Issue by ericlewis** [plaid/link#137]
Native link looks great, but we don't see a way to use it for update mode or preselected institutions the way the webviews allow. When will this be coming?

**Comment by michaelckelly** [comment]
@ericlewis - Link iOS supports both of those features! It sounds like we need to improve the docs. I'll follow up here with code samples.

**Comment by afh** [comment]
@ericlewis Thanks for bringing this up; as @michaelckelly said both features are already working.

Please find below code examples and while we update the documentation I invite you to also have a look at the LinkKit header documentation regarding [update mode](https://github.com/plaid/link/blob/master/ios/LinkKit.framework/Headers/PLKPlaidLinkViewController.h#L120-L136) and [preselected institutions](https://github.com/plaid/link/blob/master/ios/LinkKit.framework/Headers/PLKPlaidLinkViewController.h#L80-L96) for further details.

## Update Mode

To initiate the update mode instantiate the `PLKPlaidLinkViewController` object using [`initWithPublicToken:delegate:`](https://github.com/plaid/link/blob/master/ios/LinkKit.framework/Headers/PLKPlaidLinkViewController.h#L120-L136) and pass your `public_token` as the first parameter. Then present the `linkViewController` instance as usual.

Objective-C
```objc
PLKPlaidLinkViewController* linkViewController = [[PLKPlaidLinkViewController alloc] initWithPublicToken:@"<#THE_PUBLIC_TOKEN#>" delegate:linkViewDelegate];
```

Swift
```swift
let linkViewController = PLKPlaidLinkViewController(publicToken: "<#THE_PUBLIC_TOKEN#>", delegate:linkViewDelegate)
```

## Preselect Institution

To preselect an institution instantiate the `PLKPlaidLinkViewController` object using [`initWithInstitution:delegate:`](https://github.com/plaid/link/blob/master/ios/LinkKit.framework/Headers/PLKPlaidLinkViewController.h#L80-L96) and pass the `institution_id` (e.g. `ins_109509`) of the institution you would like to use  for as the first parameter. Then present the `linkViewController` instance as usual.

Refer to the [Plaid API documentation](https://plaid.com/docs/api/#institution-search) on how to find out the `institution_id` for an institution.

Objective-C
```objc
PLKPlaidLinkViewController* linkViewController = [[PLKPlaidLinkViewController alloc] initWithInstitution:@"<#THE_INSTITUTION_ID#>" delegate:linkViewDelegate];
```

Swift
```swift
let linkViewController = PLKPlaidLinkViewController(institution: "<#THE_INSTITUTION_ID#>", delegate: delegate:linkViewDelegate)
```

**Comment by michaelckelly** [comment]
@ericlewis - This has been added to the docs, see https://github.com/plaid/link/tree/master/ios#custom-initializers and https://github.com/plaid/link/tree/master/ios#update-mode

Thanks for raising this!
