### ISSUE TITLE
Demo Account New Link SDK!

### ISSUE THREAD

**Issue by intellectivee** [plaid/link#140]
Hello,

What accounts are you guys using with the latest Link SDK (`env: .development`)? 
I am trying both `username: user_good | password: pass_good` and `username: plaid_test | password: plaid_good` but I keep getting `addition limit exceeded for this client_id`. 
Even though when I try with the old method `tartan` it works fine.

Thank You!

**Comment by pbernasconi** [comment]
Hi @intellectivee – `user_good` and `pass_good` are [sandbox credentials](https://plaid.com/docs/api/#sandbox), and therefore only work when `env: 'sandbox'`. To add real bank accounts in `development` and `production` you'll have to [contact Plaid support](https://dashboard.plaid.com/support/new) to get a new allowance of items!

LMK if you encounter any more issues during your integration!

**Comment by intellectivee** [comment]
Hey @pbernasconi, thank you for your answer.
I am on iOS and I am using the Link SDK but it seems the credentials don't work.
I have tried all iOS environments `Development`, `Testing` and `Production` but still same error.
Plaid has already confirmed our account ... the problem might be with the new SDK.

![img_2632](https://cloud.githubusercontent.com/assets/22612827/23862170/a2f45d5e-080c-11e7-92bb-dfc62facbd16.PNG)

**Comment by michaelckelly** [comment]
@intellectivee - Thanks for following up. Things should work just fine with `user_good / pass_good`, the `Testing` API environment (which maps to our Sandbox API env -- we'll fix this in the iOS docs shortly), and the `public_key` from your Dashboard. If they're still not, could you please get in touch with us (you can open a ticket from the Dashboard).

**Comment by intellectivee** [comment]
Hey @michaelckelly, 
Thank you for your support. 
I opened a ticket in my dashboard case `#19638`.

**Comment by intellectivee** [comment]
Hey @michaelckelly ,
Since support will take some weeks to respond can you give me a sample response you get from a successful `auth`. Does the `account_id` come inside `account` or separate?
```
 "status": "",  
 "institution": {
    name = "";
    type = "";
 }, "account": {
   "account_id": ""
 }
```
Thank You!

**Comment by afh** [comment]
Hello @intellectivee,

`account_id` is separate of `account`, yet `account` also contains the account identifier within the `id` field (see below).

The LinkDemo applications log the returned metadata to the console upon a successful flow, so you can try it out for yourself.
Configure LinkKit with `selectAccount` `YES`, go through the Link flow, and when the `UIAlertView` shows a successful result, the console will display something similar to the following:

```
2017-03-16 14:51:35.663 LinkDemo-ObjC[80990:9666893] Successfully linked account!
publicToken: public-sandbox-3a0f043d-4fd6-475c-afb4-d9283f2510ab
metadata: {
    account =     {
        id = 3mQQvRlRXgumaRLPN84Xu8bVMwxvnZUqevGqo;
        name = "Plaid Checking";
    };
    "account_id" = 3mQQvRlRXgumaRLPN84Xu8bVMwxvnZUqevGqo;
    institution =     {
        name = "Wells Fargo";
        type = wells;
    };
    "plaid_api_request_id" = "<null>";
    "request_id" = 4x2Ov;
    status = connected;
}
```

**Comment by intellectivee** [comment]
Hey @afh,
Thank you very much for your answer.
It's strange that I cannot get this working in `Testing` but I hope it works in `Production`.
Anyways thanks again this helps a lot.

**Comment by afh** [comment]
@intellectivee Glad that this helps a lot.

The ["Implement the delegate methods section"](https://github.com/plaid/link/tree/master/ios#implement-the-delegate-methods) contains a table explaining the metadata keys and their potential values, so what exactly should be added to or changed in the documentation from you point of view?
