### ISSUE TITLE
LinkDemo-Swift erroring out of the box

### ISSUE THREAD

**Issue by abi** [plaid/link#143]
All I did was update info.plist to include my API key, set the environment ('Development') and API version. I am getting the following when I try to logging with my Chase credentials:

`Failed to link account due to: addition limit exceeded for this client_id. contact support to increase the limit.
metadata: Optional(["status": requires_credentials, "request_id": deaYf, "institution": {
    name = Chase;
    type = chase;
}, "plaid_api_request_id": <null>])
`

**Comment by michaelckelly** [comment]
@abi - That's an issue with your `public_key` in particular -- you'll want to reach out to our [support team][1] and request that your addition limit be increased.

If you test in our [API sandbox environment][2] you'll be able to test using sandbox credentials (user_good / pass_good) and test any flow you like!

[1]: https://dashboard.plaid.com/support/new
[2]: https://plaid.com/docs/api#sandbox

**Comment by abi** [comment]
Thanks, I just reached out to them! It's weird that my addition limit is already reached cos I just signed up for Plaid.

**Comment by michaelckelly** [comment]
@abi - I'll go ahead and close this, please re-open if you're still having trouble!
