### ISSUE TITLE
ios prepare distribution script minor fix

### ISSUE THREAD

**Issue by bowenisdum** [plaid/link#146]
the documentation here: https://github.com/plaid/link/tree/master/ios#user-content-prepare-distribution-script

if you have a space in your app name, make sure to add quotes around file paths in the script here, else it won't work :)

**Comment by afh** [comment]
@bowenisdum Thank you for bringing this up!
 PR #147 makes the necessary improvements.

**Comment by afh** [comment]
Closing this issue as PR #147 was merged
