### ISSUE TITLE
iOS Plaid Link Update Mode invokes success delegate when closing window

### ISSUE THREAD

**Issue by vafada** [plaid/link#148]
1. Open iOS plaid link in update mode https://github.com/plaid/link/blob/master/ios/LinkDemo-Swift/LinkDemo-Swift/ViewController.swift#L116

2. Click on the `X` button
<img width="389" alt="screen shot 2017-04-06 at 10 14 06 am" src="https://cloud.githubusercontent.com/assets/285941/24758955/daca9db2-1ab1-11e7-8abb-6801360df210.png">

3. The success method in the delegate is called instead of the exit method.

**Comment by afh** [comment]
Thank you for raising this issue @vafada. We already have a solution to the issue pending and it will be available with the next version of LinkKit.

**Comment by vafada** [comment]
hi @afh whats the timeline for this?

**Comment by afh** [comment]
Hello @vafada, an update to LinkKit (1.0.4) addressing this issue was just merged with #156.

**Comment by vafada** [comment]
@afh thanks for the updated Binary. I've tested it and so far so good. closing this issue.

**Comment by afh** [comment]
@vafada Happy to hear that 👍
