### ISSUE TITLE
Invalid env: 'Sandbox'

### ISSUE THREAD

**Issue by bowenisdum** [plaid/link#149]
2017-04-06 14:10:28.481938 fair stage[14344:3851484] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid env: 'Sandbox''

**Comment by afh** [comment]
Hello @bowenisdum, please provide more information and context about the issue you are observing:

* Which version of LinkKit are you using?
* How is LinKit configured, via Info.plist or an instance of `PLKConfiguration`?
* What values are used for the `env` and `apiVersion` configuration options?
* What are the detailed steps to reproduce the issue?

**Comment by bowenisdum** [comment]
@afh fixed after upgrading to latest linkkit, didn't realize there is a new version, if we could have this integration done with a pod that would be awesome, and prevent other people hitting similar things like thanks for the quick response! 👍

**Comment by michaelckelly** [comment]
Glad you got it fixed, @bowenisdum - apologies for the confusion with the versions!

https://github.com/plaid/link/issues/150 is open to add pod support -- thanks for the feedback!
