### ISSUE TITLE
Pod File

### ISSUE THREAD

**Issue by samfu** [plaid/link#150]
Is it possible to have an install via CocoaPods so that we can automatically get updates as part of our development process?

**Comment by afh** [comment]
Thank you @samfu for the suggestion, we'll take it into consideration for upcoming improvements.

**Comment by michaelckelly** [comment]
Thank you for the feedback @samfu - we're working to incorporate this via https://github.com/plaid/link/pull/158.

**Comment by michaelckelly** [comment]
@samfu - This was addressed via #158!
