### ISSUE TITLE
iOS Plaid Link opening with preselected institution is broken

### ISSUE THREAD

**Issue by vafada** [plaid/link#152]
using the Swift example:

```
    @IBAction func didTapButton(_ sender: Any?) {
        presentPlaidLinkWithCustomInitializer()
    }

    // MARK: Start Plaid Link with an institution pre-selected
    func presentPlaidLinkWithCustomInitializer() {
        // <!-- SMARTDOWN_CUSTOM_INITIALIZER -->
        let linkConfiguration = PLKConfiguration(key: "YOUR PUBLIC KEY", env: .sandbox, product: .auth)
        linkConfiguration.clientName = "Link Demo"
        
        let linkViewDelegate = self
        let linkViewController = PLKPlaidLinkViewController(institution: "bofa", configuration: linkConfiguration, delegate: linkViewDelegate)
        if (UI_USER_INTERFACE_IDIOM() == .pad) {
            linkViewController.modalPresentationStyle = .formSheet;
        }
        present(linkViewController, animated: true)
        // <!-- SMARTDOWN_CUSTOM_INITIALIZER -->
    }
```
Make sure to replace `"YOUR PUBLIC KEY"` with a valid key.

I expected it for `Bank of America (bofa)` to be pre-selected.

The UI just shows the blank loading screen with a UI Alert pop immediately even without clicking the close button:

<img width="323" alt="screen shot 2017-04-11 at 11 33 13 am" src="https://cloud.githubusercontent.com/assets/285941/24917421/2429e0c4-1eab-11e7-96e6-4538ec79539e.png">

**Comment by vafada** [comment]
I believe opening Plaid Link iOS in update mode has the same issue:

```
    @IBAction func didTapButton(_ sender: Any?) {
        presentPlaidLinkInUpdateMode()
    }
 
    // MARK: Start Plaid Link in update mode
    func presentPlaidLinkInUpdateMode() {
        // <!-- SMARTDOWN_UPDATE_MODE -->
        let linkConfiguration = PLKConfiguration(key: "YOUR PUBLIC KEY", env: .sandbox, product: .auth)
        linkConfiguration.clientName = "Link Demo"
        
        let linkViewDelegate = self
        let linkViewController = PLKPlaidLinkViewController(
            publicToken: "public-sandbox-318b6630-f93d-4f96-8a57-1bbd9c21aba3",
            configuration: linkConfiguration,
            delegate: linkViewDelegate)
        if (UI_USER_INTERFACE_IDIOM() == .pad) {
            linkViewController.modalPresentationStyle = .formSheet;
        }
        present(linkViewController, animated: true)
        // <!-- SMARTDOWN_UPDATE_MODE -->
    }
```

**Comment by michaelckelly** [comment]
@vafada Thanks for the question -- when using our updated API, only `ins_`-style institution IDs are supported (so `bofa` and `chase` are no longer valid for custom initializers). We're not surfacing the invalid institution ID error properly now, though - that's a bug that we'll fix in a release shortly. To get up-to-date institution IDs, I'd use the [institutions API endpoints][1], but here's a rough map of the primary institution types:

| Current institution ID | Legacy institution type |
|----------------|-------------------------|
| `ins_1`        | bofa                    |
| `ins_2`        | bbt                     |
| `ins_3`        | chase                   |
| `ins_4`        | wells                   |
| `ins_5`        | citi                    |
| `ins_6`        | us                      |
| `ins_7`        | usaa                    |
| `ins_9`        | capone                  |
| `ins_10`       | amex                    |
| `ins_11`       | schwab                  |
| `ins_12`       | fidelity                |
| `ins_13`       | pnc                     |
| `ins_14`       | td                      |
| `ins_15`       | nfcu                    |
| `ins_16`       | suntrust                |
| `ins_19`       | regions                 |
| `ins_20`       | citizens                |
| `ins_21`       | huntington              |

The issue in the second case is that the underlying `public_token` has expired - there may be a bug in which we're not surfacing that error properly, though. In the updated API, `public_token`s are one-time use and expire after 30 minutes (but can be regenerated via the [`POST /item/public_token/create` endpoint][2])

[1]: https://plaid.com/docs/api/#institutions
[2]: https://plaid.com/docs/api/#creating-public-tokens

**Comment by vafada** [comment]
@michaelckelly thanks for the update.

This raises more question with regards to the flow of the application. 

In the institution docs, its says `This data changes frequently, and we recommend that you do not store it on your system`, if we don't store anything, how would we know what institution to show upon load? Doing a search and load an institution doesn't guarantee the correct institution will be displayed. 

And if we store institution of an account (which we do since we need to display the institution logo in our UI thus we need to know what bank the account is tied to) what should we store since data might change on your end?

**Comment by rubendinho** [comment]
Just to add to this - being able to access the logos you guys use via `/institutions` (say to trigger certain banks) would be really nice.

Right now we store the institution IDs, and serve a handful of logos (for the banks we "feature"), mapped to those IDs.

**Comment by vafada** [comment]
closing this as @michaelckelly answer clarified the issue i was getting.

**Comment by AnitaSinghLoved** [comment]
@michaelckelly I am still getting error for update mode in iOS.
I have used access token to get public token when I get login required error:

here is code for present model in iOS:
`- (void)presentPlaidLinkInUpdateMode:(NSString*)publicToken {
  @try {
 // 
      id<PLKPlaidLinkViewDelegate> linkViewDelegate  = self;
      PLKPlaidLinkViewController* linkViewController = [[PLKPlaidLinkViewController alloc] initWithPublicToken:publicToken delegate:linkViewDelegate];

      [self.viewControllerReference presentViewController:linkViewController animated:YES completion:nil];
  } @catch (NSException *exception) {
    NSLog(@"Invalid configuration: %@", exception);
  }
//[self presentViewController:linkViewController animated:YES completion:nil];
  // 

}
`

**Comment by afh** [comment]
Hello @AnitaSinghLoved 

thank you for using Plaid Link for iOS.

To best help you there are some things that would be helpful to know:

* Can you please provide the stacktrace of the crash you are observing.
* Which version of LinkKit are you using?
* Which version of iOS are you running?

**Comment by AnitaSinghLoved** [comment]
Hi Alexis,

Thanks for replay. There was no issue with public_token. I was using the
one I created with access_token. It was my bad. I was using wrong method
for initialise plaidController in update mode. It is resolved now.

Thanks,
Anita Singh

**Comment by afh** [comment]
@AnitaSinghLoved happy to hear that you were able to resolve your issue and thanks for the update.
