### ISSUE TITLE
React Native WebView support

### ISSUE THREAD

**Issue by jpokrzyk** [plaid/link#153]
I'm a couple of weeks into trying to get plaid link working in a React Native webview. Per your response from #132 I opened a support ticket on plaid.com on February 27th. You guys never responded and its still just sitting open. So the purpose of this issue is a little public shaming for making me spend so much time on something that could have taken a few hours :)

Here's a number of options that would be awesome if you guys followed through with or just explained why you wouldn't proceed with them.

1. Just publish all the link source for the various platforms. I would have just grabbed the plaid link js code and written my own RN component based on that. Just put a disclaimer that you're not going to accept PRs and won't support any customizations. I can see all the webpacked code anyways. But it would be a pain to reverse engineer the compiled code instead of just starting from the original JS source.
2. Disable your CORS protection (or at least enable in sandbox so your consistent in your environments). I understand why you wouldn't want to do this. But if CORS was disabled I could just download the webpacked code and modify as needed, use the modified code and I would be done. I did this while I was developing against the sandbox only to realize you have CORS preventing me from using this approach in production.
3. Allow the developer to define which schema to be used. It's a fairly big task for me to extend the RN webviews (on both platforms) to be able to use the `plaidlink` schema. If you just made this a configuration I would configure link to use the standard 'https' schema and I could intercept those calls and I would be done.
4. Plaid could just write a RN plaid link module. 

I know I could just write my own RN module from scratch. Which I did. But it's still going to take me some time to get it on par with the plaid link library. 

I hope you take some of my suggestions from the rant above into consideration. My preference is just that you follow up with suggestion number 1. Thanks.

**Comment by michaelckelly** [comment]
Thanks for taking the time to write up this issue @jpokrzyk. Apologies that we didn't get you an answer sooner via Support. 

We'd love to make it easier to use Link within React Native -- unfortunately, #1 and #2 aren't on our roadmap, primarily for the reasons you highlighted around security and CORS. Would #3 make the integration much simpler for you?

**Comment by jpokrzyk** [comment]
1. K I'm still confused about this one. But I'm sure your security concerns are very strict.
2. I would suggest you at least enforce CORS on the sandbox env then. Unless you guys have it off for a specific reason.
3. Yea definitely. Or else the only other option that I've found is to inject a bunch of javascript and take over the window.postMessage stuff (which is possible, but a little messy).

Thanks for the quick response.

**Comment by idris** [comment]
@jpokrzyk we got the native Link iOS working with a React Native native module.  If you'd like I can share some code to show how we did it.

**Comment by pbernasconi** [comment]
@idris we would also love to see some sample code, which would help us build out our examples section for other developers using React Native!

**Comment by jpokrzyk** [comment]
@idris Sure that would be great. No rush for me though. I wouldn't want to use the iOS libraries until you guys come out with the corresponding android libraries... since we're on both mobile platforms. 

We don't really have any platform specific code without the ability to have similar code for the other platform. Another way of saying that is that it doesn't make sense for us to write any objective C code if we don't also have to ability to write the java code for android.

But I'm definitely happy to hear you're considering RN developers as you're working on these libraries.

**Comment by catalinmiron** [comment]
@idris I'd also like to see your react native implementation. Thanks!

**Comment by williamtran29** [comment]
@idris  Could you share your implementation for React Native? Thanks!

**Comment by catalinmiron** [comment]
Here's an example of usign Plaid Link with React Native.

```js

import React, { Component } from 'react';
import { WebView, Text, View, StyleSheet } from 'react-native';
import { Constants } from 'expo';

const PLAID_API_KEY = 'YOUR_PLAID_API_KEY'
const PLAID_ENV = 'sandbox'
const PLAID_PRODUCT = 'auth,transactions'

export default class App extends Component {
  constructor(props) {
    super(props)
    this.state = {
      authed: false,
      data: {}
    }
  }
  
  render() {
    return (
      this.state.data.action && this.state.data.action.indexOf('::connected') !== -1 ? this.renderDetails() : <WebView source={{uri: `https://cdn.plaid.com/link/v2/stable/link.html?key=${PLAID_API_KEY}&env=${PLAID_ENV}&product=${PLAID_PRODUCT}&clientName=CatalinMiron&isWebView=true&webhook=http://google.com`}} onMessage={(e) => this.onMessage(e)}/>
    );
  }
  renderDetails() {
    return <View style={styles.container}>
      <Text>Institution: {this.state.data.metadata.institution.name}</Text>
      <Text>Institution ID: {this.state.data.metadata.institution.institution_id}</Text>
      <Text>Token: {this.state.data.metadata.public_token}</Text>
    </View>
  }
  
  onMessage(e) {
    /*  
      Response example for success
      
      {
        "action": "plaid_link-undefined::connected",
        "metadata": {
          "account": {
            "id": null,
            "name": null
          },
          "account_id": null,
          "public_token": "public-sandbox-e697e666-9ac2-4538-b152-7e56a4e59365",
          "institution": {
            "name": "Chase",
            "institution_id": "ins_3"
          }
        }
      }
    */

    this.setState({
      data: JSON.parse(e.nativeEvent.data)
    })
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#34495e',
  },
});
```

**Comment by michaelckelly** [comment]
@catalinmiron - thanks for putting this together! We'd love to point more developers towards this example as we have a lot of developers using React Native and Link. Can we check this in to the public Link repository? Happy to give you a shout out in the example file itself or have you submit a PR from it (I may make a few contributions to it too).

**Comment by catalinmiron** [comment]
Hi,
That's for sure, no worries:) I'm really happy that I could help you guys. Keep up the good work!

**Comment by nkarman** [comment]
@catalinmiron Thanks for sharing this implementation! When I implement it, my webview disappears after loading the first plaid view. Has anyone else experienced this issue? Running on iOS, React-Native 0.42.3

I understand there have been issues with webviews nested inside of views, but I am not wrapping ym webview in anything. Thanks in advance for any help from anyone!

**Comment by catalinmiron** [comment]
The problem is the link itself, if you open that link in your browser, you'll have the same behaviour, maybe it's because plaid update their webview url.

**Comment by catalinmiron** [comment]
After some debuggins, it looks like you need to update the url.

```js
import React, { Component } from 'react';
import { WebView, Text, View, StyleSheet } from 'react-native';
import { Constants } from 'expo';

const PLAID_PUBLIC_KEY= 'YOUR_PLAID_PUBLIC_KEY'
const PLAID_ENV = 'sandbox'
const PLAID_PRODUCT = 'auth,transactions'

export default class App extends Component {
  constructor(props) {
    super(props)
    this.state = {
      authed: false,
      data: {}
    }
  }

  render() {
    return (
      this.state.data.action && this.state.data.action.indexOf('::connected') !== -1 ?
        this.renderDetails() : this.renderLogin()
    );
  }
  renderLogin() {
    return <WebView 
      source={{uri: `https://cdn.plaid.com/link/v2/stable/link.html?key=${PLAID_PUBLIC_KEY}&env=${PLAID_ENV}&product=${PLAID_PRODUCT}&clientName=CatalinMiron&isWebView=true&isMobile=true&webhook=http://google.com`}} 
      onMessage={(e) => this.onMessage(e)}
    />
  }

  renderDetails() {
    return <View style={styles.container}>
      <Text>Institution: {this.state.data.metadata.institution.name}</Text>
      <Text>Institution ID: {this.state.data.metadata.institution.institution_id}</Text>
      <Text>Token: {this.state.data.metadata.public_token}</Text>
    </View>
  }

  onMessage(e) {
    /*
      Response example for success

      {
        "action": "plaid_link-undefined::connected",
        "metadata": {
          "account": {
            "id": null,
            "name": null
          },
          "account_id": null,
          "public_token": "public-sandbox-e697e666-9ac2-4538-b152-7e56a4e59365",
          "institution": {
            "name": "Chase",
            "institution_id": "ins_3"
          }
        }
      }
    */

    this.setState({
      data: JSON.parse(e.nativeEvent.data)
    })
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#34495e',
  },
});
```

and so you need to change the key with your **PUBLIC_KEY**. Let me know if this works for you. Good luck!

**Comment by catalinmiron** [comment]
@nkarman have you had the chance to try the above code? Thanks!

**Comment by nkarman** [comment]
@catalinmiron Will try out tonight, thanks so much for your help!

**Comment by nkarman** [comment]
Has anyone noticed any major performance issues while using this implementation? My app starts using extreme CPU resources while running the webview

**Comment by nkarman** [comment]
@catalinmiron 

As soon as I open the WebView, CPU and Memory go absolutely insane. I'm testing on a simulator currently and I understand things are handled differently on the device, but this seems absurd. 


![dime memory leak](https://user-images.githubusercontent.com/21283068/28997184-5d1103e0-79dc-11e7-94aa-8cf6fc7481ca.gif)

**Comment by catalinmiron** [comment]
I've created the lib `react-native-plaid-authenticator` available through npm.

Repo:
https://github.com/catalinmiron/react-native-plaid-authenticator


Thanks!

PS: @nkarman I don't know why there's a memory leak, maybe it's because you're running in `__DEV__: true`.

**Comment by andrewnaeve** [comment]
is there a callback to hook in to if the user hits the X button on the Link page? onMessage isn't giving me anything there.

**Comment by catalinmiron** [comment]
@andrewnaeve after taking a look at the docs it seems that you can catch the `exit` event/action from `onMessage` callback.

```
switch(this.state.data.action) {
  case 'plaid_link-undefined::connected':
    return this.renderDetails()
  case 'plaid_link-undefined::exit':
    return this.renderExit();
  default:
    return this.renderLogin();
}
```

Please let me know if this works. Thanks

**Comment by catalinmiron** [comment]
@andrewnaeve ^
![react_native_plaid_link_login_button](https://user-images.githubusercontent.com/2805320/38192584-d536f58e-366d-11e8-8e04-2b3f19068f42.gif)

You can implement a state machine based on plaid action `CONNECTED` / `EXIT` / `ACKNOWLEDGE` / `EVENT`...

Change you component to 

```javascript
this.state = {
  status: 'LOGIN'
}

// also add status to setState
onMessage = (data) => {
  this.setState({data, status: data.action.substr(data.action.lastIndexOf(':') + 1).toUpperCase()})
}

render() {
  // Possible statuses: CONNECTED | EXIT | ACKNOWLEDGE | EVENT | LOGIN
  switch(this.state.status) {
    case 'CONNECTED':
      return this.renderDetails()
    case 'LOGIN':
    case 'EXIT':
      return this.renderButton();
    default:
      return this.renderPlaidWebview();
  }
}

// The renderButton should always reset the status code
// this.setState({status: ''}) E.g

renderButton = () => {
  return <View style={styles.container}>
    <TouchableOpacity onPress={() => this.setState({status: ''})}>
      <Text style={styles.paragraph}>Login with Plaid</Text>
    </TouchableOpacity>
  </View>
}
```

**Comment by criticerz** [comment]
@catalinmiron First, thank you very much for sharing this. I got it up and running a react native app using Expo.

The issue I'm running into is that as soon as I click on "Login with Plaid" on my phone... the memory starts climbing from ~200mb to >750mb and then the app crashes.

Any ideas on what the issue could be? I can start an issue under your repo if you'd like. Any help is appreciated!

**Comment by catalinmiron** [comment]
I'm not sure if this is related to this library but I have to investigate it in order to have a conclusion. What I know for sure is that you're not the only one complaining about it. Can you please use this library: https://github.com/catalinmiron/react-native-plaid-link and let me know if the memory is still jumping? Thanks!

**Comment by pbernasconi** [comment]
Hey all - We are actively working on a ReactNative example app that we anticipate releasing soon. We plan to add it to this GitHub repo when it's ready and tested, and would love your feedback!

Expect an update soon!

**Comment by pbernasconi** [comment]
Hey all!

We've released our first public example, and recommended implementation of Link + ReactNative in this Link GitHub repo: [github.com/plaid/link/react-native](https://github.com/plaid/link/tree/master/react-native)!

For now, the example is only for iOS, and we're working on the Android Webview implementation in ReactNative in coming weeks.

Please add any feedback or PRs for recommended changes and updates, and thanks for your patience while we worked on this.

**Comment by waheed25** [comment]
I am facing a problem with WebView when I press continue or cross button it didn't call onMessage function, as a result, it didn't set the state of data and when data is not set it didn't call rednderDetails function so in that I am getting the blank screen.Any idea what is going wrong with me.
` import React from 'react';
import { WebView } from 'react-native';

const PLAID_API_KEY = 'my-key'
const PLAID_ENV = 'sandbox'
const PLAID_PRODUCT = 'auth,transactions'
export default class Plaid extends React.Component {
    constructor(props){
        super(props);
        this.state = {
            authed: false,
            data: {}
        }
    }
    onMessage=(e) => {
        debugger;
        this.setState({
            data: JSON.parse(e.nativeEvent.data)
        })
        console.log('data is ::', JSON.parse(e.nativeEvent.data) )
    }
    renderLogin() {
        return <WebView
            source={{uri: `https://cdn.plaid.com/link/v2/stable/link.html?key=${PLAID_API_KEY}&env=${PLAID_ENV}&product=${PLAID_PRODUCT}&clientName=CatalinMiron&isWebview=true&isMobile=true&webhook=http://google.com`}}
            onMessage={(e) => this.onMessage(e)}
        />
    }
    renderDetails() {
        return <View style={styles.container}>
            <Text>Institution: {this.state.data.metadata.institution.name}</Text>
            <Text>Institution ID: {this.state.data.metadata.institution.institution_id}</Text>
            <Text>Token: {this.state.data.metadata.public_token}</Text>
        </View>
    }
    render(){
        console.log('is data changing???:::',this.state.data);
        return(
            this.state.data.action && this.state.data.action.indexOf('::connected') !== -1 ?
                this.renderDetails() : this.renderLogin()
        )
    }
}

`

**Comment by akainth** [comment]
@waheed25 are you able to get thus run?
I am facing same issue from last 1 week and I don't find any solution. Anyone please help me on this. I would really appreciate your help.

Thanks in advance.
