### ISSUE TITLE
iOS institution preselection

### ISSUE THREAD

**Issue by mickeyreiss** [plaid/link#154]
I'd like to be able to handle institution selection in my own UI. 

The doc string for `PLKPlaidLinkViewController.init(institution:, configuration: delegate:)` says, 

> Initializes and returns a newly created Plaid Link view controller in update mode using the given custom configuration.

Is it true that this initializer works _only_ for updating an existing token? It seems to work for linking new accounts in my experimentation.

Thanks!

**Comment by mickeyreiss** [comment]
Relatedly, I am wondering if you'd consider releasing the institutions view controller as an open source component. This would enable us to start with a well-proven implementation and rapidly tailor it to our needs from there.

**Comment by michaelckelly** [comment]
@mickeyreiss - This is likely a typo / something we can clarify in the docs. Link iOS supports custom initializers, which allow you to jump directly to the Login View for a particular institution (specified by its [institution ID][1]). The [iOS docs][2] should provide a good example to go off of too.

[1]: https://plaid.com/docs/api#institutions
[2]: https://github.com/plaid/link/tree/master/ios#user-content-custom-initializer-info

**Comment by afh** [comment]
@mickeyreiss Thanks for bringing this up. It is indeed a typo and will be corrected with the next release of LinkKit.

**Comment by mickeyreiss** [comment]
Thanks. That clarifies things for me.

**Comment by afh** [comment]
@mickeyreiss I invite you to review the header documentation corrections that [LinkKit 1.0.4](https://github.com/plaid/link/commit/8386b6b969db6d69d390d91f17b12d4f917e99c4#diff-59dc682a52288e5169f89e9622c7a75a) brings. Thanks for the feedback!
