### ISSUE TITLE
forceIframe option in Plaid.create()

### ISSUE THREAD

**Issue by prithsharma** [plaid/link#159]
In relation to the comment [here](https://github.com/plaid/link/issues/124#issuecomment-292282000), the `forceIframe` option works well to enable a behavior like Link v1 for mobile clients. But I wasn't able to find any documentation for the `forceIframe` option for `Plaid.create`.
Just wanted to know if this is an undocumented feature that would be supported or it might be removed in future? If it is indeed supported, it might be a good idea to document it.

**Comment by stephenarifin** [comment]
Can we get a comment on this? Is there any drawbacks/bugs that might arise if we use the forceIframe option?

**Comment by cconeill** [comment]
@stephenarifin Plaid does not support that flag and there can be unexpected behavior when using `forceIframe`. You can see some specific examples of bugs in the thread @prithsharma linked [here](https://github.com/plaid/link/issues/124#issuecomment-295542860).

**Comment by pbernasconi** [comment]
@prithsharma @stephenarifin – The Link team has been hard at work to make the mobile experience on mobile as good, if not better, than Desktop, and have pushed an update to Link to **default to the `forceIframe` experience on mobile**.

We've pushed a lot of bug fixed to the forceIframe flag in recent months, and believe it to be a better experience for users and easier to use Link.

Link will now consistently open inside of the same window page, and no longer open into a new browser by default.
