### ISSUE TITLE
is there a way to get the institution logo?

### ISSUE THREAD

**Issue by felipecarreramo** [plaid/link#164]

**Comment by pbernasconi** [comment]
Hi @felipecarreramo - we currently don't offer the ability pull logos from Link, and likely won't in the near future.

With that said, we do recommend using the full Link experience with the Institution Select view. This view will have logos available on both the main and search pages, and will receive continued development in the future.

**Comment by sarink** [comment]
This looks to be available now via the `include_optional_metadata` property when querying institutions plaid.com/docs/#institution-search
