### ISSUE TITLE
Uncaught Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by paradox460** [plaid/link#168]
It appears that in a recent update to Link and the client-side javascript, `babel-polyfill` has been included into the payload. This is conflicting with a copy of `babel-polyfill` our site uses, and breaks several functionalities.

The entire error from the JS console is as follows:

```
ncaught Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (link-initialize.js:1)
    at Object.<anonymous> (link-initialize.js:1)
    at __webpack_require__ (link-initialize.js:1)
    at Object.<anonymous> (link-initialize.js:1)
    at __webpack_require__ (link-initialize.js:1)
    at link-initialize.js:1
    at link-initialize.js:1
(anonymous) @ link-initialize.js:1
(anonymous) @ link-initialize.js:1
__webpack_require__ @ link-initialize.js:1
(anonymous) @ link-initialize.js:1
__webpack_require__ @ link-initialize.js:1
(anonymous) @ link-initialize.js:1
(anonymous) @ link-initialize.js:1
fbevents.js:24 Resource interpreted as Document but transferred with MIME type image/gif: "https://www.facebook.com/tr/".
(anonymous) @ fbevents.js:24
uc @ fbevents.js:24
function.e.___hb.e.___hb @ 0e510e5….js:1
cc @ fbevents.js:24
yb @ fbevents.js:24
kc @ fbevents.js:24
kc @ fbevents.js:24
q @ 549010611968010?v=2.7.10:23
(anonymous) @ 549010611968010?v=2.7.10:23
(anonymous) @ fbevents.js:24
rb.trigger @ fbevents.js:24
bc @ fbevents.js:24
yb @ fbevents.js:24
ab @ fbevents.js:24
wa @ fbevents.js:24
va @ fbevents.js:24
ra @ fbevents.js:24
bb @ fbevents.js:24
(anonymous) @ fbevents.js:24
(anonymous) @ fbevents.js:24
kc @ fbevents.js:24
oc @ fbevents.js:24
sb @ fbevents.js:24
rb.global.releaseConfig @ fbevents.js:24
kc @ fbevents.js:24
plugin @ 549010611968010?v=2.7.10:25
eb @ fbevents.js:24
(anonymous) @ 549010611968010?v=2.7.10:24
```

**Comment by michaelckelly** [comment]
@paradox460 Thanks for flagging - we're investigating this now!

**Comment by mcmar** [comment]
FYI, this is the safe way to use polyfills for libraries
https://babeljs.io/docs/plugins/transform-runtime/
The only caveat is that won't include polyfills for prototype polyfills such as `[1, 2].includes(3)`, but that's a good thing for libraries because you don't want to modify the prototype chain that your host env is using.

**Comment by michaelckelly** [comment]
Thanks @mcmar.

As an update - we are removing `babel-polyfill` as a dependency in the Link initialization script which should resolve this issue. We'll share more details as we have them.

**Comment by michaelckelly** [comment]
@paradox460 @mcmar Please re-open this issue if you are still experiencing this problem!
