### ISSUE TITLE
How to debug LinkKit crashes?

### ISSUE THREAD

**Issue by idris** [plaid/link#169]
When submitting an issue for [**Plaid Link iOS**](https://github.com/plaid/link/tree/master/ios)
please include the following information:

| Name              | Value              |
| ----------------- | ------------------ |
| Link `apiVersion` | v1 |
| Link `env`        | production |
| LinkKit version   | 1.0.4 |
| iOS version       | any |
| iOS device        | any (primarily iPhone) |

### A detailed description of the steps to reproduce the issue
I don't know how to reproduce the error, but I'm seeing a lot of iOS crashes that report `LinkKit` in the backtrace.

Is there a good way to debug these, given that `LinkKit` is not open source?
The backtrace just shows things like: `LinkKit _hidden#1782 + 40` or `LinkKit _hidden#9 + 620`

**Comment by afh** [comment]
@idris Thank you for reaching out.

A good way to debug is to symbolicate the crash reports¹; this should provide helpful information as to what could be the cause of the crashes.

For symbolication a `LinkKit.framework.dSYM` matching the used `LinkKit.framework` file is necessary; to be sure we get you what you need can you please provide the output of the following command, where `LinkKit.framework/LinkKit` is the path to the binary dylib that was used/distributed in the application.

```
dwarfdump --uuid LinkKit.framework/LinkKit 
```

¹ For details on symbolication see [TN2151](https://developer.apple.com/library/content/technotes/tn2151/_index.html) and [Advanced Crash Report Symbolication](https://pspdfkit.com/guides/ios/current/troubleshooting/advanced-symbolication/)

**Comment by idris** [comment]
```
$ dwarfdump --uuid ios/LinkKit.framework/LinkKit
UUID: 50FEDFC5-3588-3E43-A9EF-E3CD337F8F72 (i386) ios/LinkKit.framework/LinkKit
UUID: 64A88921-B482-37CD-9E16-458F8F587B8F (x86_64) ios/LinkKit.framework/LinkKit
UUID: FB1597CC-0A38-3723-8C38-AEDBB977BA73 (armv7) ios/LinkKit.framework/LinkKit
UUID: 465457B2-9794-3E1A-B263-62237EE7E78D (arm64) ios/LinkKit.framework/LinkKit
```

**Comment by afh** [comment]
@idris Thanks for following up.

 [This `dSYM`](https://github.com/plaid/link/files/1026613/LinkKit.framework.dSYM.zip)  was archived with the 1.0.4 release, unfortunately the UUIDs do not match yours. I would appreciate if you would try a symbolication regardless of that.

In case this yields no meaningful results I suggest using [these 1.0.4 release files](https://github.com/plaid/link/releases/download/ios%2F1.0.4/LinkKit.framework.zip), which contain a `LinkKit.framework` with matching `dSYM` and `bcsymbolmap` files.
I'm a afraid this implies building and distributing a new version of your application. Should you also see the crashes with development or beta versions of your application, this might be less of an issue and would be helpful in getting this resolved quickly.

Any other information that you are able to provide and that could be helpful to identify the underlying cause is much appreciated.

**Comment by idris** [comment]
No luck.. I'm going to update using Carthage and try again with the next deploy of our app.

@afh can you confirm that these are the correct UUIDs?
```
$ dwarfdump --uuid LinkKit.framework/LinkKit
UUID: 2B041AA8-D9C3-360D-8BC6-16233EA493D2 (i386) LinkKit.framework/LinkKit
UUID: 490787FC-DA79-30D3-8DCF-C4B290D79557 (x86_64) LinkKit.framework/LinkKit
UUID: B81601CB-356B-310B-B288-EB344257A32F (armv7) LinkKit.framework/LinkKit
UUID: 0F706E50-FCBF-3EA8-8092-FDD7DE8D072F (arm64) LinkKit.framework/LinkKit
```

**Comment by afh** [comment]
@idris Thanks for giving it a try.

Yes, I confirm that those UUIDs are indeed correct; the following command shows that the `dSYM` matches the framework.

```
% dwarfdump --uuid LinkKit.framework/LinkKit LinkKit.framework.dSYM | awk '{print $3,$2,$4}' | sort | column -t
(arm64)   0F706E50-FCBF-3EA8-8092-FDD7DE8D072F  LinkKit.framework.dSYM/Contents/Resources/DWARF/LinkKit
(arm64)   0F706E50-FCBF-3EA8-8092-FDD7DE8D072F  LinkKit.framework/LinkKit
(armv7)   B81601CB-356B-310B-B288-EB344257A32F  LinkKit.framework.dSYM/Contents/Resources/DWARF/LinkKit
(armv7)   B81601CB-356B-310B-B288-EB344257A32F  LinkKit.framework/LinkKit
(i386)    2B041AA8-D9C3-360D-8BC6-16233EA493D2  LinkKit.framework.dSYM/Contents/Resources/DWARF/LinkKit
(i386)    2B041AA8-D9C3-360D-8BC6-16233EA493D2  LinkKit.framework/LinkKit
(x86_64)  490787FC-DA79-30D3-8DCF-C4B290D79557  LinkKit.framework.dSYM/Contents/Resources/DWARF/LinkKit
(x86_64)  490787FC-DA79-30D3-8DCF-C4B290D79557  LinkKit.framework/LinkKit
```

If you'd like verify that you are using the same files please download [LinkKit.framework.sha512.txt](https://github.com/plaid/link/files/1028712/LinkKit.framework.sha512.txt) and run:

```
% shasum -c LinkKit.framework.sha512
LinkKit.framework/LinkKit: OK
LinkKit.framework.dSYM/Contents/Resources/DWARF/LinkKit: OK

% shasum -a 512 LinkKit.framework/LinkKit LinkKit.framework.dSYM/Contents/Resources/DWARF/LinkKit
a55417855ac3c2662a601fd8bd59d23a02f1ac59e4e5d9988eb371788522c7fc663ccc1d195cf46b0639dd29ce2decdb3cb8cb23645887c00de1a233db154ef2  LinkKit.framework/LinkKit
544b367b46475aec975f2de2e037adc185fb7e2cf0aa17056a9af4a43cb454d1946032d7a9917963e4a80631d7fbd8de0ca5561b54e36c11ba5de0ae1b563987  LinkKit.framework.dSYM/Contents/Resources/DWARF/LinkKit
```

**Comment by idris** [comment]
@afh alright, I think I have something useful:
<img width="525" alt="screen shot 2017-05-30 at 3 32 11 pm" src="https://cloud.githubusercontent.com/assets/13989/26601242/2e7be496-454d-11e7-97a3-52aa87123a01.png">

This is especially interesting because it shouldn't even be showing the `PLKSelectAccountViewController`, because I'm just using `connect` to get transactions, which shouldn't prompt for a specific account.

On a related note, I've seen some cases where it _does_ ask for a specific account, for example when updating an item in error state.  I think that's a separate (but related) bug

**Comment by afh** [comment]
Thanks @idris, that is indeed useful.

To gain further insight into the cause of the crash could you please share the actual exception that is being thrown?

I have found where the code path shows the select account flow when it shouldn't and am looking for the exact circumstances that lead to it. Thanks for bringing this to our attention.

**Comment by afh** [comment]
@idris Through further investigation I found the circumstances for the exception.
Fixes for the crash the select account flow only being when ? will be available with next release planned for next week.

**Comment by idris** [comment]
Thanks @afh!  I have another crash stack trace here.  Let me know if you'd like me to create a new issue for it instead.  I don't know how to reproduce any of these (when I link accounts it works fine, but users are seeing crashes.. possibly because of different institutions).

## - [__NSPlaceholderDictionary initWithObjects:forKeys:count:]
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[3]'`
<img width="720" alt="stack trace" src="https://cloud.githubusercontent.com/assets/13989/26684763/04fead96-46b6-11e7-8893-605d837db0c8.png">

**Comment by afh** [comment]
@idris Thank you very much for bringing this to our attention! I'm okay with addressing all issues here.

I have already found the code parts which can be improved and a fix for `NSInvalidArgumentException` will also make it into the next release. Again I'm looking for the exact circumstances that lead to it to ensure the underlying issue is understood and addressed completely.

**Comment by idris** [comment]
@afh another one: (I am just sending these as they appear in my app)

```
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFLocale languageCode]: unrecognized selector sent to instance 0x135d141b0'

Last Exception Backtrace:
0   CoreFoundation                       0x00000001814aedb0 __exceptionPreprocess + 124
1   libobjc.A.dylib                      0x0000000180b13f80 objc_exception_throw + 56
2   CoreFoundation                       0x00000001814b5c4c -[NSObject(NSObject) doesNotRecognizeSelector:] + 212
3   CoreFoundation                       0x00000001814b2bec ___forwarding___ + 872
4   CoreFoundation                       0x00000001813b0c5c _CF_forwarding_prep_0 + 92
5   LinkKit                              0x00000001007e4088 -[PLKAnalytics linkProperties:] (PLKAnalytics.m:138)
6   LinkKit                              0x00000001007e3bc8 -[PLKAnalytics trackProperties:context:] (PLKAnalytics.m:114)
7   LinkKit                              0x00000001007e3a50 -[PLKAnalytics trackEvent:context:] (PLKAnalytics.m:103)
8   LinkKit                              0x00000001007e36bc +[PLKAnalytics trackEvent:context:] (PLKAnalytics.m:67)
9   LinkKit                              0x00000001007bccbc __61-[PLKPlaidLinkViewController initWithConfiguration:delegate:]_block_invoke (PLKPlaidLinkViewController.m:117)
10  libdispatch.dylib                    0x0000000180ef94bc _dispatch_call_block_and_release + 24
11  libdispatch.dylib                    0x0000000180ef947c _dispatch_client_callout + 16
12  libdispatch.dylib                    0x0000000180efeb84 _dispatch_main_queue_callback_4CF + 1844
13  CoreFoundation                       0x0000000181464d50 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
14  CoreFoundation                       0x0000000181462bb8 __CFRunLoopRun + 1628
15  CoreFoundation                       0x000000018138cc50 CFRunLoopRunSpecific + 384
16  GraphicsServices                     0x0000000182c74088 GSEventRunModal + 180
17  UIKit                                0x0000000186676088 UIApplicationMain + 204
18  MyApp                                0x00000001000bb178 main (main.m:16)
19  ???                                  0x0000000180f2a8b8 0x0 + 0
```

**Comment by afh** [comment]
@idris Thank you so much for the valuable feedback! The next version of LinkKit will also address this issue with iOS 9 compatibility related changes.

**Comment by idris** [comment]
@afh any idea when the next version will be released?

**Comment by afh** [comment]
Hello @idris, thank you for your patience.

All of the issues you have reported are fixed, except for the the nil insertion attempt.
These changes turn out to be more elaborate than expected and it will take until the beginning of next week to finalize those.

**Comment by afh** [comment]
Hello @idris 

[LinkKit 1.0.5](https://github.com/plaid/link/releases/tag/ios%2F1.0.5) has been published and all issues you raised within this issue (including the nil insertion attempt) have been addressed.
