### ISSUE TITLE
 Can we get the institution_id in the metadata?

### ISSUE THREAD

**Issue by phaddius** [plaid/link#172]
You are currently returning the institution "name" and "type", but "type" has been deprecated in v2, in favor of institution_id (and your javascript docs say you are returning it in the javascript library). We just need it in the iOS library.

**Comment by afh** [comment]
@phaddius Thank you for reaching out.

This has already been changed and will be available with the next LinkKit release, which is planned for next week.

**Comment by afh** [comment]
Hi @phaddius 

[LinkKit 1.0.5](https://github.com/plaid/link/releases/tag/ios%2F1.0.5) has been published and `institution_id` is now returned in the metadata when using APIv2.
