### ISSUE TITLE
iOS: Banks without a logo don't show bank name on update flow

### ISSUE THREAD

**Issue by idris** [plaid/link#173]
| Name              | Value              |
| ----------------- | ------------------ |
| Link `apiVersion` | v1 |
| Link `env`        | production |
| LinkKit version   | 1.0.4 |
| iOS version       | any |
| iOS device        | iPhone |

### A detailed description of the steps to reproduce the issue

* Link a bank account that does not have a logo (for example, Virgin America Visa)
* On some of the secondary screens, it shows the bank logo but no title (and the titlebar is taken over by something else, like "Enter your credentials", "Loading...", "Success", etc.)

### What you expected to see?
The name of the bank I am trying to update (or the bank I am linking) should appear somewhere on the screen.  This is especially a problem on the "Enter your credentials" screen, because I don't know what I'm entering credentials for!

### What you saw instead?
No bank name, no logo (because this institution doesn't have a logo).

### A screenshot that shows the state of the UI (if applicable)
![img_3328](https://cloud.githubusercontent.com/assets/13989/26696905/5bc2ecf0-46de-11e7-93d8-20d78f8d4d03.PNG)
![img_3326](https://cloud.githubusercontent.com/assets/13989/26696909/5e8af824-46de-11e7-9b9c-c2963dbfb42d.PNG)

**Comment by afh** [comment]
Hello @idris, thank you for reporting. We have encountered and addressed this issue already; a fix where the institution  name  is displayed in the navigation bar title on the `CredentialPane` (where the username and password is entered) will be included with the next LinkKit release. Subsequent panes however will _not_ show the institution name; this may change in a future release to match the web version of Link.
