### ISSUE TITLE
ios: Would be nice to dynamically use sandbox environment when username is "user_good"

### ISSUE THREAD

**Issue by phaddius** [plaid/link#174]
When using our server-side plaid integration (not link), we can detect when username == "user_good" and use the sandbox version of the plaid client, and be able to switch between sandbox and production easily, and since the tokens that come back are labeled with sandbox or production (or development) its easy for the code to know which environment to use when making subsequent requests on those items.  

Can we also do this in the plaid link ios (and webiew) client? It makes it way more convenient for development and testing when we don't need to recompile in order to use test credentials.

**Comment by afh** [comment]
Hello @phaddius,

changing the environment mid-way in the flow is something that I prefer not to support in Plaid Link iOS. What I suggest instead is adding the capability to switch the environment by using [a custom configuration](https://github.com/plaid/link/blob/master/ios/LinkDemo-ObjC/LinkDemo-ObjC/ViewController.m#L114-L134) for each environment you'd like to use and initialize Plaid Link accordingly within your application.

@pbernasconi What are your thoughts for the webview implementations?

**Comment by afh** [comment]
Plaid Link iOS should be initialized and used with the desired environment, if an application would like switch the environment at runtime it should do so by creating multiple instances of `PLKPLaidLinkViewController` initialized different custom configurations.
