### ISSUE TITLE
ios: I still need to pass in custom config to PLKPlaidLinkViewController even after successful setup() with the same config?

### ISSUE THREAD

**Issue by phaddius** [plaid/link#175]
I'm using in-code configuration as opposed to in Info.plist because I want to dynamically switch between environments without needing to recompile.

I've called PLKPlaidLink.setup() with a PLKConfiguration object, and getting the success callback, but when I init a PLKPlaidLinkViewController(), it fails unless I also pass in the same config object.  I'm getting a 'Missing PLKPlaidLinkConfiguration in Info.plist' error if I dont pass the config object in, and it succeeds if I do.

By needing to pass it in, am I incurring the performance penalty of not pre-configuring?

**Comment by afh** [comment]
Hi @phaddius,

thank you for reaching out. To answer your question: **Yes** you need to pass in the custom `PLKConfiguration` instance to `PLKPlaidLinkViewController` after a successful `setup` and **no** you are not incurring the performance penalty by doing so.

The performance penalty only occurs when `setup` is not called or when the configuration between `setup` and the one passed to `PLKPlaidLinkViewController` differs.

If you have any suggestions on how to improve the documentation to make it more understandable, please let us know.
