### ISSUE TITLE
sandbox env breaks what works with tartan

### ISSUE THREAD

**Issue by MaximusMcCann** [plaid/link#177]
*Please do not include your API `secret` or `public_key` in any issue.*
---
When submitting an issue for Link on the web or within a Webview, please include the following information:

|       Name       | Value |
|------------------|-------|
| Link `env`       |    tartan -> sandbox   |
| Browser          |   WebKit     |
| Operating system |  iOS     |

### A detailed description of the steps to reproduce the issue

Just change the `env` query parameter from `tartan` to `sandbox`. 

Webview briefly shows then disappears.  

has a third response: the `actionType` = 'exit' = why is it doing this?

third response: also says the `status` = 'requires_credentials', but the user was never allowed to enter any :/

### What you expected to see?

Not have the webview disappear.

### What you saw instead?

Webview disappears right away w/out allowing the user to do anything. Due to the 'exit' "call"

**Comment by michaelckelly** [comment]
@MaximusMcCann your API keys may be enabled for legacy API access, in which case you'll want to ensure the `apiVersion` flag is set to `v2` when using `env` equal to `sandbox, `development`, or `production`.

**Comment by michaelckelly** [comment]
@MaximusMcCann I'm going to go ahead and close this out but please re-open if you're still experiencing an issue!

**Comment by MaximusMcCann** [comment]
Hi @michaelckelly The web endpoint we hit is; `https://cdn.plaid.com/link/v2/stable/link.html?product=auth&selectAccount=true&webhook=https://requestb.in&isMobile=true&clientName=<NAME>&isWebview=true&key=<KEY>&env=sandbox`

**Comment by michaelckelly** [comment]
@MaximusMcCann - If you signed up for Plaid API keys before March of this year, you're likely enabled for our legacy API. If that's the case, you will need to use the `apiVersion` flag when initializing Link in order to take advantage of the new API. So we suggest using the `apiVersion=v2` flag in your case. Our [API transition guide][1] covers this in greater depth!

[1]: https://plaid.com/docs/link/transition-guide/#client-side-integration

**Comment by MaximusMcCann** [comment]
Apparently you do have to add `apiVersion=v2` to the query parameters.  This is no longer an issue. Cheers
