### ISSUE TITLE
Sandox env/credentials not working

### ISSUE THREAD

**Issue by roktoshl** [plaid/link#179]
|       Name       | Value |
|------------------|-------|
| Link `env`       |    sandbox   |
| Browser          |    webview   |
| Operating system |    Android   |

### A detailed description of the steps to reproduce the issue

* Created a new bank connection using "user_good", "pass_good" for username, password
* Showing processing loader
* Error screen shown at the end
* Some banks immediately return exit action and do not go through evaluation stage at all (#177)

### What you expected to see?

Success screen, which was working before.

### What you saw instead?

Error screen: Failed to create a connection.

### A screenshot that shows the state of the UI (if applicable)

Restart screen for failed connection creation

![plaid_error](https://user-images.githubusercontent.com/25606903/27485554-74d9343c-582d-11e7-949e-2d1acd58f6f3.png)

**Comment by stevejcox** [comment]
Also seeing the same issue.

**Comment by pbernasconi** [comment]
Thank for raising this issue! @roktoshl – we've resolved the issue and you should be able to connect a sandbox item in the Sandbox environment again using `user_good` and `pass_good`!
