### ISSUE TITLE
apiVersion set to v2

### ISSUE THREAD

**Issue by qvivr-jeffrey** [plaid/link#187]
Please update android source code to have apiVersion set to v2. If not when we try the sample code the app would constantly refresh the webview. It is very annoying.

 linkInitializeOptions.put("apiVersion", "v2");

**Comment by pbernasconi** [comment]
Thanks for your feedback @qvivr-jeffrey – https://github.com/plaid/link/pull/188 was just merged which updates the iOS and Android webview examples!
