### ISSUE TITLE
Paypal login not working

### ISSUE THREAD

**Issue by mihahribar** [plaid/link#191]
| Name              | Value              |
| ----------------- | ------------------ |
| Link `apiVersion` |         APIv2           |
| Link `env`        |          Production          |
| LinkKit version   |          1.0.7          |
| iOS version       |         10.3           |
| iOS device        |            Simulator, iPhone7        |

### A detailed description of the steps to reproduce the issue

* Open PayPal directly on login view (institution `ins_22`)
* Enter login credentials
* Solve captcha (I'm not a robot or select squares with X)
* Continue

### What you expected to see?

You successfully linked PayPal.

### What you saw instead?

Endless loading screen. After exiting, since there is nothing else to do, following metadata is returned by Plaid:

```
{
    institution =     {
        "institution_id" = "ins_22";
        name = PayPal;
    };
    "plaid_api_request_id" = "<null>";
    "request_id" = 2vsai;
    status = "requires_recaptcha";
}
```

### A screenshot that shows the state of the UI (if applicable)

![screen shot 2017-08-02 at 18 40 22](https://user-images.githubusercontent.com/148423/28884432-13bec41a-77b2-11e7-8c65-fc9365752d28.png)

**Comment by afh** [comment]
Hi @mihahribar thank you for bringing this to our attention, we are looking into it.

**Comment by afh** [comment]
Hello @mihahribar 

the cause of the issue has been identified and a fix will be available with the next LinkKit release.

**Comment by roktoshl** [comment]
PayPal seems to cause issues on Android also.

Name | Value
-- | --
Link apiVersion | APIv2
Link env | Production
Operating system | Android

### A detailed description of the steps to reproduce the issue

* Open PayPal directly on login view (institution ins_22)
* Enter login credentials
* Solve re-captcha
* Error

### What you expected to see?
Successful login

### What you saw instead?
Error screen

### A screenshot that shows the state of the UI (if applicable)
![android_plaid_paypal_error](https://user-images.githubusercontent.com/25606903/28958292-103ae900-78f6-11e7-81e0-fe4af59239c8.png)

**Comment by pbernasconi** [comment]
Hi @roktoshl – the issue you're seeing doesn't appear to be directly related to Link. I would recommend opening [a new support ticket in the Plaid Dashboard](dashboard.plaid.com/support/new) to enquire more about why your PayPal account isn't working with out API.

It is possible that due to your account being based in EUR currency, that we cannot support it, however you'll find a concrete answer with our support team directly.

**Comment by roktoshl** [comment]
@pbernasconi The link doesn't work, I get a 404.

**Comment by nathankot** [comment]
@roktoshl looks like that link is malformed, please try: https://dashboard.plaid.com/support/new

**Comment by roktoshl** [comment]
@nathankot Thank you.
