### ISSUE TITLE
Account list is shown even with "selectAccount" set to "false"

### ISSUE THREAD

**Issue by superarts** [plaid/link#193]
Hi please forgive me for this noob question: I'm using the latest iOS SDK with the config below. Even with `selectAccount` sets to `false`, after entering username and password for let's say Chase, I'm still seeing 3 accounts under that Chase account. I remember when I was using `.tartan` it was not like this, but can't be sure since the server code was chanced and I can't test `APIv1` anymore. Is there anything I'm doing wrong please?

```
	let linkConfiguration = PLKConfiguration(key: key, env: .sandbox, product: .auth, selectAccount: false, longtailAuth: true, apiVersion: .PLKAPIv2)
```

**Comment by afh** [comment]
Hi @superarts,

thanks for reaching out. Just to verify by "latest iOS SDK" you mean [1.0.7](https://github.com/plaid/link/releases/tag/ios%2F1.0.7)?

In order to better understand what may be happening can you please provide a list of detailed steps how you can reproduce the issue?

**Comment by superarts** [comment]
Thanks! Turned out that there's an error in my code and now it works as expected. Sorry for the false alarm

Orz

**Comment by afh** [comment]
That's good to hear.

In case the documentation or demo projects have been unclear or could be improve in any way, feedback is very welcome.
