### ISSUE TITLE
Plaid mobile web sometimes ends with a blank screen

### ISSUE THREAD

**Issue by stephenarifin** [plaid/link#194]
*Please do not include your API `secret` or `public_key` in any issue.*
---
When submitting an issue for Link on the web or within a Webview, please include the following information:

|       Name       | Value |
|------------------|-------|
| Link `env`       |  development     |
| Browser          |   safari, chrome    |
| Operating system |   ios, android    |

### A detailed description of the steps to reproduce the issue

Sometimes, when a user goes through the link, successfully links a bank account, and hits "continue", the window goes white and the javascript callback onSuccess does not get hit. The tab does not close, and often the user is confused on whether it was not successful or not. I never receive a webhook when this happens as well.

I have not been able to repro this issue but there have been several occasions where some beta testers have reported hitting this issue. One instance was a user running iOS safari, and another was android chrome.

### What you expected to see?

Usually, when the user presses "continue" after a successful link, the new tab on mobile closes and the onSuccess callback is called.

### What you saw instead?

The new tab that plaid opens does not close, and you are left with a white screen.

### A screenshot that shows the state of the UI (if applicable)

I will work hard to get a repro

---

I will work hard to find a repro, but I have not been able to repro on my iPhone 6S running either chrome or safari. Is this a known issue?

**Comment by stephenarifin** [comment]
I managed to repro the issue once. This happens when you try to open the plaid mobile web from a website open by an email client. For example, I click on a link in an email in gmail, and that link opens plaid. Here's a screenshot: http://imgur.com/a/vBsfB

**Comment by nathankot** [comment]
Hey @stephenarifin the mobile implementation of Link uses `window.opener` to communicate with the opener - if Link is opened in Safari from a Webview inside another app then there will be no `window.opener` to communicate back to.

The recommended solution here is to use the (undocumented) `forceIframe: true` option when using Link inside a webview that you have *no control over*. However I'm not entirely sure if this is the scenario you're describing - how are users opening Link from the gmail app?

**Comment by stephenarifin** [comment]
Hey @nathankot, I appreciate the response. The scenario you described is correct: I send an email to a user which leads the user to webpage to open link. Sometimes, the website is opened in the app's webview. I have enabled` forceIframe: true` and it works!

I was wondering why the forceIframe option is undocumented. Is there any drawbacks on using this option? More bugs I should be aware of?
