### ISSUE TITLE
Crash after selecting bank account

### ISSUE THREAD

**Issue by hovmush** [plaid/link#195]
When submitting an issue for [**Plaid Link iOS**](https://github.com/plaid/link/tree/master/ios)
please include the following information:

| Name              | Value              |
| ----------------- | ------------------ |
| Link `apiVersion` |           APIv2           |
| Link `env`             |       Sandbox         |
| LinkKit version      |            1.0.7           |
| iOS version            |          ANY         |
| iOS device             |      ANY      |

### A detailed description of the steps to reproduce the issue

* Install linkkit v1.0.7
* Tap on any bank account
* crash:

![screen shot 2017-08-14 at 6 48 55 pm](https://user-images.githubusercontent.com/18054378/29277106-d03f107c-8121-11e7-8681-477912bf29c2.png)
![screen shot 2017-08-14 at 6 51 59 pm](https://user-images.githubusercontent.com/18054378/29277111-d2b36538-8121-11e7-8db0-b09f41750711.png)

**Comment by afh** [comment]
Hi @hovmush, thank you for reporting this.

Please provide more details how you are configuring LinkKit:
* Are you using a shared configuration from Info.plist or a custom configuration?
* Do you configure `clientName`? If not you might be running into #189

**Comment by hovmush** [comment]
I'm using shared configuration, but i'm also tried with custom and have a same crash. Yeah, i configured clientName.

**Comment by afh** [comment]
Can you provide even more information, e.g.:

* Xcode version you are using
* whether you observe the issue in the iOS Simulator or on actual devices or both
* The configuration you use (please **leave out** your `public_key`!)
* Does the issue only happen only in your project or also in any project in the `LinkDemo.xcworkspace`?

**Comment by hovmush** [comment]
I'm using Xcode Version 8.3.2. It's happening only in my project. In demo app it works correctly. I test it on real device.

**Comment by afh** [comment]
Thanks for the update, @hovmush.

Can you provide a minimal sample project that reliably demonstrates the issue?

**Comment by hovmush** [comment]
[Crash Files ).zip](https://github.com/plaid/link/files/1224456/Crash.Files.zip)
Just add this files into demo app and check.

**Comment by afh** [comment]
Hi @hovmush,

the issue at hand is a [Category Method Name Clash](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/CustomizingExistingClasses/CustomizingExistingClasses.html#//apple_ref/doc/uid/TP40011210-CH6-SW4) since LinkKit also adds a `colorFromString:` method to the `UIColor` class.

The next release of LinkKit will prefix method names on categories of UIKit classes properly, until it is released please use a different name for your category method. Apologies for the inconvenience.

**Comment by afh** [comment]
Hi @hovmush,
once #196 is merged and LinkKit 1.0.8 released the issue you encountered is fixed.
