### ISSUE TITLE
Text is overlaying submit button

### ISSUE THREAD

**Issue by roktoshl** [plaid/link#198]
*Please do not include your API `secret` or `public_key` in any issue.*
---
When submitting an issue for Link on the web or within a Webview, please include the following information:

|       Name       | Value |
|------------------|-------|
| Link `env`       |   production    |
| Browser          |   webview|
| Operating system |    Android     6   |

### A detailed description of the steps to reproduce the issue

* Tried to input login credentials
* Privacy policy overlays submit button on keyboard open

### What you expected to see?

Clearly visible submit button.

### What you saw instead?

Overlayed submit button.

### A screenshot that shows the state of the UI (if applicable)

![29969235-8301b286-8f1f-11e7-9c90-b9d18524e4ad](https://user-images.githubusercontent.com/25606903/29969711-a488d130-8f21-11e7-841d-3c97040ecea0.png)

**Comment by pbernasconi** [comment]
Thanks for flagging this issue @roktoshl – we do perform some validation of viewport height, but it seems our breakpoint is not sufficient for your Android device. This issue has been fixed, so please look out for it in the next release of Link Web!
