### ISSUE TITLE
Failed to verify bitcode in LinkKit.framework/LinkKit    - is bitcode available?

### ISSUE THREAD

**Issue by qvivr-cris** [plaid/link#201]
*Please do not include your API `secret` or `public_key` in any issue.*
---
When submitting an issue for Link on the web or within a Webview, please include the following information:

|       Name       | Value |
|------------------|-------|
| Link `env`       |       |
| Browser          |       |
| Operating system |       |

### A detailed description of the steps to reproduce the issue

Xcode 8.3.1
Project that runs fine on iPhone 6, and Simulator
Xcode Archive a project. 
Once archive complete, go to organizer, and  Export for Ad-Hoc configuration  (with bitcode)

### What you expected to see?

App archive built

### What you saw instead?

2017-09-12 01:05:48 +0000 [MT] Presenting: Error Domain=IDEFoundationErrorDomain Code=1 "Failed to verify bitcode in LinkKit.framework/LinkKit:
error: Cannot extract bundle from /var/folders/mr/q73dzcjd1s90h0k3thzl5tth0000gn/T/XcodeDistPipeline.xbe/Root/Payload/cash.app/Frameworks/LinkKit…" UserInfo={NSLocalizedDescription=Failed to verify bitcode in LinkKit.framework/LinkKit:
error: Cannot extract bundle from /var/folders/mr/q73dzcjd1s90h0k3thzl5tth0000gn/T/XcodeDistPipeline.xbe/Root/Payload/cash.app/Frameworks/LinkKit…}

### A screenshot that shows the state of the UI (if applicable)

see above error

-

**Comment by afh** [comment]
@qvivr-cris Thank you for reaching out. Saving an archive for Ad-Hoc Deployment works well from the LinkDemo project. What are the differences to your project that might be the cause?

In order to gain more insight about what the issue might be please:

* provide a sample project demonstrating the issue you observe
* provide the version of LinkKit you are using
* answer how you are integrating LinkKit in your application: using Cocoapods, Carthage, or manually?
* and whether you enable `Rebuild from bitcode` during export

**Comment by qvivr-cris** [comment]
For some reason, the LinkKit Framework was included twice in the project settings, which appears to have been the cause of this problem.

**Comment by afh** [comment]
Happy to hear you were able to resolve the issue.

**Comment by qvivr-cris** [comment]
Its back.  Its when exporting ad-hoc.  
LinkKit 1.0.10+337
We are using LinkKit Manually.   We would prefer a cocoapod.  It was not clear that a cocoapodwas available.  
We use "Rebuild from bitcode",  unclicking that allows us to do the export.

**Comment by qvivr-cris** [comment]
Using the cocoapod seems to address the issue.   Thanks!

**Comment by afh** [comment]
@qvivr-cris Thanks for following up and providing the additional details. What would have made it more clear that LinkKit can be integrated using Cocoapods?

**Comment by qvivr-cris** [comment]
yes, LinkKit via    pod 'Plaid', '~> 1.0'    Cocoapod seems to work just fine, thank you.
