### ISSUE TITLE
When searching for institutions for link in development mode, search is returning 403 forbidden

### ISSUE THREAD

**Issue by johnwang21** [plaid/link#202]
|       Name       | Value |
|------------------|-------|
| Link `env`       |   development    |
| Browser          |   firefox    |
| Operating system |   windows    |

### A detailed description of the steps to reproduce the issue
1. open up plain link window and search for institutions as seen in image: [https://imgur.com/a/tlIfd]
Instead of click on a particular institution (which works), use the search bar.
sample js:
    javascript:
```
        jQuery(function() {
            var environ = "#{env}";

            var plaid_options = {
                    selectAccount: true,
                    env: ((environ == 'production') ? 'production' : 'development'),
                    clientName: '#{current_user.id}',
                    key: '#{plaid.public_key}',
                    product: 'auth',
                    onLoad: function() { },
                    onSuccess: function(public_token, metadata) {

                        var $form = jQuery('#payment-form');
                        $form.append(jQuery('<input type= "hidden" name= "public_token" />').val(public_token)); 
                        $form.append(jQuery('<input type= "hidden" name= "account_id" />').val(metadata.account_id)); 
                        $form.attr("action", "/stripe/seller/community_fee/bank_account");
                        // and re-submit
                        $form.get(0).submit();
                    },
                    onExit: function() { },
            };

            var linkHandler = Plaid.create(plaid_options);
        });
```
### What you expected to see?
The search functionality to work and allow me to select an institution

### What you saw instead?
api call: https://cdn.plaid.com/institutions/all/search?q=g
error:
403 Forbidden
```
<?xml version=“1.0″ encoding=”UTF-8″?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>9969BEA5AFD76BE0</RequestId
><HostId>nJ/K/cEx9f+uryLY4p6K6Bozz1G5Z0TiRYCWzNBUg7AOhqMXgoL8mPBDPF25jMq2yz3jvscIBdU=</HostId></Error
>
```
### Additional notes
Selecting an institution normally DOES, but the search is broken for development. Is this expected behavior? Or am I implementing this incorrectly on development?

**Comment by michaelckelly** [comment]
@johnwang21 - Can you check the console and see if there are any logged error messages? Sometimes, when Link is configured incorrectly or fails to initialize properly, it may still open while also logging an error to the console. 

We are working to change this behavior so that a misconfiguration is more evident.

**Comment by johnwang21** [comment]
![image](https://user-images.githubusercontent.com/6091011/30758082-d62f825a-9f85-11e7-8523-e1684816503b.png)

**Comment by johnwang21** [comment]
in case you want the text 
'''
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>5D2A5E51937C73E0</RequestId
><HostId>SiWHfq/AvSLdr3B7qfh0GK+iBbwoM2wVVu2v6/DujPHV6C9K9UT7lurSv5Gz9zILDasOOlZPjZY=</HostId></Error
>
'''

**Comment by johnwang21** [comment]
I can also zoom or text conference if needed

**Comment by michaelckelly** [comment]
Hi @johnwang21 - are there are any other errors present in the console prior to the 403s you're seeing?

**Comment by johnwang21** [comment]
@michaelckelly  none, in the console. i'll send a screenshot of the entirety

**Comment by johnwang21** [comment]
![image](https://user-images.githubusercontent.com/6091011/30758211-425c0eee-9f86-11e7-8713-6ccf10c703b7.png)

**Comment by pbernasconi** [comment]
@johnwang21 – could you please send an email to paolo@plaid.com with either your public_key or the link_session_id (returned in the `onExit` metadata) callback.

I believe your configuration in Link is not correct, however we can definitely improve the error response in Link when this occurs, and providing information specific to your integration will help us debug in our logs!

**Comment by johnwang21** [comment]
@pbernasconi email sent

**Comment by pbernasconi** [comment]
Thanks @johnwang21 – this issue has been resolved, and we will address better error messaging during Link development. The root issue was that your public_key is by default enabled for the legacy Plaid API however your Link configuration was using the new "development" environment.

To fix this, the `apiVersion: "v2"` flag in the Link config is required, in addition to changing the `product` key to an array.
