### ISSUE TITLE
Link iOS returns API v1 error codes from API v2

### ISSUE THREAD

**Issue by lokae0** [plaid/link#203]
| Name              | Value              |
| ----------------- | ------------------ |
| Link `apiVersion` |      v2              |
| Link `env`        |       sandbox / prod             |
| LinkKit version   |      1.0.10              |
| iOS version       |      10.x              |
| iOS device        |       All             |

### A detailed description of the steps to reproduce the issue

* Present Link in development mode and choose any bank 
* Use user: user_good / pass: error_MFA_NOT_SUPPORTED (or any error code)
* See failure screen
* Dismiss modal
* Examine error object in `linkViewController(didExitWithError:)`

### What you expected to see?
Per Brandon Huang, we should be able to find errors with codes or statuses reflecting those listed here (such as `MFA_NOT_SUPPORTED`): https://plaid.com/docs/api/#errors 

### What you saw instead?
Codes reflecting those listed in https://plaid.com/docs/legacy/api/#response-codes, such as 1208

### Further logging output:
Production:
Wells 2FA error:
Error Domain=PLKPlaidLinkAPIErrorDomain Code=1210 "The security rules for this account restrict access. Disable ‘Enhanced Sign On’ in your Wells Fargo settings." UserInfo={NSLocalizedDescription=The security rules for this account restrict access. Disable ‘Enhanced Sign On’ in your Wells Fargo settings.}

Metadata:
["status": requires_code, "request_id": xxxxx, "institution": {
    "institution_id" = "ins_4";
    name = "Wells Fargo";
}, "plaid_api_request_id": <null>]

Sandbox:
Error with username: "user_good", password: "error_ ITEM_NOT_SUPPORTED":
Error Domain=PLKPlaidLinkAPIErrorDomain Code=1210 "The given account is not currently supported for this financial institution. We apologize for the inconvenience." UserInfo={NSLocalizedDescription=The given account is not currently supported for this financial institution. We apologize for the inconvenience.}

Metadata:
["status": requires_credentials, "request_id": xxxxx, "institution": {
    "institution_id" = "ins_4";
    name = "Wells Fargo";
}, "plaid_api_request_id": <null>]

Error with username: "user_good", password: "error_ MFA_NOT_SUPPORTED":
Error Domain=PLKPlaidLinkAPIErrorDomain Code=1208 "The multi-factor security features enabled on this account are not currently supported for this financial institution. We apologize for the inconvenience." UserInfo={NSLocalizedDescription=The multi-factor security features enabled on this account are not currently supported for this financial institution. We apologize for the inconvenience.}

**Comment by afh** [comment]
Thank you for raising this @lokae0, the issue will be addressed with the upcoming release of LinkKit.

**Comment by afh** [comment]
Hi @lokae0 the newly released version of LinkKit 1.1.0 addresses this issue.

**Comment by lokae0** [comment]
Great. Thanks for the update @afh!
