### ISSUE TITLE
Institution Select Doesn't Show Any Institutions to Select

### ISSUE THREAD

**Issue by sidbatra** [plaid/link#209]
I was testing Plaid Link and developing with my personal credentials with CLIENT_ID=5933ab4abdc6a401d71d846c and everything was working fine.

Now to get to production, I switched to our company's account with CLIENT_ID=59c00106bdc6a40ac87ed1bc and the rest of the code is the same.

However, with these new credentials, I'm no longer seeing any any institutions to select on web or mobile web (screenshot attached). If I searched for an institution and add it everything works fine.

I also reproduced this with the ruby sample app, so I'm fairly certain it is nothing in the code itself, I'll really appreciate some help, thank you!

Related support ticket: https://dashboard.plaid.com/support/page/1/37517

**Comment by pbernasconi** [comment]
@sidbatra – thanks for flagging this issue, we're actively working towards getting your production version of Link fixed and will update this thread shortly!

**Comment by sidbatra** [comment]
Thank you! If it helps, I noticed that this started with plaid 2.0.67, versions till 2.0.66 seem to work fine. I also tested with another new test id, and it is affecting all new client ids.

**Comment by pbernasconi** [comment]
Hey @sidbatra – we've fixed your issue and I've verified that everything is back to normal for your two client_ids, per the codepens below:

- `5933ab4abdc6a401d71d846c`: https://codepen.io/pbernasconi/pen/bojbjd?editors=1100
- `59c00106bdc6a40ac87ed1bc `: https://codepen.io/pbernasconi/pen/jGpNpr?editors=1100

**Comment by sidbatra** [comment]
Works, you guys are amazing, thank you so much for the fast turnaround!
