### ISSUE TITLE
plaid.open() in web api opens a new browers in ionic 2 app (cordova)

### ISSUE THREAD

**Issue by cgbrucezjy** [plaid/link#210]
|       Name       | Value |
|------------------|-------|
| Link `env`       |   sandbox    |
| Browser          |    mobile chrome on android   |
| Operating system |   android     |

### A detailed description of the steps to reproduce the issue

* plaid.open() opens a webpage instead of staying within the app
* 
* 

### What you expected to see?
user plaid web api in ionic 2 (cordova based app) plaid.open() is expected to stay within the app view instead of opening it in web browser
### What you saw instead?
it opens another web browser

### propose
a cordova plugin or window.open("",_self)
###
---

When submitting an issue for [**Plaid Link iOS**](https://github.com/plaid/link/tree/master/ios)
please include the following information:

| Name              | Value              |
| ----------------- | ------------------ |
| Link `apiVersion` |                    |
| Link `env`        |                 |
| LinkKit version   |                    |
| iOS version       |                    |
| iOS device        |                    |

### A detailed description of the steps to reproduce the issue

* 
* 
*

**Comment by pbernasconi** [comment]
@cgbrucezjy - please check out this example repo for how to use Link inside of Ionic 2:

https://github.com/pbernasconi/plaid-link-ionic-2-example

**Comment by pbernasconi** [comment]
@cgbrucezjy going to close this out for now since that example should be working as-is, but please feel free to re-open if you continue to have an issue using Link with Ionic 2.
