### ISSUE TITLE
account_id not returned for connected bank account

### ISSUE THREAD

**Issue by hsmith825** [plaid/link#211]
*Please do not include your API `secret` or `public_key` in any issue.*
When submitting an issue for [**Plaid Link iOS**](https://github.com/plaid/link/tree/master/ios)
please include the following information:

| Name              | Value              |
| ----------------- | ------------------ |
| Link `apiVersion` |                    |
| Link `env`        |      production              |
| LinkKit version   |   1.0.7                 |
| iOS version       |    11.0.2                |
| iOS device        |     iPhone 6               |

### A detailed description of the steps to reproduce the issue
1. Running environments as follows:
Xcode 9, IOS 11.0.2, Swift3, iPhone 6

2. Used as reference the swift code at: https://github.com/plaid/link/blob/master/ios/LinkDemo-Swift3/LinkDemo-Swift3/ViewController.swift

3. Code Snipet is as follows:
```
func presentPlaidLinkWithCustomConfiguration() {
            // With custom configuration
            let linkConfiguration = PLKConfiguration(key: "**********", env: .production, product: .auth)
            linkConfiguration.clientName = "Flickitt"
            let linkViewDelegate = self
            let linkViewController = PLKPlaidLinkViewController(configuration: linkConfiguration, delegate: linkViewDelegate)
            if (UI_USER_INTERFACE_IDIOM() == .pad) {
                linkViewController.modalPresentationStyle = .formSheet;
            }
            present(linkViewController, animated: true)
        }
        func handleSuccessWithToken(_ publicToken: String, metadata: [String : Any]?) {
            print("LoginView, login,Success, message: token: \(publicToken)\nmetadata: \(metadata ?? [:])")
extension LoginViewController : PLKPlaidLinkViewDelegate {
    func linkViewController(_ linkViewController: PLKPlaidLinkViewController, didSucceedWithPublicToken publicToken: String, metadata: [String : Any]?) {
        dismiss(animated: true) {
            // Handle success, e.g. by storing publicToken with your service
            NSLog("Successfully linked account!\npublicToken: \(publicToken)\nmetadata: \(metadata ?? [:])")
            self.handleSuccessWithToken(publicToken, metadata: metadata)
        }
    }
```

4. I connected with the bank and OK the link to Flickitt as directed 

### What you expected to see?

I expected a response that included the publicToken and the metadata that included the account_id.  Something similar to the following:
```
Success, message: token: public-production-0e29ca08-8a47-427f-9c7b-272cefc48772
metadata: ["status": connected, "account": {
    id = "<null>";
    name = "<null>";
}, "request_id": pNy2M, "institution": {
    "institution_id" = "ins_120012";
    name = "Bank of the West";
}, "plaid_api_request_id": <null>, "account_id": nnnnnnnnn]
````

### What you saw instead?

The actual response includes a public token and "<null>" for the account_id as shown below.
```
Success, message: token: public-production-0e29ca08-8a47-427f-9c7b-272cefc48772
metadata: ["status": connected, "account": {
    id = "<null>";
    name = "<null>";
}, "request_id": pNy2M, "institution": {
    "institution_id" = "ins_120012";
    name = "Bank of the West";
}, "plaid_api_request_id": <null>, "account_id": <null>]
```

### A screenshot that shows the state of the UI (if applicable)

**Comment by afh** [comment]
Hi @hsmith825, thanks for reaching out.

The `account_id` metadata field is only set for `selectAccount` flows, which means that the [`selectAccount` option](https://github.com/plaid/link/tree/master/ios#optional-plkplaidlinkconfiguration-items) needs to be set to `YES` in your `PLKConfiguration`:

```
let linkConfiguration = PLKConfiguration(key: "<#YOUR_PLAID_PUBLIC_KEY#>", env: .production, product: .auth, selectAccount: true, longtailAuth: false, apiVersion: PLKAPIv2)
```

---

P.S.:
I'd like to recommend updating LinkKit in your application since there have been [several improvements](https://github.com/plaid/link/blob/master/ios/CHANGELOG.md) in [4 releases](https://github.com/plaid/link/releases) since version 1.0.7. 🙂

**Comment by hsmith825** [comment]
Hi Alexis,

First I updated LinkKit to 1.1.0.   Your suggestion did not work.  
	1. If I include the apiVersion: PLKAPIv2, I get PLKAPIv2 undeclared.
	2 After removing apiVersion: PLKAPIv2 which is the default anyway, I get “Type of expression is ambiguous without more context.
	3. If I remove selectAccount: true, it works but I don’t get the account_id.

You do know I am using Plaid Link iOS?

Any other sugestions?

Thanks!
Howard

**Comment by afh** [comment]
Hi @hsmith825,

yes, I am very much aware and delighted that you are using the native Plaid Link iOS SDK (a.k.a LinkKit.framework) 🙂 

The code example I suggested contained a typo, the correct line is:
```
let linkConfiguration = PLKConfiguration(key: "<#YOUR_PLAID_PUBLIC_KEY#>", env: .production, product: .auth, selectAccount: true, longtailAuth: false, apiVersion: .PLKAPIv2)
```
please notice the `.` in front of `.PLKAPIv2`.

I'll keep this issue open, until you've verified it works for you.

**Comment by hsmith825** [comment]
Hi Alexis,

Thanks for your quick response.  It worked and that problem is solved.  We are also trying to add Plaid features to our IOS iMessage extension app.  In this app the available screen size is a little less than that on a normal app. It turns out that your submit button is below the window.  Is there away we can move the submit button to the top, make the window smaller, or provide scrolling? 

Thanks for your excellent support!
Howard

**Comment by afh** [comment]
Hi @hsmith825,

thanks for confirming that the select account flow now works for you. I'm going to close this issue.

Regarding the available screensize I kindly ask you to create a new issue and include information such as the `CGRect` of the view in which you are displaying `PLKPlaidLinkViewController` and if possible a screenshot, that would be quite helpful.

Glad I can help :)
