### ISSUE TITLE
Submit Button does not display in  iMessage extension apps

### ISSUE THREAD

**Issue by hsmith825** [plaid/link#212]
*Please do not include your API `secret` or `public_key` in any issue.*

When submitting an issue for [**Plaid Link iOS**](https://github.com/plaid/link/tree/master/ios)
please include the following information:

| Name              | Value              |
| ----------------- | ------------------ |
| Link `apiVersion` |       PLKAPIv2            |
| Link `env`        |    production                |
| LinkKit version   |         1.1.0           |
| iOS version       |           11.0.3         |
| iOS device        |            iPhone 5        |

### A detailed description of the steps to reproduce the issue

1. Executed the following code on an iMessageExtension App.  
2. I am displaying the PLKPlaidLinkViewController view in an expanded window.  The screenshot (attached) shows the Select Account Window.  We covered the confidential bank account info.  Notice the submit button is not displayed.  
3. I use Apple's auto layout since the code would be large if I had to do the CGRect computations manually.
Below is the executed code to call the PLKPlaidLinkViewController:
```
func presentPlaidLinkWithCustomConfiguration() {
            // With custom configuration
            let linkConfiguration = PLKConfiguration(key: "<#PUBLIC_KEY#>", env: .production, product: .auth, selectAccount: true, longtailAuth: false, apiVersion: .PLKAPIv2)
            linkConfiguration.clientName = "Flickitt"
            let linkViewDelegate = self
            let linkViewController = PLKPlaidLinkViewController(configuration: linkConfiguration, delegate: linkViewDelegate)
            if (UI_USER_INTERFACE_IDIOM() == .pad) {
                linkViewController.modalPresentationStyle = .formSheet;
            }
            present(linkViewController, animated: true)
        }
```

### What you expected to see?
Expect to get screens with the Submit button showing.  Notice the Screen Shot (attached).  I get displays similar to this on all screens with the submit button which makes it unusable for iMessage Extension apps.

 Two solutions that would solve the problem are as follows:
1. All a Select Button placement option with at least two options (Top, Buttom).

2. Provide vertical scrolling.

 
### What you saw instead?
Missing Submit button
### A screenshot that shows the state of the UI (if applicable)
Attached
![account selection screen shot](https://user-images.githubusercontent.com/1394060/31644013-902d9842-b2a8-11e7-8d45-26fc552bee00.png)

**Comment by afh** [comment]
Hi @hsmith825,

embedding Plaid Link iOS in an iMessage app has worked for me quite well in regards to the issue that you are observing:
<img width="40%" src="https://user-images.githubusercontent.com/16507/31743280-6bfb4f38-b40f-11e7-9f32-1d43f25e6655.png">

Here's a screenshot of the Interface Bulider setup I've used:
<img width="40%" src="https://user-images.githubusercontent.com/16507/31743285-6e71a4d8-b40f-11e7-9685-894a9bb1ef91.png">

The things that I'd verify is:
* Is the superview of the `PLKPlaidLinkViewController` view respecting the safe area?
* Is the `PLKPlaidLinkViewController`'s view frame set to its superview bounds on `viewWillLayoutSubviews:`?

Here's the code snippet from the `MessagesViewController`:
```
- (void)viewDidLoad {
    [super viewDidLoad];
   
    NSString* publicKey = @"<#PUBLIC_KEY#>";
    PLKEnvironment environment = PLKEnvironmentDevenv;
    PLKProduct product = PLKProductAuth;
    BOOL selectAccount = YES;
    BOOL longtailAuth = NO;
    PLKAPIVersion apiVersion = PLKAPIv2;
    PLKConfiguration* configuration = [[PLKConfiguration alloc] initWithKey:publicKey
                                                                        env:environment
                                                                    product:product
                                                              selectAccount:selectAccount
                                                               longtailAuth:longtailAuth
                                                                 apiVersion:apiVersion];
    self.linkViewController = [[PLKPlaidLinkViewController alloc] initWithConfiguration:configuration
                                                                   delegate:self];
    
    [self.containerView addSubview:self.linkViewController.view];
}

- (void) viewWillLayoutSubviews {
    [super viewWillLayoutSubviews];
    self.linkViewController.view.frame = self.containerView.bounds;
}
```

It's interesting to see LinkKit being embedded in an iMessage app and I will look into how LinkKit can be made safe for use in an application extension.

What other challenges do you see with LinkKit being used in an iMessage app?

**Comment by hsmith825** [comment]
Hi Alexis,

Thanks for your timely response.  I was shutdown for a week an could not try your changes.  I will let you know if it solves my problem………………….≥≥

Thanks!
Howard

**Comment by afh** [comment]
Hi @hsmith825,

any update on this?

**Comment by hsmith825** [comment]
Unfortunately I have been sidelined by The flu.  Should be back at work on Monday.

Sorry.
Howard

**Comment by hsmith825** [comment]
We have scheduled this support in our 11/15 release so I have to jump on it as soon as I return to work.

Thanks for your support!
Howard

**Comment by hsmith825** [comment]
Hi Alexis,

Before I could get back to the submit button problem, we ran into an unexpected problem when running a validation with the app store.We were preparing to run test flight on the rest of the app and we got the following error in the validation step of appstore:

iTunes Store Operation Failed
Invalid Signature. Code object is not signed at all. The file at path [FlickittMessages11.app/Frameworks/LinkKit.framework/prepare_for_distribution.sh] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html <https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html>

We have tried the suggestions offered in the message.  We did not want to remove the LinkKit and test the rest of the app.  We now that will validate.

Any suggestions?

Thanks!
Howard

**Comment by afh** [comment]
Hi @hsmith825,

yes, `prepare_for_distribution.sh` needs to be removed prior to App Store submission, and the script removes itself when run. That's all part of the manual integration process, yet you ran into issues with that when using Cocoapods (see #204).

Until we have a solution to support the different modes of integration remove the script, prior to building your release archive.

**Comment by hsmith825** [comment]
Hi Alexis,

We removed the script as you indicated since we integrate with pod.  We did not add the script back.  It is removed when we remove plaid from our product.   It is added back by Cocoa pod when we add plaid back.  How can we remove the script prior to release.  We can’t even locate it.

Thanks!

Howard

**Comment by afh** [comment]
Hello @hsmith825,

after some investigation I come to the following conclusions:

* When integrating LinkKit with Cocoapods the `Prepare for Distribution` build phase script **is** necessary (I'll update the documentation accordingly) and needs to be as follows:
```
cp "${PODS_ROOT}"/Plaid/ios/LinkKit.framework/prepare_for_distribution.sh "${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}"/LinkKit.framework/prepare_for_distribution.sh
"${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}"/LinkKit.framework/prepare_for_distribution.sh
```

* The issues you observed regarding the build script phase (#204) stemmed from the `Prepare for Distribution` build phase script being added to the iMessage Extension target, yet the build phase script **must** be added to the host application target **after** the `[CP] Embed Pods Frameworks` phase.
<img width="1072" alt="linkcocoapod" src="https://user-images.githubusercontent.com/16507/32244031-80b4a102-be34-11e7-857e-3a841e3c2798.png">

Please let me know if this resolves the issues you are observing.

**Comment by hsmith825** [comment]
Hi Alexis,

Thanks for the update.  It will take a few days for me to try this.  I had to shift to something else that will take a couple of days.  I will let you know if this works for me.

Thanks!
Howard

**Comment by michaelckelly** [comment]
@hsmith825 - Let me know if we should go ahead and close this issue out!
