### ISSUE TITLE
SecurityError: Blocked a frame with origin * from accessing a frame with origin "https://cdn.plaid.com".

### ISSUE THREAD

**Issue by jsvg** [plaid/link#213]
* Link env: production
* Browser: appears to be exclusive to mobile chrome
* OS: iOS

Our production deployment tracks errors with Sentry. We've had around 50 `SecurityError` reports. The error message is as follows:

`Blocked a frame with origin "https://ourcompanydomain.com" from accessing a frame with origin "https://cdn.plaid.com". Protocols, domains, and ports must match.`

As far as I'm aware, we are not attempting to access the plaid iFrame, so the source of this error is unknown. Hoping somebody on the plaid team might be able to shed light on whether or not this error is actionable.

**Comment by pbernasconi** [comment]
hey @jsvg – please excuse the delayed reply. Would you mind sending me an email at paolo@plaid.com with your `client_id` or `public_key` so that I can check our logs. Also if you have a link to test your integration that would be very helpful!

**Comment by jsvg** [comment]
Hey @pbernasconi thanks for the response - closing this issue in favor of following up via email.
