### ISSUE TITLE
Carthage build of 1.1.0 prevents app store submission

### ISSUE THREAD

**Issue by idris** [plaid/link#214]
When using version 1.1.0 (via Carthage), Apple rejects the binary with this message:
> **Invalid Bundle** - Disallowed LLVM instrumentation. Do not submit apps with LLVM profiling instrumentation or coverage collection enabled. Turn off LLVM profiling or code coverage, rebuild your app and resubmit the app.

When I switch back to version 1.0.1, the binary is accepted.

**Comment by afh** [comment]
Hi @idris,

thanks for filing this issue. LinkKit version 1.1.0 is the first release built using Xcode 9, I'll look into it and make the necessary changes.

**Comment by aarons22** [comment]
Just wanted to chime in and say that this is also an issue when using version 1.1.0 via Cocoapods

**Comment by afh** [comment]
Thanks @aarons22, that makes sense since Cocoapods and Carthage use the same LinkKit.framework binary.

**Comment by afh** [comment]
Hi @idris, hi @aarons22,

[LinkKit 1.1.1](https://github.com/plaid/link/releases/tag/ios%2F1.1.1) has been released and addresses the issue according to [Technical Q&A QA1964 – Resolving App Rejections for GCC and LLVM Instrumentation](https://developer.apple.com/library/content/qa/qa1964/_index.html).

```
% nm -m -arch all LinkKit.framework/LinkKit | grep -c gcov
0
% otool -l -arch all LinkKit.framework/LinkKit | grep -c __llvm_prf
0
```
