### ISSUE TITLE
Cococ

### ISSUE THREAD

**Issue by Sethmr** [plaid/link#216]
When submitting a testflight build with Cocoapods install 'Plaid 1.1.1 ', the prepare_for_distribution.sh file throws an error. Luckily, I had noticed that in the manual install, there was a run script required to fix this very issue. 

After adding this:

```
cp "${PROJECT_DIR}"/Pods/Plaid/ios/LinkKit.framework/prepare_for_distribution.sh "${CODESIGNING_FOLDER_PATH}"/Frameworks/LinkKit.framework/prepare_for_distribution.sh
"${CODESIGNING_FOLDER_PATH}"/Frameworks/LinkKit.framework/prepare_for_distribution.sh
```

I was able to get the project to submit to the app store. 

I would either fix your installation guide to include the runscript in both the cocoapods section and the manual section, or fix this issue in the cocoapods install route.

**Comment by afh** [comment]
Hi @Sethmr,

thanks for reaching out. What was the exact error that was thrown by `prepare_for_distribution.sh`?

**Comment by Sethmr** [comment]
If I come across it again, I will definitely snapshot it and post it here.

**Comment by afh** [comment]
Hi @Sethmr,

that is the error that you observe after having deleted derived data?

**Comment by afh** [comment]
@Sethmr, did you also ensure "that the Prepare for Distribution build phase runs after the `[CP] Embed Pods Frameworks` build phase."?

**Comment by Sethmr** [comment]
I did not check that... Good catch!

**Comment by afh** [comment]
And yes you can run the script as a pre action when archiving, the post action will likely have no effect, since LinkKit.framework has already been bundled with your application into an `.xcarchive`.

Thanks for flagging this, I will update the documentation accordingly.

**Comment by adamdahan** [comment]
Same issue over here but that script @Sethmr mentioned doesn't work for me either.

**Comment by afh** [comment]
Hi @adamdahan,

what is the exact error message that you see?

**Comment by Sethmr** [comment]
This is the only script I use nowadays. 
![screen shot 2018-09-20 at 1 33 00 pm](https://user-images.githubusercontent.com/10062416/45836059-c68f3800-bcd9-11e8-986a-dc222f1044ff.png)

**Comment by afh** [comment]
Thanks for clarifying @Sethmr :)
