### ISSUE TITLE
public_token/exchange Errors

### ISSUE THREAD

**Issue by hsmith825** [plaid/link#221]
*Please do not include your API `secret` or `public_key` in any issue.*
---
Al
When submitting an issue for [**Plaid Link iOS**](https://github.com/plaid/link/tree/master/ios)
please include the following information:

| Name              | Value              |
| ----------------- | ------------------ |
| Link `apiVersion` |         PLKAPIv2           |
| Link `env`        |             production       |
| LinkKit version   |     1.1.3               |
| iOS version       |         11.2.1           |
| iOS device        |            iPhone        |

Server is .Net
Programing language is c#

### A detailed description of the steps to reproduce the issue
I am attemtping to use the public token to exchange for an acccess token.  I first attempted togenerate the access token using the URL I am currently using on another IOS app with POST to https://api.plaid.com/exchange_token.  With this URL I get an unauthorized error.  With a little research I disccovered you have a new URL which is https://production.plaid.com/item/public_token/exchange.  I get error: (415) Unsupported Media Type.

Here is my code snippet in C#.  This code is currently running on an existing product with the older URL above:
```
NameValueCollection wcollection = new NameValueCollection();
            wcollection.Add("client_id", ConfigurationManager.AppSettings["client_id"]);   //production;
            wcollection.Add("public_token", plaid_public_token);
            wcollection.Add("secret", ConfigurationManager.AppSettings["secret"]);  //production
            try
            {
                using (var client = new WebClient())
                {
                    byte[] response_array = client.UploadValues(new Uri("https://production.plaid.com/item/public_token/exchange"), "POST", wcollection);  //production
                    PlaidTokens object_reply = JsonConvert.DeserializeObject<PlaidTokens>(reply);
                    return object_reply.access_token;
                }
            }
```

Any help is appreciated.
Thanks!
Howard

**Comment by afh** [comment]
Hi @hsmith825,

can you please provide a `request_id` from one of the responses?

**Comment by afh** [comment]
Additionally can you post the actual response from the server?
Response code 415 may be an indication that the request does not properly set the HTTP `Content-type` header to `application/json`

**Comment by hsmith825** [comment]
Hi Alexis,

 

The actual response from the server is as follows:

1.	For request URL https://production.plaid.com/item/public_token/exchange

The remote server returned an error: (415) Unsupported Media Type.

2.	For request URL https://api.plaid.com/exchange_token

The remote server returned an error: (401) Unauthorized.

Works in the app that uses jQuery Https call.

Does not work when I am using AlamoFire and Swift.

 

Thanks!

Howard

**Comment by afh** [comment]
Hi @hsmith825 

apologies for my vague question :)

When I asked for the actual response I did not ask for the HTTP response status code, you were kind enough to provide that already. What I wanted to ask for was the response body, which should include some JSON containing details about what is wrong with the request, e.g.
```
{
    "display_message": null,
    "error_code": "INVALID_HEADERS",
    "error_message": "Content-Type must be one of [application/json]",
    "error_type": "INVALID_REQUEST",
    "request_id": "kwhmd"
}
```

**Comment by hsmith825** [comment]
Hi Alexis,

I hit a rate limited exceeded.  I am assuming this is due to thee number of request I have made trying to resolve this issue.  How long before I can start testing again.

Thanks!
Howard

**Comment by afh** [comment]
Hi @hsmith825,

usually rate limits are per minute so you should be able to test again.

If possible try to be as specific as possible, e.g. in this case on which endpoint did you hit a rate limit. The more specific the issue description the better we can assist 🙂

**Comment by hsmith825** [comment]
I was selecting the account in the bank.  In the dialogue I had a message that I could not connect to my account at that time.  I checked the account and there is not a problem for normal access.  I had an option to select another account or exit. on exit I have the following meta object in linkConfiguration error call.  

metadata = ["status": requires_credentials, "request_id": WRACd, "institution": {
    "institution_id" = "ins_120012";
    name = "Bank of the West";
}, "link_session_id": c5b56b06-5fb7-416c-85e3-1f50eb6c7189]

Its been over an hour and I still can not access the account through Plaid.  I suspect it may be a limit imposed by my bank.

Thanks!
Howard

**Comment by afh** [comment]
Hi @hsmith825,

What you are describing now seems unrelated to the initial issue;
at this point please open a [support ticket through the dashboard](https://dashboard.plaid.com/support/new/product-and-development), it seems the issues you observe are of a more general nature with the integration than specific to Link or Link for iOS.

**Comment by hsmith825** [comment]
This original issue is not resolved.  I only mentioned the rate limit problem because it prevented me from resolving this  issue.  The limit rate is no longer a problem.  We can not get public_token/exchange to work.  I have not been able to get a response body.  This issue should not be closed.
Thanks!

**Comment by afh** [comment]
Hi @hsmith825,

while I understand that your issue is not solved yet, the issue you observe is about the integration and not Plaid Link or Plaid Link for iOS itself, which are handled here, therefore contacting support through the dashboard as mentioned above is the right way forward to get the best assistance 🙂

**Comment by Saurabhiws** [comment]
How can i get access token from plaid in ios using public key. Is it possible to get in ios side or we need to send publick key to server for next process. Please help me.

**Comment by cconeill** [comment]
Hey @Saurabhiws , Christopher from Plaid Support here 👋 , could you please reach out to us via your [Plaid Dashboard](https://dashboard.plaid.com/support/new)? We're the best team to help you get started with general questions about our API, our Github is better suited for specific questions/bugs related to the code contained in the repo.
