### ISSUE TITLE
New search improvements are hiding "next" button

### ISSUE THREAD

**Issue by noahemmet** [plaid/link#222]
|       Name       | Value |
|------------------|-------|
| Link `env`       |  production     |
| Browser          |    webview   |
| Operating system |    all   |

It appears that the [recent search improvements](https://blog.plaid.com/improved-search/) have an unfortunate side effect: the fuzzier matcher increases the chance of at least one match, which means the empty state's "next" button never appears.

Example:
![external_accounts__lets_link_your_bank_account__simple_2017-12-20_14-41-50](https://user-images.githubusercontent.com/1952578/34314275-b983849c-e726-11e7-9f6f-5ba63d330b3d.png)

We're using that "next" button as the trigger for our trial deposits flow, which customers are no longer able to enter. Would it be possible to either:
- Reduce the fuzziness of the matcher so that the empty screen appears more easily, or
- Show the "next" button as the last option in the list of search results.

Thanks!

**Comment by pbernasconi** [comment]
Hey @noahemmet – please excuse the delayed reply!

We've received similar feedback, and can agree that while fuzzy matching can help your users find their bank better, there are now more results which doesn't allow users to exit via the "no results found" copy and action button.

We're looking into alternatives and a fix in the next few days and will share an update with you soon!

**Comment by pbernasconi** [comment]
@noahemmet – your feedback was heard and we've just recently shipped an improvement to the user experience for allowing users to exit from Link when search results are still present.

See the screenshot below for the new UI in Link

<img width="382" alt="screen shot 2018-02-01 at 10 40 09 am" src="https://user-images.githubusercontent.com/1716394/35696478-774ec8a8-073c-11e8-81a7-e6e97218a6a4.png">
