### ISSUE TITLE
"Search request timed out, try again with better connection" on Sandbox local install

### ISSUE THREAD

**Issue by SAMGOOCH1** [plaid/link#223]
*Please do not include your API `secret` or `public_key` in any issue.*
---
When submitting an issue for Link on the web or within a Webview, please include the following information:

|       Name       | Value |
|------------------|-------|
| Link `env`       |    sandbox   |
| Browser          |    chrome   |
| Operating system |   MacOS Sierra    |

### A detailed description of the steps to reproduce the issue

For the quickstart demo - Installed requirements.txt, put in credentials for sandbox and went to localhost:5000.

Expected to see list of banks, 404 -

* 
* 
* 

### What you expected to see?

List of banks in link app

### What you saw instead?

The error "Search request timed out, try again with better connection" on Sandbox local install.

I see a 404 error in the terminal: 127.0.0.1 - - [26/Dec/2017 22:40:36] "GET /favicon.ico HTTP/1.1" 

### A screenshot that shows the state of the UI (if applicable)
![image](https://user-images.githubusercontent.com/24403216/34373276-0747e518-ea8f-11e7-8a6f-3fb043ff0adf.png)

---

When submitting an issue for [**Plaid Link iOS**](https://github.com/plaid/link/tree/master/ios)
please include the following information:

| Name              | Value              |
| ----------------- | ------------------ |
| Link `apiVersion` |                    |
| Link `env`        |                    |
| LinkKit version   |                    |
| iOS version       |                    |
| iOS device        |                    |

### A detailed description of the steps to reproduce the issue

* 
* 
*

**Comment by michaelckelly** [comment]
@SAMGOOCH1 - are you still experiencing this issue? Are you seeing any other errors or issues in your browser console?

**Comment by hikoship** [comment]
Same issue here. Have you solved it?

**Comment by tirthmehta** [comment]
Hi, Im facing this same issue. I tried to do it with the python quickstart. Anyone here has any updates on this one?

**Comment by dmsqui** [comment]
thanks hikoship that got it to work for me
