### ISSUE TITLE
Text field caret misplaced on iPhone X

### ISSUE THREAD

**Issue by pingd** [plaid/link#225]
When using Plaid in WKWebKit on iPhone X, the text field caret is misplaced (due to view scrolling in order to show keyboard). Tested with Plaid WKWebKit example and in separate project.

|       Name       | Value |
|------------------|-------|
| Link `env`       |   sandbox    |
| Browser          |   WKWebKit    |
| Operating system |   iOS 11.2   |

### A detailed description of the steps to reproduce the issue

* select a bank
* tap on `password` text field

### What you expected to see?
The caret should stay within the text field's bounds.
### What you saw instead?
The caret is misplaced.
### A screenshot that shows the state of the UI (if applicable)
<img width="362" alt="iPhone X simulator screenshot" src="https://user-images.githubusercontent.com/4449503/34882761-da102ffc-f7b7-11e7-900a-f2670ab20108.png">

**Comment by pbernasconi** [comment]
Thanks for raising this issue @pingd – we're looking into reproducing it this week and will keep you updated with a fix!

**Comment by bowersz** [comment]
Any update on this?  I'm seeing this issue as well, only on more devices than just the iPhone X. The username field starts out okay, but when the Password field is selected, the cursor is below the input field like shown above. Then, if you go back to the username field, the cursor is below that field also.

**Comment by afh** [comment]
Hi @bowersz expect changes addressing the iPhone X soon.

**Comment by afh** [comment]
Hi @bowersz, @pingd, can you please retest? We have deployed changes that address the iPhone X specifically.

**Comment by pingd** [comment]
Hi @afh, looks good now. Thanks!

**Comment by afh** [comment]
Happy to hear that the changes corrected the issue you were observing, thanks for checking, @pingd !
