### ISSUE TITLE
Allow adding an extra action cell to search results

### ISSUE THREAD

**Issue by klaaspieter** [plaid/link#228]
| Name              | Value              |
| ----------------- | ------------------ |
| Link `apiVersion` |      2              |
| Link `env`        |           sandbox         |
| LinkKit version   |   1.1.4                 |
| iOS version       |          11.2          |
| iOS device        |       iPhone 7 Simulator             |

### A detailed description of the steps to reproduce the issue

* Search for a bank

### What you expected to see?

An option to add bank account manually. We prefer Plaid in our app, but we allow trial deposits for bank accounts that Plaid doesn't support. We changed the empty view action button from “Exit” to “Add Manually” and we would like to have a similar option add the bottom of search results.

### What you saw instead?

Plaid supported bank accounts

### A screenshot that shows the state of the UI (if applicable)

<details><summary>:iphone: :camera:</summary>

![simulator screen shot - iphone 7 - 2018-02-01 at 10 26 00](https://user-images.githubusercontent.com/98880/35671012-69544b80-073a-11e8-99ca-0d5e51537224.png)

![simulator screen shot - iphone 7 - 2018-02-01 at 10 28 13](https://user-images.githubusercontent.com/98880/35671079-9ddc0438-073a-11e8-9c08-e2aac2d45bca.png)

</details>

**Comment by afh** [comment]
Hello @klaaspieter, thank you for reaching out. Fortunately we have something already planned that should address your needs.

**Comment by afh** [comment]
One thing I noticed in the screenshots you provided, @klaaspieter, is that the appearance of the `Cancel` button on the `UISearchBar` seems to have been customized. Is this intentional and are you using [`UIAppearance`](https://developer.apple.com/documentation/uikit/uiappearance) for this?

**Comment by klaaspieter** [comment]
@afh Not intentionally, but yes we do use `UIAppearance` to customize various aspects of our apps, including the search bar. I had never noticed it carried over to your UI.

**Comment by afh** [comment]
@klaaspieter Thank you for your quick response. We have seen uses of `UIAppearance` affecting LinkKit's UI before, it usually comes from applying `UIAppearance`  rather "broadly", e.g.

```
[[UINavigationBar appearance] setBarTintColor:myNavBarBackgroundColor];
```

We recommend using [`appearance(whenContainedInInstancesOf:)`](https://developer.apple.com/documentation/uikit/uiappearance/1615013-appearance) to be more specific of where appearance should be altered.

**Comment by afh** [comment]
Hello @klaaspieter I'd like to let you know that [LinkKit version 1.1.7](https://github.com/plaid/link/releases/tag/ios%2F1.1.7) was released and adds an exit button below the search results addressing the feature you requested.

<img width='25%' src='https://user-images.githubusercontent.com/16507/37734673-1a1056a0-2d09-11e8-9693-d47d17b5df9c.png'>
