### ISSUE TITLE
RunScript in BuildPhase

### ISSUE THREAD

**Issue by vijayasri5G4** [plaid/link#230]
When submitting an issue for [**Plaid Link iOS**](https://github.com/plaid/link/tree/master/ios)
please include the following information:

| Name              | Value              |
| ----------------- | ------------------ |
| Link `apiVersion` |                    |
| Link `env`        |            Sandbox        |
| LinkKit version   |       1.1.3             |
| iOS version       |         9.2           |
| iOS device        |          iPhone 8-plus          |

### A detailed description of the steps to reproduce the issue

*  I am implementing  a plaid integration with IOS SDK.  so I followed the plaid documents. so I installed the LINKKIT frame work using cocoa pods. after installing we have to add the Run script in build phase. and then configuration. In plaid documents they show a LINK_ENVIRONMENTS AND LINK_PUBLIC_KEY under user defined in build settings after completion of whole process upto configuration. But in my user defined build settings the LINK_ENVIRONMENT and LINK_PUBLIC_KEY are not present. Why it is not present in my build settings. is there problem with when at the time I changing the {PROJECT_DIR}/LinkKit framework. or any thing else . 
 
What is expecting is The link_environments and link_public_key Is present in build settings

### What you saw instead? LINK_ENVIRONMENTS and LINK_PUBLIC_KEY is not  present in build settings

<details><summary>:camera:</summary>

![screen shot 2018-02-05 at 2 11 31 pm](https://user-images.githubusercontent.com/26701352/35797685-761ef690-0a86-11e8-909a-9d0c71c0fea6.png)
![screen shot 2018-02-05 at 3 11 41 pm](https://user-images.githubusercontent.com/26701352/35797806-e6e3e98a-0a86-11e8-88ab-ff1049d94418.png)

![screen shot 2018-02-05 at 2 06 12 pm](https://user-images.githubusercontent.com/26701352/35797763-c8d1458c-0a86-11e8-9168-b72af89bb1b2.png)

</details>

**Comment by afh** [comment]
Hello @vijayasri5G4, thank you for reaching out.

The custom run script phase *does not* create the build settings¹ these need to be manually added. Also note that the documentation proposes the names `LINK_KEY` and `LINK_ENV` opposed to the ones that you are looking for: `LINK_PUBLIC_KEY` and `LINK_ENVIRONMENT`.
Also note that whatever names you choose for your build settings they *must* match with the names used in the application's `Info.plist`.
You may also enter your public key and desired environment directly into the applications `Info.plist`, removing the need for custom build settings, which may be a much easer albeit less flexible solution.

¹ the "script […] removes any non-iOS device code from the framework which is included to support running LinkKit in the Simulator but may not be distributed via the App Store." –  https://plaid.com/docs/link/ios/#add-run-script

**Comment by vijayasri5G4** [comment]
Thank you . I think it's silly question to you.

**Comment by vijayasri5G4** [comment]
Thank you.

**Comment by afh** [comment]
@vijayasri5G4 You're welcome 🙂
