### ISSUE TITLE
Consistent crash on iOS link during success/exit callbacks

### ISSUE THREAD

**Issue by yinonar** [plaid/link#234]
In some situations the app crashes before the success/exit call backs return, apparently caused by LinkKit. See below for the stack trace. There’s no pattern to the crash though, which makes it difficult to provide more useful information or to reproduce it consistently. Thus far, I've seen this in the sandbox using the dummy credentials for both success and exit callbacks, but I haven't tested extensively in other environments.

| Name              | Value              |
| ----------------- | ------------------ |
| Link `apiVersion` |          n/a          |
| Link `env`        |          sandbox          |
| LinkKit version   |           1.1.3         |
| iOS version       |          11.2          |
| iOS device        |          Simulator          |

**Stack trace below**:
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:

(
	0   CoreFoundation                      0x000000011119612b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000110832f41 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001111d60cc _CFThrowFormattedException + 194
	3   CoreFoundation                      0x00000001110a423d -[__NSPlaceholderArray initWithObjects:count:] + 237
	4   CoreFoundation                      0x00000001110aae34 +[NSArray arrayWithObjects:count:] + 52
	5   LinkKit                             0x000000010b6e855b __77-[PLKPlaidLinkViewController(FlowCoordinator) displayLoadingPaneWithContext:]_block_invoke + 281
	6   LinkKit                             0x000000010b6e82cd __96-[PLKPlaidLinkViewController(FlowCoordinator) displaySceneWithIdentifier:context:customization:]_block_invoke + 134
	7   libdispatch.dylib                   0x000000011236f2f7 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x000000011237033d _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x000000011237b5f9 _dispatch_main_queue_callback_4CF + 628
	10  CoreFoundation                      0x0000000111158e39 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	11  CoreFoundation                      0x000000011111d462 __CFRunLoopRun + 2402
	12  CoreFoundation                      0x000000011111c889 CFRunLoopRunSpecific + 409
	13  GraphicsServices                    0x00000001158949c6 GSEventRunModal + 62
	14  UIKit                               0x000000010de7b5d6 UIApplicationMain + 159
	15 <app name>                              0x0000000107481747 main + 55
	16  libdyld.dylib                       0x00000001123ecd81 start + 1

```

**Comment by afh** [comment]
@yinonar Thank you for reporting this, we're investigating

**Comment by afh** [comment]
@yinonar One thing that might be helpful to know is which institution was used when the crash happened.

**Comment by yinonar** [comment]
The crash happened on both Chase and Citi

**Comment by afh** [comment]
Thank @yinonar, that's helpful.

I see you are using version 1.1.3 of LinkKit, any reason you are using that specific, outdated version? I'd appreciate if you could try to reproduce the issue using the latest version [1.1.5](https://github.com/plaid/link/releases/tag/ios%2F1.1.5), which was released yesterday.

**Comment by yinonar** [comment]
@afh It still exists in 1.1.5 (although thanks for the upgrade tip, 1.1.5 removes the native alert modal which is nice). I believe I can reproduce it now, at least in one case: open link in sandbox, tap development mode in the top right, go back, then enter user_good, pass_good on chase; just crashed for me.

**Comment by afh** [comment]
Thank you for verifying that the issues persists in LinkKit 1.1.5. Unfortunately we have been unable to reproduce it on our end using the steps you provided. We're tracing through the involved code paths to locate where `nil` might be inserted into an `NSArray`.

Would you be able to provide a screencast demonstrating the issue? That might provide us with useful details.
```
% xcrun simctl io booted recordVideo link_234.mov
% ffmpeg -i link_234.mov -s 738x1328 -pix_fmt rgb24 -r 25 -f gif - \
| gifsicle --optimize=3 --delay=3 > link_234.gif
```

Note that `-s 738x1328` depends on the simulated device screen size and whether device bezels are shown or not.

**Comment by yinonar** [comment]
Happy to hop on the phone next week, may be easiest. I'd like to talk through this to ensure it's exclusively a sandbox crash prior to releasing. Steps to reproduce (happens every time):
1. Present PLKPlaidLinkViewController in the sandbox
2. Click on the development mode icon in the top right
3. Click back
4. Enter user_good / pass_good credentials
5. App crashes

Also helpful, here's how we're presenting link (note that we have our own UI for search):
```
let config = PLKConfiguration(key: <public_key>, env: .sandbox, product: .transactions)
let linkViewController = PLKPlaidLinkViewController(institution: “ins_5”, configuration: config, delegate: self)
if (UI_USER_INTERFACE_IDIOM() == .pad) {
      linkViewController.modalPresentationStyle = .formSheet;
}
present(linkViewController, animated: true)
```

**Comment by afh** [comment]
Thank you very much @yinonar for the updated description on how to reliably reproduce the issue; I'm able to reproduce it on my end — the crucial part was the institution based initializer. It does look an issue exclusive to sandbox, yet I'm further investigating the root cause and will follow up with details.

**Comment by afh** [comment]
Hi @yinonar, further investigation and testing revealed that it is a sandbox-only issue, a fix is underway and will be published with the next release.

I propose to [find a good time](http://everytimezone.com) to chat (I'm currently residing in UTC+8) and using [hangouts](https://hangouts.google.com) to talk through the details of the issue.

**Comment by pushchris** [comment]
@afh experiencing the same issue but when running in development mode. The exact error is the following: 
```
*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UICollectionViewCell 0x111eafc20> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key firstLabel.'
```

Using version 1.1.5 and the following to present:
```
let config = PLKConfiguration(key: plaidKey, env: .development, product: .transactions)
        let linkViewController = PLKPlaidLinkViewController(configuration: config, delegate: self)
        if (UI_USER_INTERFACE_IDIOM() == .pad) {
            linkViewController.modalPresentationStyle = .formSheet
        }
        present(linkViewController, animated: true)
```

We found the issue to be linked to a bank that we had being presented by default. Removing that bank from the list to be displayed in the modal resolved the issue. In our case it was First National Bank of Omaha when using the transactions product.

**Comment by afh** [comment]
Hi @pushchris thank you for raising this.

While the effect, i.e. crash is the same the cause is a different one. Looking at the stacktrace this issues is about inserting `nil` into an `NSArray`. The issue that you unfortunately experience is related to de-serializing an Interface Builder file.

Mind opening another issue with more detailed steps on how to reproduce the issue? I'd like to track it separately.

**Comment by pushchris** [comment]
My mistake, @afh, have switched to a new issue

**Comment by afh** [comment]
Not to worry, @pushchris. Thank you for opening #235, let's continue the conversation over there.

**Comment by afh** [comment]
Hello @yinonar LinkKit version [1.1.6](https://github.com/plaid/link/releases/tag/ios%2F1.1.6) addressing this issue has been released.
Please update your application to use this latest version and verify that the issue is resolved.
