### ISSUE TITLE
Utilizing certain items as defaults causes crash in transactions product

### ISSUE THREAD

**Issue by pushchris** [plaid/link#235]
| Name              | Value              |
| ----------------- | ------------------ |
| Link `env`        | development |
| LinkKit version   | 1.1.5  |
| iOS version       | 11.2.5 |
| iOS device        | iPhone X  |

### Steps to reproduce the issue

* Start a fresh Swift project and install LinkKit 1.1.5
* Utilize the following code to present the default bank selection modal:
```
let config = PLKConfiguration(key: plaidKey, env: .development, product: .transactions)
let linkViewController = PLKPlaidLinkViewController(configuration: config, delegate: self)
if (UI_USER_INTERFACE_IDIOM() == .pad) {
    linkViewController.modalPresentationStyle = .formSheet
}
present(linkViewController, animated: true)
```
* Switch to a web browser and navigate to the web configuration and add First National Bank of Omaha to the list of defaults
* Return to Xcode and re-run the project, re-open the Plaid picker.
* This time it crashes while trying to load the different banks

### What you expected to see?

Expected to be able to chose an account

### What you saw instead?

The entire app crashed with the following error: 

```
*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UICollectionViewCell 0x111eafc20> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key firstLabel.'
```

From what I can tell it appears that if you include certain items in the defaults it will crash.

**Comment by afh** [comment]
Thank you @pushchris for opening this issue, I can reproduce the crash and look into the underlying cause.

**Comment by afh** [comment]
@pushcris The underlying cause for the issue is found, a fix is being reviewed and will be available with the next release of LinkKit.

**Comment by pushchris** [comment]
@afh that's great! Thank you for your rapid response and work.

**Comment by afh** [comment]
Hello @pushchris LinkKit version [1.1.6](https://github.com/plaid/link/releases/tag/ios%2F1.1.6) addressing this issue has been released.
Please update your application to use this latest version and verify that the issue is resolved.
