### ISSUE TITLE
Missing "Don't see your bank?" button with no search results on iOS

### ISSUE THREAD

**Issue by GriffinSchneider** [plaid/link#236]
|       Name       | Value |
|------------------|-------|
| Link `env`       |   any    |
| Browser          |    WKWebView or UIWebView   |
| Operating system |   iOS 11, not tested on other versions    |

### A detailed description of the steps to reproduce the issue

* Run the iOS WKWebView example in this repo
* Type some nonsense in the search bar until there are no results

### What you expected to see?

The "Don't see your bank?" button, since the user does not see their bank

### What you saw instead?

A blank screen

### A screenshot that shows the state of the UI (if applicable)
![missing_button](https://user-images.githubusercontent.com/999346/36611607-73ac0c4a-18aa-11e8-9ec2-46f5650aec68.gif)

**Comment by pbernasconi** [comment]
@GriffinSchneider thanks for raising this - confirmed that I'm seeing the same. Please expect a fix to come out in the next Link web release.

I'll update this thread when it's been fully deployed!

**Comment by pbernasconi** [comment]
@GriffinSchneider - we've addressed the issue and will be going out to production in the next Link release.

Thanks for your patience!
