### ISSUE TITLE
link-initialize.js silently fails on iOS hybrid (Cordova) app

### ISSUE THREAD

**Issue by andreipopovici** [plaid/link#237]
This may be a bit hard to reproduce, but I'd like to at least get a hint about how to continue troubleshooting.

## Setup details:
- Cordova hybrid app (standard WebView)
- iOS 11.2 running in simulator, with Safari Developer Tools connected
- custom Plaid Link web integration, identical code running for existing Vue.js webapp and hybrid Cordova app
- `sandbox` env

## Steps to reproduce:
- load `https://cdn.plaid.com/link/v2/stable/link-initialize.js` using async script loader
- create link handler with an `onLoad` function
- call `open()` on link handler either directly or from a click event handler

## Expected result:

`onLoad` function should get called. Plaid Link widget should open. (At the very least, an error should be thrown.)

This correctly occurs in the following situations:
- with the same code deployed as a webapp, in mobile Safari, in the same iOS simulator
- with the same code, as a hybrid mobile app compiled for Android, running in a simulator or actual device
- any other situation except in the hybrid app running on iOS

## Actual result:

The `onLoad()` handler never gets called. Calling `open()` on the link handler does nothing. No errors get thrown.

## Reproducing the issue:

With the hybrid app loaded in the iOS simulator, I connected using the desktop Safari Developer Tools and ran the following:

![screen shot 2018-03-15 at 6 56 46 pm](https://user-images.githubusercontent.com/1143417/37479544-91bf3f3c-2885-11e8-9c33-89222492fcb1.png)

The result was the same as above: no error, no `onLoad` called, no widget.

In the Network tab, there are no additional requests to the Plaid CDN after `link-initialize.js`, whereas in the other successful situations, it correctly fetches `link.js` and other resources. This leads me to believe that `link-initialize.js` never runs, or never throws an error and silently fails.

## Help!
Can you please suggest anything else I can do to figure out why `link-initialize.js` silently fails in iOS WebViews only?

**Comment by pbernasconi** [comment]
Hi @andreipopovici – please excuse the late response here. It seems you're running into an issue where Link is likely opening into a new tab in your iOS WebView, which is a fallback when link-initialize determines that it cannot operate well inside of the parent window on mobile (eg: in an iFrame).

I believe the `forceIframe: true` flag will fix this for your integration on iOS. It's currently an undocumented configuration flag in Link for Web, and we plan on improving the developer experience around integrating Link in a Webview in the near future so stay tuned for an update there. By adding this flag to your `Plaid.create` object, it will force Link to always open in the same window and hopefully fix your integration.

Please let us know if this doesn't work and we can help you dive deeper. Thanks!

**Comment by andreipopovici** [comment]
Hi @pbernasconi, thank you for looking into this.

Unfortunately, adding `forceIframe: true` did not have any effect:

![screen shot 2018-03-20 at 9 18 33 pm](https://user-images.githubusercontent.com/1143417/37677715-7f9a7698-2c84-11e8-8f12-7b9b2195cac7.png)

**Comment by pbernasconi** [comment]
Hmm that's strange @andreipopovici – we need to see more of your integration to be able to help you debug.

A few other thoughts:
- do you have a meta-viewport tag for your mobile experience
```html
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
```
- are you blocking inline-styles in your CSP headers?

Otherwise can you send us your public_key + some sample code to paolo@plaid.com and we can help you out more?

**Comment by andreipopovici** [comment]
We do have the meta-viewport tag, and we're not blocking inline-styles via CSP headers.

In either case, wouldn't that also prevent `link-initialize.js` from working on Android, with the same code base?

I'll send more details via email. Thank you for helping us out!

**Comment by andreipopovici** [comment]
I was able to reproduce the issue in an empty Quasar Framework app wrapped with Cordova. I've created a repo, with steps to reproduce:

https://github.com/andreipopovici/plaid-link-ios-hybrid-bug

**Comment by andreipopovici** [comment]
It seems that a recent change in Cordova's whitelist plugin has broken backward compatibility. Following @pbernasconi's suggestions, I was able to fix this by adding `<allow-navigation href="*" />` at the top level of `<widget>`.

This could probably be refined to only allow Plaid's CDN URLs, but it solved the issue and now Plaid Link loads as intended on iOS.

Thank you @pbernasconi!
