### ISSUE TITLE
Prepare for Distribution & Crashlytics

### ISSUE THREAD

**Issue by Albarahakami** [plaid/link#238]
Hello,

We are running into an issue with the Run Script. After adding the run script exactly as suggested on the installation guid, we aren't able to install the app through Crashlytics.

We are using CocoaPods and here's the run script we are using:

`LINK_ROOT=${PODS_ROOT:+$PODS_ROOT/Plaid/ios}
cp "${LINK_ROOT:-$PROJECT_DIR}"/LinkKit.framework/prepare_for_distribution.sh "${CODESIGNING_FOLDER_PATH}"/Frameworks/LinkKit.framework/prepare_for_distribution.sh
"${CODESIGNING_FOLDER_PATH}"/Frameworks/LinkKit.framework/prepare_for_distribution.sh`

Please note that submitting to the App Store isn't generating any issues for us. We haven't tried submitting to Apple yet.

**Comment by afh** [comment]
Hi @Albarahakami, thanks for reaching out. Can you be more specific when you say you "aren't able to install the app through Crashlytics." Is there any error message or additional information that is being displayed or can be found in the (system, Crashlytics) logs?

**Comment by Albarahakami** [comment]
Thanks for your prompt response @afh. It just simply says "Unable to download". Crashlytics doesn't provide any logs I don't think. Deploying the app directly from XCode works fine.

I will look if there are any logs on the device itself now.

**Comment by Albarahakami** [comment]
Couldn't locate any logs from the device using XCode.
Remove the run script and deploying again using Crashlytics installs the app just fine.

**Comment by afh** [comment]
I'd also search in macOS' logs in `~/Library/Lobs` and using Console.app to find any Crashlytics related log messages.

You could try *not* running the `prepare_for_distribution` script and test whether Crashlytics strips used/embedded framework binaries to remove unneeded architectures. From our experience submitting an application that embeds a framework that contains non arm symbols does not pass App Store validation.

If you run `lipo -info` on the unstripped LinkKit.framework you see that it includes symbols `x86_64` and `i386` used by the iOS Simulator:
```
% lipo -info LinkKit.framework/LinkKit
Architectures in the fat file: LinkKit.framework/LinkKit are: i386 x86_64 armv7 arm64 
```

Running the same command on a stripped framework should show only `arm*` architectures.

**Comment by Albarahakami** [comment]
Looked at `~/Library/Logs` and nothing relatable. Installing the app after downloading it is what gives the error.

I plugged in the device and logged the console and noticed something there, I am getting these lines that I think are the cause of the issue:

`Mar 27 11:12:48 Albara installd(MobileSystemServices)[3504] <Notice>: 0x16ee9f000 +[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:]: 147: Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.IoDAUO/extracted/Payload/Roger.app/Frameworks/LinkKit.framework : 0xe8008017 (A signed resource has been added, modified, or deleted.)`

`Mar 27 11:12:49 Albara installd(MobileSystemServices)[3504] <Notice>: 0x16efb7000 -[MIClientConnection updatePlaceholderMetadataForApp:installType:failureReason:underlyingError:failureSource:completion:]: Update placeholder metadata requested by client installcoordinationd (pid 1516) for app com.roger.Roger installType = 1 failureReason = 2 underlyingError = Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.IoDAUO/extracted/Payload/Roger.app/Frameworks/LinkKit.framework : 0xe8008017 (A signed resource has been added, modified, or deleted.)" UserInfo={NSLocalizedDescription=Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.IoDAUO/extracted/Payload/Roger.app/Frameworks/LinkKit.framework : 0xe8008017 (A signed resource has been added, modified, or deleted.), LegacyErrorString=ApplicationVerificationFailed, SourceFileLine=147, LibMISErrorNumber=-402620393, FunctionName=+[MICodeSigningVerifier _validateSign<\M-b\M^@\M-&>`

`Mar 27 11:12:49 Albara installcoordinationd(MobileInstallation)[1516] <Notice>: com.roger.Roger:5:11:1:1:Updating PlaceholderMetadata for com.roger.Roger with failure 2 <LSInstallType 1, underlyingError (Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.IoDAUO/extracted/Payload/Roger.app/Frameworks/LinkKit.framework : 0xe8008017 (A signed resource has been added, modified, or deleted.)" UserInfo={LibMISErrorNumber=-402620393, LegacyErrorString=ApplicationVerificationFailed, SourceFileLine=147, FunctionName=+[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:], NSLocalizedDescription=Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.IoDAUO/extracted/Payload/Roger.app/Frameworks/LinkKit.framework : 0xe8008017 (A signed resource has been added, modified, or deleted.)}), source 17>`

`Mar 27 11:12:49 Albara appstored[181] <Notice>: [LaunchServicesObserver]: Coordinator canceled for com.roger.Roger`

`Mar 27 11:12:49 Albara appstored[181] <Error>: [CoordinatorStore]: <IXInitiatingAppInstallCoordinator<0x15bf1f1b0> identifier:com.roger.Roger creator:App Store state:IXAppCoordinationStateErrorOccurred> was canceled with reason: Error Domain=IXUserPresentableErrorDomain Code=2 "This app was unable to be installed." UserInfo={NSLocalizedDescription=This app was unable to be installed., NSUnderlyingError=0x15b9cddb0 {Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.IoDAUO/extracted/Payload/Roger.app/Frameworks/LinkKit.framework : 0xe8008017 (A signed resource has been added, modified, or deleted.)" UserInfo={NSLocalizedDescription=Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.IoDAUO/extracted/Payload/Roger.app/Frameworks/LinkKit.framework : 0xe8008017 (A signed resource has been added, modified, or deleted.), LegacyErrorString=ApplicationVerificationFailed, SourceFileLine=147, LibMISErrorNumber=-`


I hope these are helpful in pinpointing the issue.

**Comment by afh** [comment]
Hi @Albarahakami,

can you explain in more detail how you use Crashlytics? A screencast demonstrating that would be good, or even more better: a demo project including a detailed description how to reproduce the issue. Is that something you could provide?

* I took the liberty of editing your previous comment for legibility and changed the use of inline code to a single code block.

**Comment by Albarahakami** [comment]
Hi @afh 

It doesn't seem like crashlytics is doing anything other than uploading\distributing it, I have never ran into any issues with them and removing the run script makes the build downloadable. I'm thinking maybe I missed a step somewhere or my run script needs some editing.
Crashlytics use a run script themselves and can be found [here](https://fabric.io/kits/ios/crashlytics/manual-install?step=1)

The way Crashlytics work is that you archive the project, then once archived you upload it. Shown in the screencast [here](https://www.dropbox.com/s/67b45auk2t23c4y/crashlytics.mov?dl=0)

I'm tempted to install Link manually and see what happens but I really need to use CocoaPods with this one.


Thanks for your continuous help in this.

**Comment by emersonhum** [comment]
Hi @afh, we're also having the same issue. There's no problem when submitting to and distributing from the App Store. If it helps, the issue started around middle of October 2017.

**Comment by afh** [comment]
@Albarahakami thanks for providing the additional information.

The Crashlytics run script you pointed to is just a wrapper around `uploadDSYM`, which is a binary executable; so not sure what it does without further investigation.

If removing the `prepare_for_distribution` scripts makes your application downloadable via Crashlytics then I would go with that.

The one thing I would verify is what architectures are contained in the LinkKit.framework that is embedded in your application's archive. Yet it could be that Crashlytics strips the architectures during upload.

* Archive your application
* `open ~/Library/Developer/Xcode/Archives/$(date +'%Y-%m-%d')`
* `Show Package Contents` of the application's `.xcarchive`
* Find your application in `Products/Applications`
* `Show Package Contents` of the application`.app`
* Find `LinkKit.framework` in `Frameworks`
* Run `lipo -info on LinkKit.framework/LinkKit` it should show only `arm*` related architectures:
```
Architectures in the fat file: LinkKit.framework/LinkKit are: armv7 arm64 
```

<details><summary>Screenshots</summary>

<img width="50%" src="https://user-images.githubusercontent.com/16507/37991806-fc6301e2-31be-11e8-920c-9fd2561b7ffa.png">
<img width="50%" src="https://user-images.githubusercontent.com/16507/37991821-0bf4c528-31bf-11e8-9ad5-6b4d14d10832.png">
<img width="50%" src="https://user-images.githubusercontent.com/16507/37991835-14619420-31bf-11e8-8530-c0dd0e49d716.png">

</details>

**Comment by afh** [comment]
Thank you for chiming in, @emersonhum. Just to be sure: You are also using Crashlytics and the install fails for you during download?

**Comment by Albarahakami** [comment]
@afh Thank you.

It would be a hassle to have to remember to remove and add it every time we push a build to Crashlytics vs Apple. We push builds in Crashlytics almost daily.

I just ran `lipo -info LinkKit.framework/LinkKit` in the archived build from today and got whats expected: `Architectures in the fat file: LinkKit.framework/LinkKit are: armv7 arm64`

**Comment by afh** [comment]
@Albarahakami Apologies for not stating clearer what I meant earlier, allow me to rephrase:

If I understood you correctly

- you removed the `prepare_for_distribution` run script phase
- archived your application
- were able to upload, then download and install the application successfully using Crashlytics
- and verified that the LinkKit.framework embedded in your application's `.xcarchive` contained only `arm*` architectures

In this case I suggest you remove the `prepare_for_distribution` run script completely since it seems that Crashlytics handles stripping embedded binaries for you.

**Comment by emersonhum** [comment]
Yeah, we're using Crashlytics to distribute beta versions of our production app to our testers, just like how Albara does in his video and we get the same console logs. Also verified the `.xarchive` only contained `arm*` architectures while the unarchived repo has `i386 x86_64 armv7 arm64`.

I'll probably remove the `prepare_for_distribution` as you suggest. Thanks!

**Comment by Albarahakami** [comment]
No worries @afh I shoulda made my message more clear too.

This is where the issue arises, I did verify that after removing the `prepare_for_distribution` that the LinkKit.framework embedded in my application's `.xcarchive` contained only `arm*` architectures. But then doing so prevents me from submitting to Apple. Here's a screenshot of the error I get upon submission:
![image](https://user-images.githubusercontent.com/5579487/37993829-9f450914-31c4-11e8-8e9c-0ff9fdd29146.png)

So it's a catch 22 kinda thing, adding the `prepare_for_distribution` script makes the submission to Apple possible but throws an error in crashlytics. Removing the scripts does the opposite.

Hope this makes it a bit more clear.

Thank you for your prompt responses.
And thanks @emersonhum for pitching in on this one too.

**Comment by afh** [comment]
@Albarahakami I see. Mind sharing a screenshot of your build phases (feel free to send it to me directly via ahildebrandt@plaid.com). It seems that the `prepare_for_distribution` script runs after the application's resources have been signed, since the script modifies the dylib it invalidates previously generated signatures.

**Comment by Albarahakami** [comment]
@afh I just did. Thanks.

**Comment by emersonhum** [comment]
Thanks for catching @Albarahakami. I get the same App Store error when trying to validate the archive with the the `prepare_for_distribution` run script removed and successful validation when it is included.

**Comment by afh** [comment]
The best workaround I have at the moment is to replace the `Prepare for Distribution` build phase script with

```
LINK_ROOT=${PODS_ROOT:+$PODS_ROOT/Plaid/ios}
rm -f "${LINK_ROOT:-$PROJECT_DIR}"/LinkKit.framework/prepare_for_distribution.sh "${CODESIGNING_FOLDER_PATH}"/Frameworks/LinkKit.framework/prepare_for_distribution.sh
```

which will only remove the `prepare_for_distribution.sh` avoiding the resource not properly signed issue mentioned above.
