### ISSUE TITLE
Please include account info in `onSuccess` callback when "Select Account" feature is disabled

### ISSUE THREAD

**Issue by felixc** [plaid/link#239]
Plaid Link has the option of enabling or disabling the "Select Account" screen after the user has successfully authenticated. If enabled, the user can select one or more accounts, and the details of those selected accounts are returned in the `onSuccess` callback.

If, however, the "Select Account" screen is *not* enabled, no account information is returned. However, watching the network requests made by Link show that the details of all accounts are in fact still returned from the Plaid API and are available to the Link widget.

**This issue is to request as a feature** that if the "Select Account" screen is not enabled, information for *all* accounts is returned in `onSuccess`. In other words, `onSuccess` would *always* return account information, and the "Select Account" feature would *filter down* the returned values.

Our use-case for this is that we have switched off the "Select Account" screen because we have built a custom screen that is roughly equivalent, except we do some filtering of which accounts are shown and make the UI/UX fit our application. To make this work, we get the public token from `onSuccess`, and immediately make API calls to get the exact same information that was already available in the user's browser (but only inside Plaid Link). If Link surfaced these account details, embedders who follow this pattern could cut down on latency and API calls, providing a better experience for users.

Thanks as always for your consideration!

**Comment by GREENTEAMHQ** [comment]
https://github.com/plaid/link/issues/239#issue-312018002

**Comment by felixc** [comment]
Hello!

Just following up on this 'cause I heard the news that some of this info is now in fact available in this way via the `onSuccess` callback, which is great!

Looking at it now, it appears that the callback returns a list of account objects, each of which contains the following fields:
- id
- mask
- name
- subtype
- type

However looking at the network response, it seems like a few additional fields are also available; namely:
- official_name
- current_balance
- available_balance
- currency

Any chance those could be exposed in the same way too? :) Thank you!

**Comment by hairarrow** [comment]
Any updates on this?

I'm trying to find the account that a user selects, but I'm getting all of the accounts for a given institution instead.

**Comment by pbernasconi** [comment]
@felixc – accounts data is now consistently returned in the `onSuccess` callback for both Link Web + iOS. We don't have any short term roadmap plans to expose additional data, but I'll update this thread if that changes.

@hairarrow – You can turn on single or multiple account selection via the [Plaid Dashboard – Customize](https://dashboard.plaid.com/link/account-select) feature. `onSuccess` will accordingly return a filtered list of accounts that a user selects via Link in the `accounts` array.

<img width="905" alt="screen shot 2019-02-03 at 8 15 30 pm" src="https://user-images.githubusercontent.com/1716394/52189941-8e077b00-27f0-11e9-8cae-a18dabfa4622.png">
