### ISSUE TITLE
iOS Link has toolbar located overlapping input box

### ISSUE THREAD

**Issue by pushchris** [plaid/link#241]
| Name              | Value              |
| ----------------- | ------------------ |
| Link `apiVersion` | 2 |
| Link `env`        | production |
| LinkKit version   | 1.1.7 |
| iOS version       | 11.3 |
| iOS device        | iPhone 8 |

### A detailed description of the steps to reproduce the issue
Still working on getting exact steps to reproduce, but have gotten enough user reports of it to know it happens with frequency.

### What you expected to see?
Expected to have the submit button be placed right on top of the input fields

### What you saw instead?
The action toolbar was significantly 

### A screenshot that shows the state of the UI (if applicable)
![image-1-1](https://user-images.githubusercontent.com/679974/38573806-c36de9c0-3cbc-11e8-8c5b-3846acd40913.jpg)

**Comment by afh** [comment]
Thanks for reporting this @pushchris. What's the frequency of user reports you get?
I see what I can do to reproduce the issue and will review the code to find code paths that could be responsible for the issue.

**Comment by pushchris** [comment]
Very sporadic. So probably 1/25. One of our users sent in a screen recording of it as well as that screenshot. I've included the screenshot below:
![giphy](https://user-images.githubusercontent.com/679974/38576587-25074f08-3cc4-11e8-9353-7199edc7acbd.gif)
Will try to find better steps to reproduce.

**Comment by afh** [comment]
Thanks @pushchris that's helpful.

I notice that the distance from the input accessory view to the keyboard is the same height as the keyboard itself; I'll review the code that does the frame conversion via [`convertRect:fromView:`](https://developer.apple.com/documentation/uikit/uiview/1622498-convertrect?language=objc).

**Comment by afh** [comment]
@pushchris In the video I notice that [intercom](https://www.intercom.com/) seems to be present in the app. Mind elaborating on how you've integrated with them? It could be that they are adding their UI in an "unusual" way (otherwise the UI wouldn't be visible) and that somehow affects the keyboard input accessory view.

**Comment by pushchris** [comment]
@afh so Intercom just has a method for showing/hiding their button. I would imagine they are placing their UI on a different window or something so that it is always above everything else. Once you call for it to be shown it stays shown on top of every view controller you go through

**Comment by afh** [comment]
FYI @pushchris, we have worked lined up for this quarter which will change the UI with regards to the `Submit` button removing the need for `inputAccessoryView`.

**Comment by pushchris** [comment]
@afh thanks for your work. We will continue to investigate, but seeing as the UI will be changing it might be for naught and we will look forward to the changes you guys continue to implement! Thanks again!
