### ISSUE TITLE
Get account balance or transactions in iOS?

### ISSUE THREAD

**Issue by cesaredecal** [plaid/link#244]
Hi, I understand how to authenticate users. I got the auth working using `LinkKit`. In order to retrieve the user's transactions or balance do I need to make REST API calls (using `URLSession`s/Alamofire). Does the `LinkKit` framework provide some sort of API wrapper we can use to retrieve transactions/balance/etc.?

Edit: I'm using the sandbox account (user_good/pass_good).

Thanks

**Comment by pbernasconi** [comment]
Hi @cesaredecal – great to hear that you've been able to integrate with Link to authenticate your users to Plaid.

After reading your comments, it seems you'd like to hit our `/transactions/get` and `/accounts/balance/get` API endpoints to obtain transaction and balance data for an Item. To do so, you'll need to setup your own server which ultimately calls Plaid's backend API, and passes in the `public_token` created by Link to your personal sever, and then call Plaid's API endpoints to get detailed user information. I would highly recommend checking out our [Quickstart documentation](https://plaid.com/docs/quickstart/) to get started with Plaid.

The general flow is:
- Open Link with a specific configuration (this includes your `public_key`, the initial `products` you'd like to use, and any other configuration that suits your application)
- Your user connects a new `Item` to Plaid via Link. Link returns a `public_token` in the success callback / handler
- Send an HTTP request to your own server from your iOS app, which passes the Link `public_token` in the body, and in your backend calls the Plaid `/item/public_token/exchange` endpoint, returning a persistent `access_token` that you need to save in your own DB
- Call any Plaid product endpoints in your backend server with your `client_id` and `secret` + given `access_token` to obtain `Item` data that you want to use. Please do note **that your `client_id` and `secret` are sensitive Plaid credentials, and should not be visible or used inside of your iOS application**

I hope this helps with your integration, and please do reach out to our Support team via the [Plaid Dashboard](https://dashboard-staging.plaid.com/support/) if you have any further questions or problems!

**Comment by cesaredecal** [comment]
Makes perfect sense. Thanks Paolo!
