### ISSUE TITLE
App Crash When Click on Exit Button on Plaid Button 

### ISSUE THREAD

**Issue by MAmir99** [plaid/link#247]
else if (action == "exit") {

                            plaidLinkWebview.loadUrl(linkInitializationUrl.toString());

//                            Intent i = new Intent (getContext(),HomeActivity.class);
//                            startActivity(i);

                            //fragmentClass = Fragment_plaid.class;
                            //loadFragment();

                        // User exited
                        // linkData may contain information about the user's status in the Link flow,
                        // the institution selected, information about any error encountered,
                        // and relevant API request IDs.
                        Log.d("User status in flow: ", linkData.get("status"));
                        // The requet ID keys may or may not exist depending on when the user exited
                        // the Link flow.
                        Log.d("Link request ID: ", linkData.get("link_request_id"));
                        Log.d("API request ID: ", linkData.get("plaid_api_request_id"));

                        // Reload Link in the Webview
                        // You will likely want to transition the view at this point.
                        //plaidLinkWebview.loadUrl(linkInitializationUrl.toString());
                    }

**Comment by MAmir99** [comment]
Actually, when Click on exit button on webview on prescribed bank panel, the application goes to crash.
Kindly help me how to resolve it

**Comment by Mikaaill** [comment]
How do i link my bank with the apps

**Comment by MAmir99** [comment]
Actually, the api is working fine in android. Which type of banks you are
offering in your aaps? Your target country...

**Comment by Mikaaill** [comment]
How do i link my personal bank though plaid link with other apps i do not own a business.

**Comment by Mikaaill** [comment]
How do i link my personal bank though plaid link with other apps i do not own a business.

**Comment by pbernasconi** [comment]
Hi @MAmir99 @Mikaaill – I would recommend opening a Support ticket via the [Plaid Dashboard](http://dashboard.plaid.com/support/new) for questions regarding product questions.
