### ISSUE TITLE
Available products list?

### ISSUE THREAD

**Issue by sarink** [plaid/link#249]
Is there a list of available `product`s that we pass to link? I apologize if it's in the docs somewhere but I can't seem to find it.

**Comment by pbernasconi** [comment]
hey @sarink - you should be able to find a list of products in the sidebar of our docs! https://plaid.com/docs/api/#products

For quick reference, you can use any combination of:
- `auth`
- `transactions`
- `identity`
- `income`
- `assets`

doing:

```js
Plaid.create({
  products: ['auth', 'identity'],
});

**Comment by sarink** [comment]
What about Balance?

**Comment by pbernasconi** [comment]
Balance is a product that you can call for an existing / newly created Item, but not a product you can initialize Link with. Instead initial Link with `transactions`, ..., and you can then call `/balance/get` when you want to get a live balance update for an Item.
