### ISSUE TITLE
Error: "multifactor authentication is not currently supported for this account"

### ISSUE THREAD

**Issue by sarink** [plaid/link#250]
*Please do not include your API `secret` or `public_key` in any issue.*
---
When submitting an issue for Link on the web or within a Webview, please include the following information:

|       Name       | Value |
|------------------|-------|
| Link `env`       |    Development   |
| Browser          |   Chrome    |
| Operating system |   OSX   |

### A detailed description of the steps to reproduce the issue

* Try to link a valid US Bank account
* The user has both SMS-2FA and ID Security Questions enabled on their US Bank profile
* It is worth noting that I have others users who have linked US Bank accounts successfully, I'm not entirely sure what is different about this one. The plaid docs state "We support MFA for all institutions" - so ever seeing this error _at all_ seems unexpected?

### What you expected to see?
* Link be successful

### What you saw instead?
 * Received the error message `multifactor authentication is not currently supported for this account`

### A screenshot that shows the state of the UI (if applicable)
![unnamed](https://user-images.githubusercontent.com/1881761/42054289-9222c3bc-7ad9-11e8-84fb-e2b3f6eb5fe0.jpg)

**Comment by cconeill** [comment]
Hi!

US Bank recently deployed a new MFA flow and our team is working to deploy support for this new authentication flow. In the meantime users with this new MFA flow will receive an MFA_NOT_SUPPORTED​ error when trying to link their account.

If you'd like to be notified when we rollout support for this new MFA flow please open a ticket in your [Plaid Dashboard](https://dashboard.plaid.com/support/new) and we'll reach out ASAP!

Best,
Christopher
Plaid Support

**Comment by cconeill** [comment]
The best way to find out about these sorts of issues and be notified when they're fixed is to open a ticket with us on Support in your [Plaid Dashboard](https://dashboard.plaid.com/support)!

**Comment by pbernasconi** [comment]
Hi @archcorsair – please open a [Support ticket via the Plaid Dashboard](https://dashboard.plaid.com/support/new) to get a faster and better answer for updates related to US Bank and other institution issues.

The Link team here at Plaid generally uses this GitHub repo to address Link specific bugs and feature requests, and our support team is very well equipped to help out on more general questions or bank-related issues.
