### ISSUE TITLE
Animation issue on pushing to bank Login screen

### ISSUE THREAD

**Issue by ioskunal** [plaid/link#253]
When submitting an issue for [**Plaid Link iOS**](https://github.com/plaid/link/tree/master/ios)
please include the following information:

| Name              | Value              |
| ----------------- | ------------------ |
| Link `apiVersion` |                    |
| Link `env`|              development |
| LinkKit version   |        1.1.9            |
| iOS version       |        iOS 11.3, iOS 11.4            |
| iOS device        |        iPhone X , iPhone 6s            |

### A detailed description of the steps to reproduce the issue

* Come to the all bank screen of the Plaid
* Search for any bank with the help of UISearchBar
* Click on any bank

### What you expected to see? 
Selecting a bank should take you to the bank login screen smoothly.

### What you saw instead?
The animation jerks a little bit and then takes you to the login screen. The Jerk should not come in the navigation.

### A screenshot that shows the state of the UI (if applicable)

[Animation Jerk.zip](https://github.com/plaid/link/files/2209069/Animation.Jerk.zip)

**Comment by afh** [comment]
Thanks for reporting @ioskunal. Which version of LinkKit was used?

**Comment by afh** [comment]
Hi @ioskunal, unfortunately I have been unable to reproduce the issue. Can you provide some more information, e.g.:

- Which version of LinkKit was used
- A longer video that shows how the application starts, LinkKit is presented, the issue at hand, and LinkKit dismissed
- A code snippet that shows how you integrate LinkKit, i.e. configure and present `PLKPlaidLinkViewController`
- Which other third-party software is used, e.g. via CocoaPods or Carthage
- Anything else that may seem useful

Thanks!

**Comment by ioskunal** [comment]
Hi @afh 
Apologies for missing the earlier message. Here are the answer to your questions.
1. I am using Linkkit version 1.1.9.
2. Attaching video for the same.
3. Attaching code snippet.
4. I am using many third party applications using Cocoapods. Do you want the entire list? Does it depend on other third parties?


[Archive.zip](https://github.com/plaid/link/files/2230894/Archive.zip)

**Comment by afh** [comment]
Hello @ioskunal,
thank you for your response and making the effort to provide another video and the code snippet, that will be helpful.
While LinkKit itself does not depend on any third-party code, in the past we have seen third-party code messing with the view hierarchy, essentially influencing LinkKit. Therefore an entire list of used third-party code could be helpful.

**Comment by ioskunal** [comment]
Hey @afh 
Here is a list of libraries that I am using
```pod 'Alamofire', '4.5.0'
    pod 'SwiftGen', '3.0.0'
    pod 'Crashlytics'
    pod 'EZSwiftExtensions'
    pod 'ActionSheetPicker-3.0'
    pod 'IQKeyboardManagerSwift'
    pod 'SwiftEventBus', :tag => '2.1.2', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'
    pod 'EZAlertController'
    pod 'Apollo'
    pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
    pod 'SVPullToRefresh'
    pod 'RMMapper'
    pod 'SwiftMessages', '~> 4.0.0'
    pod 'ZendeskSDK'
    pod 'Shimmer'
    pod 'Plaid'
    pod 'PinCodeTextField'
    pod 'Intercom'
    pod 'Analytics', '~> 3.0'
    pod 'ACFloatingTextfield-Swift', '~> 1.7'
    pod 'GrowingTextView', '~> 0.5'
```

**Comment by afh** [comment]
Hi @ioskunal my hunch is that the `Intercom` Cocoapod is messing with the view hierarchy. Is it possible for you to disable the Intercom Cocoapod and try to reproduce the bug or even better provide a minimal Xcode project with which the issue is reliably reproducible?

**Comment by ioskunal** [comment]
Sure Alexis,
I will try it and let you know.

**Comment by ioskunal** [comment]
Hello @afh 
As you suggested i have tried removing the Intercom Cocoapod but still the animation does not improve. What would be the next steps?

**Comment by afh** [comment]
Hi @ioskunal,
as we continue to go to the root of this issue and try to find ways to reproduce it, here are some suggestions on what you could do:

* Upgrade to LinkKit 1.1.10 and see if the issue still appears
* Provide a minimal demo Xcode project with which the issue can be reproduced reliably

**Comment by afh** [comment]
Hi @ioskunal,

I noticed you closed this issue, I'm curious as to what the resolution is. Care to elaborate a bit?
