### ISSUE TITLE
[iOS] When updating an error'd account, Retry link is broken

### ISSUE THREAD

**Issue by idris** [plaid/link#256]
| Name              | Value              |
| ----------------- | ------------------ |
| Link `apiVersion` |  v2  |
| Link `env`        |   production                 |
| LinkKit version   |  1.10.0                  |
| iOS version       |    12                |
| iOS device        |   iPhone X                 |

### A detailed description of the steps to reproduce the issue

* Open Plaid Link in _update_ mode (that is, with an existing public token of an account in error state)
* (First problem: I don't think the intro "This app uses Plaid..." screen should appear.  That should probably only appear on a new account.  But I digress..)
* Enter an incorrect password, and click Submit.
* Press the "Retry Login" button

### What you expected to see?
"Retry Login" should take me back to the login screen.

### What you saw instead?
"Retry Login" takes me to the "Are you sure you want to exit?" screen.

### A screenshot that shows the state of the UI (if applicable)
![plaid-update-retry](https://user-images.githubusercontent.com/13989/43742698-d4bb4d58-9987-11e8-98af-fbe3bab3d976.gif)

**Comment by afh** [comment]
Hello @idris,
thank  you for reporting this.

A bugfix for this will be available with the upcoming release of LinkKit 1.1.11 planned for mid August.

**Comment by ravron** [comment]
Hi @idris, I'd like to let you know that [LinkKit version 1.1.11][1] was released and addresses this issue. Please give it a try. Thanks again for your thorough report!

[1]: https://github.com/plaid/link/releases/tag/ios%2F1.1.11
