### ISSUE TITLE
Unable to install Plaid 1.1.11

### ISSUE THREAD

**Issue by ajfigueroa** [plaid/link#258]
### A detailed description of the steps to reproduce the issue
* Update Podfile to include this line: `pod 'Plaid', '1.1.11'`
* Run `pod install`

**Cocoapods version: 1.4.0
Mac OS: 10.13.6**

### What you expected to see?

I expected to be able to successfully install `v1.1.11` since the [podspec](https://github.com/plaid/link/blob/master/Plaid.podspec) is updated.

### What you saw instead?

The following error even after running `pod repo update`: 
```
[!] CocoaPods could not find compatible versions for pod "Plaid":
  In Podfile:
    Plaid (= 1.1.11)

None of your spec sources contain a spec satisfying the dependency: `Plaid (= 1.1.11)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
error Command failed with exit code 31.
```

I noticed that https://cocoapods.org/pods/Plaid says the last release was in July. Is it possible that this update hasn't been pushed yet?

---

| Name            | Value |
|-----------------|-------|
| Link `env`      |    N/A   |
| LinkKit version |   N/A    |
| iOS version     |   N/A    |
| iOS device      |    N/A   |

**Comment by afh** [comment]
Thanks for using Plaid and thansk for reporting @ajfigueroa!

The issue should be fixed now. Please try again and verify that `pod update` does indeed install version 1.1.11 of the Plaid CocoaPod.

**Comment by ajfigueroa** [comment]
@afh Thank you, it works 😄

**Comment by afh** [comment]
Thanks for verifying, @ajfigueroa, and apologies for the inconvenience.
