### ISSUE TITLE
macOS swift 4 version

### ISSUE THREAD

**Issue by kienpham2000** [plaid/link#259]
Hi,

Awesome project, I really love Plaid! I'm new to iOS and macOS development. I'm trying to create a native macOS app, I only see the framework for iOS, would that work for macOS? If not do you plan to have a macOS swift version for Link? 

Thanks,
Kien

**Comment by ravron** [comment]
Hi Kien, thanks for reaching out! 

Unfortunately our iOS framework will not work in a macOS app, and we're not currently working on a version compatible with macOS. However, the web version of Link may be able to help. My recommendation would be to open the web version of Link in a webview and communicate with it via JavaScript. Take a look at [the documentation](https://plaid.com/docs/api/#integrating-with-link) and see if that will fit your use case!

We're always looking for feedback, and I've added the idea of a native macOS framework to our list of possible improvements. Thanks for using Plaid!

**Comment by kienpham2000** [comment]
thank you very much for your prompt reply. I'll look into webview. Thank you.
