### ISSUE TITLE
Link ReactNative NPM availability

### ISSUE THREAD

**Issue by barryelevatyr** [plaid/link#262]
Will the newly released ReactNative component me made available via NPM?

The [Readme ](https://github.com/plaid/link/tree/master/react-native/linkkit) for the linkkit mentions installation via NPM (npm install react-native-plaid-link --save), however the package name that it refers to (react-native-plaid-link) is not for the new Plaid RN component.

**Comment by afh** [comment]
Hi @barryelevatyr,

thanks for reaching out. The `react-native/linkkit/README.md` was published accidentally, apologies for that.

The example code is what we provide for now and we have not planned to release the code via NPM.

/cc @pbernasconi

**Comment by zachrnolan** [comment]
Yeah, this seems like a must-have for our team. Would you reconsider adding this to NPM?
