### ISSUE TITLE
Link for Link iOS Integration Docs Broken

### ISSUE THREAD

**Issue by SunnyIzr** [plaid/link#267]
### A detailed description of the steps to reproduce the issue

Where are the latest docs to integrate Link with iOS? The current link that's listed (plaid.com/docs/link/ios) is broken.

**Comment by GREENTEAMHQ** [comment]
[beeman_insurance_agents_statement_of_financial_health.pdf](https://github.com/plaid/link/files/2364001/beeman_insurance_agents_statement_of_financial_health.pdf)

**Comment by afh** [comment]
@SunnyIzr I checked again just to be sure and the docs are back online, if you still do not see them it may be a caching issue.
