### ISSUE TITLE
Include of non-modular header inside framework module 'LinkKit'

### ISSUE THREAD

**Issue by adamdahan** [plaid/link#268]
*Please do not include your API `secret` or `public_key` in any issue.*
---
### A detailed description of the steps to reproduce the issue

* Run the pod 'LinkKit' on Xcode 10
* 
* 

### What you expected to see?

That LinkKit builds.

### What you saw instead?

Include of non-modular header inside framework module 'LinkKit' for all headers

// LinkKit Public Headers
#import <LinkKit/PLKConstants.h>
#import <LinkKit/PLKConfiguration.h>
#import <LinkKit/PLKPlaidLink.h>
#import <LinkKit/PLKPlaidLinkViewController.h>

<details><summary>Screenshots that show the state of the UI (if applicable)</summary>

</details>

---

When submitting an issue for Link on the web or within a Webview, please include the following information:

|       Name       | Value |
|------------------|-------|
| Link `env`       |       |
| Browser          |       |
| Operating system |       |

---

When submitting an issue for [**Plaid Link iOS**](https://github.com/plaid/link/tree/master/ios) please include the following information:

| Name            | Value |
|-----------------|-------|
| Link `env`      |       |
| LinkKit version |       |
| iOS version     |       |
| iOS device      |       |

#### List of used 3rd party libraries (e.g. CocoaPods):

* [Plaid](https://cocoapods.org/pods/Plaid)
*
*

**Comment by afh** [comment]
Hi @adamdahan,

thanks for reaching out.

Since we have successfully tested LinkKit integration with Cocoapods and Xcode 10 can you please explain in more detail which actions you are taking and include any commands you are running as well as any errors you encounter.
Ideally we would like to receive a minimal sample project with which the error you are observing can be reproduced reliably?

**Comment by afh** [comment]
Hi @adamdahan,

are you still running into this issue or can it be closed?

**Comment by afh** [comment]
@adamdahan I'm closing this issue since I haven't heard back, feel free to re-open providing more information should you still run into this issue.
