### ISSUE TITLE
The bottom inset on the iPhone X is not taken into account in the design sometimes.

### ISSUE THREAD

**Issue by Sethmr** [plaid/link#269]
The bottom inset on the iPhone X is not taken into account in the design sometimes.
On one of the first couple of screens our team has noticed this a several times already in 1.1.11.

![simulator screen shot - iphone x - 2018-09-18 at 17 27 53](https://user-images.githubusercontent.com/10062416/45717504-32519380-bb68-11e8-9605-f5657d953ac6.png)

**Comment by afh** [comment]
Hello @Sethmr :wave:🙂 

thank you for reaching out and using LinkKit.

The behaviour you describe can only be observed on the Simulator where one can toggle the visibility of the keyboard (using ⌘ K) while a text field is the first responder or when using a hardware keyboard paired with the device, which we think is a very rare scenario.

On a device the input accessory view, containing the **Reset password** and **Submit** button, is hidden alongside the keyboard once the first responder is resigned (for example when using the app switcher) unless as stated above a paired hardware keyboard is used.

We also have work planned that will remove the input accessory view altogether resolving this rare issue in another way.

**Comment by Sethmr** [comment]
Thank you for your quick response. This is perfectly acceptable to me. I have been yelling at the people over at Dunkin Donuts to fix their UI for a while revolving around this (it's still hard to tap submit on their App), so it was a sore enough spot to bring it to your attention. Theirs is broken under all conditions though >.<
