### ISSUE TITLE
[Android Webview] Pre-select institution

### ISSUE THREAD

**Issue by yuanliu666** [plaid/link#274]
Is there any way to skip institution search page and open specific institution page given all institution info needed is already fetched?
I know that iOS has 
```
let viewController = PLKPlaidLinkViewController(institution: "ins_1", configuration: configuration, delegate: self)
```
but I am not sure if this can be achieved in android webview as well?

**Comment by michaelckelly** [comment]
@yuanliu666 - Link does not support jumping directly to a particular institution -- you must use the Institution Select view. The behavior you mentioned on iOS is deprecated and no longer supported.

**Comment by seonixx** [comment]
Has this behaviour been deprecated for Link web plugin as well?
