### ISSUE TITLE
Cannot submit to Appstore Connect.

### ISSUE THREAD

**Issue by adamdahan** [plaid/link#275]
*Please do not include your API `secret` or `public_key` in any issue.*
---
### A detailed description of the steps to reproduce the issue

Follow your instructions on your website for installing via cocoapods. It works well in development mode but when you try to upload your app store. It does not work. 

This is the message I received from Apple.
 
> Dear Developer,We identified one or more issues with a recent delivery for your app, "Bosslife". Please correct the following issues, then upload again.Invalid Signature - Code object is not signed at all. The file at path [Bosslife.app/Frameworks/LinkKit.framework/prepare_for_distribution.sh] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.htmlBest regards,The App Store Team

I looked a little more into this - and I saw your comments about 

> "Change the ${PROJECT_DIR}/LinkKit.framework path in the example below according to your setup, and be sure to quote the filepaths when they contain whitespace." 

so I did and it ended up being: 

```
LINK_ROOT=${PODS_ROOT:+$PODS_ROOT/Plaid/ios}
cp 
"${LINK_ROOT:-/Users/adamdahan/Github/bosslife/bosslife}"/LinkKit.framework/prepare_for_distribution.sh

"${CODESIGNING_FOLDER_PATH}"/Frameworks/LinkKit.framework/prepare_for_distribution.sh

"${CODESIGNING_FOLDER_PATH}"/Frameworks/LinkKit.framework/prepare_for_distribution.sh
```

Which is funny because you guys don't even include the prepare_for_distribution.sh file inside your framework when you ship with cocoapods. So how could that possibly work? 

I ended up dragging the file from your example project download into that directory and here is the error I get now.

```
/Users/adamdahan/Library/Developer/Xcode/DerivedData/Bosslife-cvdrhagqcktpyredobmrwokmpdvi/Build/Intermediates.noindex/Bosslife.build/Debug-iphoneos/Bosslife.build/Script-9A5C20502153CCB900D4DA63.sh: line 8: /Users/adamdahan/Library/Developer/Xcode/DerivedData/Bosslife-cvdrhagqcktpyredobmrwokmpdvi/Build/Products/Debug-iphoneos/Bosslife.app/Frameworks/LinkKit.framework/prepare_for_distribution.sh: No such file or directory
```

------------- I am lost at this point. 

### What you expected to see?

I am hoping to get some help so I can distribute my app to some users this weekend. 
---

When submitting an issue for [**Plaid Link iOS**](https://github.com/plaid/link/tree/master/ios) please include the following information:

| Name            | Value |
|-----------------|-------|
| Link `env`      |    Not sure how to check this.   |
| LinkKit version |  Plaid latest on Cocoapods    |
| iOS version     |   iOS 12    |
| iOS device      |   Simulator iPhone XR    |

#### List of used 3rd party libraries (e.g. CocoaPods):

* [Plaid](https://cocoapods.org/pods/Plaid)

Please help!

Thank you

**Comment by afh** [comment]
Hi @adamdahan 

thank you for using Plaid Link for iOS and for thanks reaching out. I'm sorry to hear that you are running into issues while integrating with Plaid Link. Let me try and straighten things out :)

Once `pod install` was run the `prepare_for_distribution.sh` script is available at `Pods/Plaid/ios/LinkKit.framework/prepare_for_distribution.sh` from within your Xcode project directory; the directory that also contains the `*.xcworkspace` and `*.xcproj` files.

Since you are using Cocoapods to integrate Plaid Link for iOS there is no need to make changes to the custom build phase **Run Script**.

I suspect that the order of the **Build Phase**s is not as it needs to be, i.e. have you made "sure to run this build phase after the […] [CP] Embed Pods Frameworks build phase"
as the [documentation](https://plaid.com/docs/link/ios/#add-run-script) suggests?

<img width="50%" alt="linkios-275a" src="https://user-images.githubusercontent.com/16507/45821948-b2076b80-bcea-11e8-8f63-aba6e4569c97.png">

**Comment by adamdahan** [comment]
Hey @afh Thank you for the speedy reply!

I did double check that the order was correct take a peak: 

![screen shot 2018-09-20 at 9 55 24 am](https://user-images.githubusercontent.com/1205894/45823322-6ee1d400-bcbb-11e8-9d1c-88af1776af41.png)

From my experience the script did need to be changed to this guys comment on #issue 216 Sethmr commented on Oct 30, 2017.

cp "${PROJECT_DIR}"/Pods/Plaid/ios/LinkKit.framework/prepare_for_distribution.sh "${CODESIGNING_FOLDER_PATH}"/Frameworks/LinkKit.framework/prepare_for_distribution.sh
"${CODESIGNING_FOLDER_PATH}"/Frameworks/LinkKit.framework/prepare_for_distribution.sh

I still had to copy the file into the framework myself. As no prepare_for_distribution was created a pod install. 

However, on a good note **** so far *** the app is "Processing" and it's been about 20 minutes with no error trigger on apples end. So this is good news. 

I will comment back in 20 minutes if the full upload processed or not!

Hang tight 👍

**Comment by adamdahan** [comment]
Okay so after using the script that was provided by #issue 216 Sethmr commented on Oct 30, 2017.

The application upload does work correctly! YAY!

However, now this error occurs and effectively makes it that you can only run your project on a real device and not the simulator. 

![screen shot 2018-09-20 at 12 11 41 pm](https://user-images.githubusercontent.com/1205894/45834427-17506200-bcd5-11e8-9d1b-b8c12d0c0c35.png)

I will have to run on device until I can debug whats going on in that photo. But I do think you guys need to update your information on your website - it doesn't work the way it is explained. 

If you guys have any idea whats going on in the photo in this message please shed some light!

Thank you - I love Plaid!

**Comment by afh** [comment]
Hi @adamdahan,

the script removes all architectures from the LinkKit dylib that must not be submitted to the App Store, i.e. `i386` and `x86_64` for the Simulator.

I assume you may have run the script on the LinkKit.framework that resides in the Pods and therefore have removed the symbols required for running on the Simulator.

To find out which architectures are contained in the LinkKit dylib used for linking do:
```
% lipo -info Pods/Plaid/ios/LinkKit.framework/LinkKit 
Architectures in the fat file: Pods/Plaid/ios/LinkKit.framework/LinkKit are: i386 x86_64 armv7 arm64
```

If `i386` or `x86_64` or both are missing I recommend you delete the cached Plaid Cocoapod and re-install it:
```
% rm -rf Pods/Plaid
% pod install
```

**Comment by adamdahan** [comment]
Hi @afh, 

I cannot thank you enough. It worked perfectly.. Both compiling for simulator > device and archiving for app store distribution. 

You are the f'n man!!!!!! 🤗

:shipit:

**Comment by afh** [comment]
Hi @adamdahan,

I'm glad to hear that I was able to help :pray:
Wishing you much success with launching your app! :smiley::tada:

**Comment by adamdahan** [comment]
@afh Thank you!
