### ISSUE TITLE
Add a ruby sample response handler to examples?

### ISSUE THREAD

**Issue by SupremeA** [plaid/link#28]
I have been working with plaid link and while I have it working I would like to see an example of a ruby response handler. Any chance you could add a sample ruby server-side handler to the documentation example instead of just node?

**Comment by michaelckelly** [comment]
@SupremeA:

We'll work on adding a Rails handler!  We're working to integrate the [`/exchange_token`](https://github.com/plaid/link/blob/master/README.md#exchange_token-endpoint) endpoint into [plaid-ruby](https://github.com/plaid/plaid-ruby) as well (see https://github.com/plaid/plaid-ruby/issues/53)

**Comment by SupremeA** [comment]
That's great! This is one of the last pieces to my app puzzle. Any idea of
an ETA? I was aware about the exchange_token so that is good too.

 

Art

**Comment by michaelckelly** [comment]
@SupremeA 

I don't have a firm date for you, but hopefully within the next week or two!

In the meantime, you can use the `/exchange_token` endpoint using vanilla HTTP requests. A sample cURL request:

```console
curl -X POST https://tartan.plaid.com/exchange_token \
-d client_id=test_id \
-d secret=test_secret \
-d public_token=test,chase,connected
```

The response from the API will be JSON-parseable and will either be an error (in the case of an invalid `public_token` or `client_id`/`secret` pair) or a response similar to:

```json
{"access_token": "foo_bar_plaid_access_token"}
```

I know it's not nearly as ideal or convenient as using a native client library, but you should be able to do something similar with a ruby http request library.

**Comment by SupremeA** [comment]
Cool thats not too long. Thanks!

**Comment by michaelckelly** [comment]
@SupremeA:

The /exchange_token endpoint is in the latest release of [plaid-ruby](https://github.com/plaid/plaid-ruby). Check out the [example](https://github.com/plaid/plaid-ruby#exchanging-a-link-public_token-for-a-plaid-access_token), too.

**Comment by SupremeA** [comment]
Thanks for the update. I saw it 1 hour after you put it up. I was watching. 

Question in the example, does the exchangeTokenResponse and the stuff after that go into the initializer file or are those for use in other parts of your app?

**Comment by michaelckelly** [comment]
Reopening this issue as we have not yet posted the Ruby app sample - that should be up in the [/examples](https://github.com/plaid/link/tree/master/examples) directory in the next few days!

**Comment by michaelckelly** [comment]
@SupremeA:

The ruby [sample app](https://github.com/plaid/link/tree/master/examples/ruby) has been added!

**Comment by SupremeA** [comment]
Thanks!
