### ISSUE TITLE
Banking credentials, Security, Consumer Confidence, Unlimited Account Access

### ISSUE THREAD

**Issue by bdowling** [plaid/link#282]
### What you expected to see?

* Trust the information is going to the right parties.
* Security of the communications
* Integrity of the parties
* Confidence and Clarity in how these credentials will be used.

While I can understand your constraints with working with banks, the authentication/ACH mechanism as a consumer of your product leaves a lot to be desired.  As mentioned in #68 -- the user has no visible trust mechanisms to ensure that they are in fact communicating with plaid securely and in turn what plaid is doing with those credentials.  Cloning a banks image/login form look does not bode confidence or trust in the transaction.   In the implementation I have seen, the vendor's site is presenting iframes that link to plaid's registration forms.  So the user's browser makes it appear they are sending the credentials to the vendor.  Using iframes in a security transaction is bad practice.

Credentials to a online bank account would obviously imply unlimited constraints in what could occur with those credentials on the customer's banking site.  There is no limited access granted, no expiration/time constraints.  Customers are simply giving up their credentials for you to access their bank site.  

From a consumer standpoint, all I want to permit is ACH transfers, not grant you the ability to see/access my account(s), transaction history, bill payment information or any other data that they contain.  In this regard, the micro-payment method as was utilized by Robinhood is preferable.  Granted it's a slow and error prone process, but it meets the goals of least access security constraints.  From the consumer standpoint, any account I setup with ACH access is always a zero-balance account, funds only exist when an ACH is in process.  This leaves the control in the consumers hands as it should be.

There is no confidence or clarity in what will happen after "account linking" takes place.  Can the consumer change their credentials?  Are you storing API keys for future activities?  Are you simply collecting account information to enable the ACH transfers to take place?  The consumer has absolutely no idea.

**Comment by ravron** [comment]
Hey @bdowling, thanks for reaching out with your concerns. You may find answers to some of your questions on our [security page](https://plaid.com/security/) or in our [privacy policy](https://plaid.com/legal/#end-user-privacy-policy). If you still have questions or concerns, contact us at [privacy@plaid.com](mailto:privacy@plaid.com).

**Comment by NSExceptional** [comment]
@ravron Your links fail to answer any questions asked here. That seems like a canned response.
