### ISSUE TITLE
PLKConfiguration `webhook` property throws EXC_BAD_INSTRUCTION on read

### ISSUE THREAD

**Issue by ajfigueroa** [plaid/link#284]
### A detailed description of the steps to reproduce the issue
* Create a new Xcode project
* Setup this project as a dependency via Cocoapods
```
pod 'Plaid', '1.1.13'
```
* Install project and then add a test or some usage that involves building a PLKConfiguration and attempting to access the `webhook` property
* Observe that the property is unable to be read due to an `EXC_BAD_INSTRUCTION` exception

Alternatively, I've setup a project that helps reproduce this: https://github.com/ajfigueroa/PlaidBadAccessDemoProject

### What you expected to see?

- No exception thrown when attempting to access the `webhook` property

### What you saw instead?

- I saw `EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)` as per the screenshots below:

<details><summary>Screenshots that show the state of the UI (if applicable)</summary>

<img width="1150" alt="xcodescreenshot" src="https://user-images.githubusercontent.com/3321592/48158234-fd2c0c80-e29f-11e8-8ce0-2518aff05789.png">

</details>

| Name            | Value |
|-----------------|-------|
| Link `env`      |  development   |
| LinkKit version |   1.1.12 and 1.1.13    |
| iOS version     |   10/11/12    |
| iOS device      |   N/A    |
| Xcode Version | 10 |
| iOS SDK version | 12 |

**Comment by afh** [comment]
Thanks for reporting @ajfigueroa; looking into it.

**Comment by afh** [comment]
Thank you very much for providing the PlaidBadAccessDemoProject; it has been very helpful in identifying the issue. A fix will be available with the next release.

What I can offer for the time being is a patch you can apply to LinkKit.framework that will address the issue in the current version:

```
% pwd
$PATH_TO/PlaidBadAccessDemoProject

% patch --dry-run -p0 < PLKConfiguration_h.patch
patching file Pods/Plaid/ios/LinkKit.framework/Headers/PLKConfiguration.h

% cat PLKConfiguration_h.patch
--- Pods/Plaid/ios/LinkKit.framework/Headers/_PLKConfiguration.h	2018-11-07 23:33:02.000000000 +0100
+++ Pods/Plaid/ios/LinkKit.framework/Headers/PLKConfiguration.h	2018-11-07 23:29:07.000000000 +0100
@@ -113,14 +113,14 @@
 @property (readonly) PLKProduct product;
 
 /// Displayed once a user has successfully linked their account.
-@property (copy,nonatomic) NSString* clientName;
+@property (copy,nonatomic) NSString* _Nullable clientName;
 
 #pragma mark Optional configuration properties
 /**
  The webhook to receive notifications once a user's transactions have been processed and are ready for use.
  For details consult https://plaid.com/docs/api/#webhook.
  */
-@property (copy,nonatomic) NSURL* webhook;
+@property (copy,nonatomic) NSURL* _Nullable webhook;
 
 /// Whether support for longtailAuth institutions should be enabled.
 @property (readonly) BOOL longtailAuth;
```

Let me know if this works for you.

**Comment by afh** [comment]
And an extra 👏 for this ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ bug report!

**Comment by ajfigueroa** [comment]
@afh Thanks for the quick turnaround, the nullability update works. 🎉 

Was this an error during the code conversion phase (that is, from Obj-C to Swift)? It's interesting that adding the proper nullability annotation resolves it.

**Comment by afh** [comment]
Happy to hear that the patch works for you 🙂

Not sure what you mean by *the code conversion phase*; LinkKit is written in Objective-C.

I'm afraid it has been on oversight ever since the first version of LinkKit due to [`NS_ASSUME_NONNULL_BEGIN`](https://github.com/plaid/link/blob/master/ios/LinkKit.framework/Headers/PLKConfiguration.h#L12) being used.

The proper nullability annotation resolves it, because when Swift tries to force unwrap the uninitalized `webhook` property it comes across `nil` and then `EXC_BAD_INSTRUCTION` occurs. With the proper nullability annotation Swift knows that the property may be nil and handles it as an Optional.

Fortunately the issue you observe only happens when the property is accessed from Swift while it is still `nil`, so something that in real world applications should happen rarely.

Thanks for finding and reporting this :pray:

**Comment by ajfigueroa** [comment]
@afh Is there a release planned for December?

**Comment by afh** [comment]
Hi @ajfigueroa, there sure is! [LinkKit 1.1.14](https://github.com/plaid/link/releases/tag/ios%2F1.1.14) was released earlier today and addresses this issue.
