### ISSUE TITLE
Ember component

### ISSUE THREAD

**Issue by jasonkriss** [plaid/link#30]
Not sure if this is the best place to put this but wanted to share in case it was useful for anyone else...

I needed to use Plaid from an Ember app, so I wrapped the Link plugin in an ember component. The project is [here](https://github.com/jasonkriss/ember-plaid).

**Comment by michaelckelly** [comment]
Thanks @jasonkriss - we're working on putting together a list of Link community resources within the [/examples](https://github.com/plaid/link/tree/master/examples) directory. If it's ok with you we'll add a link to the ember component there!

**Comment by jasonkriss** [comment]
That sounds great! Thanks @michaelckelly.

**Comment by michaelckelly** [comment]
Added - check out https://github.com/plaid/link/tree/master/examples!

**Comment by jasonkriss** [comment]
Thanks @michaelckelly!
