### ISSUE TITLE
About Micro deposit implementation

### ISSUE THREAD

**Issue by mehulpxm** [plaid/link#303]
If anyone knows please explain me the flow to implement micro deposit in the plaid link in android webview?

**Comment by ravron** [comment]
Hi @mehulpxm! Using the full suite of Auth products is possible regardless of platform, and is documented [here](https://plaid.com/docs/#auth). Your account must be enabled for the authentication paths other than Instant Auth, as noted in that documentation. Please reach out to your account manager or integrations@plaid.com to get started.
