### ISSUE TITLE
Micro-Deposits linkConfiguration.clientName = "Link Demo" to "My App" loading continue and never stop (Link iOS Swift)

### ISSUE THREAD

**Issue by MannVik** [plaid/link#304]
I am implementing Micro-Deposits and set linkConfiguration.clientName = "My App" -> Search bank -> Click on Link With Account number -> Enter rounting number -> Enter account number  -> Click on continue -> loading appear and never stop(not call any delegate method). If i set  linkConfiguration.clientName = "Link Demo", It's work perfectly.

**Comment by pbernasconi** [comment]
Hi @MannVik - we're looking into this right now, and will likely be releasing a new version of Link iOS later today. Stay tuned for an update soon from me

**Comment by MannVik** [comment]
Hi @pbernasconi , Thank you for releasing new version, LinkKit 1.1.16 
fixed this issue.
