### ISSUE TITLE
[Feature request] Way to know if user already updated Item

### ISSUE THREAD

**Issue by dhoffman34** [plaid/link#305]
Currently, if we open Plaid Link in update mode but the Item has actually already been fixed, then when the user closes the modal, the onExit callback gets called with `exitScreen = "requires_credentials", exitReason = "abandoned"`. This is indistinguishable from the case where the user opens Plaid Link in update mode for an Item that actually needs to be updated, but just happened to close the modal before actually reauthenticating.

This is an issue for us because there are certain edge cases where it's possible for our system to get out of sync with Plaid and prompt the user to reconnect when really they shouldn't. As is, there's no way for us to tell that the connection is actually good and get the system back in sync. We were thinking that just calling the `onSuccess` callback in that case would be good.

**Comment by dangreenisrael** [comment]
This issues is superseded by https://github.com/plaid/link/issues/308
