### ISSUE TITLE
z-index needed?

### ISSUE THREAD

**Issue by jasonkriss** [plaid/link#31]
Stripe checkout puts a z-index of 9999 on their iframe. I think something like this is probably needed here as well. Currently, I have to override the styles for #plaid-link-iframe in order to make sure it displays on top.

**Comment by c316** [comment]
+1, I am manually doing this, but it took a few attempts before I even realized that was the reason I wasn't seeing the link window. Also, not sure if the beta side has a different iframe id, but when I first switched I had to add that id to my stylesheet.

**Comment by michaelckelly** [comment]
@jasonkriss and @c316:

Thanks for pointing that out - that is definitely an inconvenience. We'll push out an updated version with a large default `z-index` value. I'll be sure to update this issue once that's happened.

**Comment by jasonkriss** [comment]
Nice! Thanks for the quick response @michaelckelly.

**Comment by michaelckelly** [comment]
No worries, @jasonkriss - the updated version is live, now, too! No code changes are necessary on your end (although I suppose you could remove your explicit z-index assignment now). Let us know if you're still encountering issues there.

**Comment by jasonkriss** [comment]
Beautiful. Just removed my z-index and I can confirm it's working now. Thanks!
