### ISSUE TITLE
Google verification code problem

### ISSUE THREAD

**Issue by liuxiaodao1** [plaid/link#311]
We are your Chinese user, if you do not install VPN, you cannot show Google verification code, may I ask if there is a solution to this problem? Thank you!
![161553068463_ pic](https://user-images.githubusercontent.com/16780762/54667874-7843e000-4b28-11e9-831c-b52bc0c93223.jpg)

**Comment by afh** [comment]
Thank you for reaching out @liuxiaodao1,

how are you integrating Plaid Link in your application? Are you using the native LinkKit SDK or WebViews?

**Comment by liuxiaodao1** [comment]
Thanks for your reply. I use plaid in webviews.


| |
刘睢
|
|
邮箱：liusui1122@163.com
|

签名由 网易邮箱大师 定制

On 03/21/2019 00:07, Alexis Hildebrandt wrote:

Thank you for reaching out @liuxiaodao1,

how are you integrating Plaid Link in your application? Are you using the native LinkKit SDK or WebViews?

**Comment by liuxiaodao1** [comment]
Sorry for our urgent project, could you please reply as soon as possible? we using wkwebview.

**Comment by afh** [comment]
@liuxiaodao1 Please [open a support issue through the Plaid dashboard](https://dashboard.plaid.com/support), this way we are able to assist you better.

**Comment by liuxiaodao1** [comment]
hello, could you answer the question. thanks!
