### ISSUE TITLE
didExitWithError delegate method gets called 2 times in a row while loading

### ISSUE THREAD

**Issue by tolgaarikan** [plaid/link#312]
### A detailed description of the steps to reproduce the issue

* Configure and present the PLKPlaidLinkViewController
* Dismiss it while the view controller is loading (when it's showing the activity indicator)
* Notice, `linkViewController(_ linkViewController: PLKPlaidLinkViewController, didExitWithError error: Error?, metadata: [String: Any]?)` gets called 2 times in a row.

### What you expected to see?

The default behavior is that this delegate method gets called one time when you tap dismiss button. You can see this if you tap dismiss button on right top after loading.

### What you saw instead?

While the PLKPlaidLinkViewController is loading and you tap on dismiss button on top right, the 
didExitWithError delegate method is invoked 2 times in a row.

The reason for this is related to the canceled API request(see below), the second call is because of this error, but this does not make any sense from the perspective of the user of this SDK, because this error happens 100% of the time when I tap the dismiss button while the view controller is loading. And even if it is happening it does not need to call the delegate method, it can invoke the method once and pass the error the first time it is called.

```
Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://sandbox.plaid.com/link/client/get, NSLocalizedDescription=cancelled, NSErrorFailingURLKey=https://sandbox.plaid.com/link/client/get}
```

| Name            | Value |
|-----------------|-------|
| Link `env`      |   both in production and sandbox    |
| LinkKit version |   LinkKit 1.1.15    |
| iOS version     |   iOS 12    |
| iOS device      |   iPhone 8(real device), and simulator    |

**Comment by afh** [comment]
Thank you for your report @tolgaarikan, will look into this.

**Comment by jleandroperez** [comment]
Hello @tolgaarikan! thank you for reporting this!. This behavior was actually updated in LinkKit 1.1.15: i can only reproduce the double error callback in v1.1.14.

For sanity check, would it be possible to retest with the [latest stable release](https://github.com/plaid/link/releases/tag/ios%2F1.1.17)?

Thanks in advance!

**Comment by tolgaarikan** [comment]
Hey @jleandroperez, I did not have any time to check this yet, I will do it this week and let you know. 
Thanks as well!

**Comment by tolgaarikan** [comment]
Hey @jleandroperez, I updated to 1.1.18 and tested today and was not able to reproduce the double error callback. Thanks!

**Comment by afh** [comment]
Thanks, @tolgaarikan, getting back to us on this issue and using Plaid Link for iOS!
