### ISSUE TITLE
Android WebView Example - no redirection happing

### ISSUE THREAD

**Issue by ericntw** [plaid/link#313]
*Please do not include your API `secret` or `public_key` in any issue.*
---
### A detailed description of the steps to reproduce the issue

* Supply the public key and run the app
* Go through the flow (select Chase bank, enter user_good, pass_good etc.)
* Observe in Android LogCat or through debugger that no redirection is happing, the whole plaid webpage seems like a fancy single page application doing everything with Javascript

### What you expected to see?
Redirection to the `plaidlink://...` urls like described in your documentation! https://plaid.com/docs/#webview-integration

### What you saw instead?
0 redirection, none of the following is triggered throughout the flow:
```java
@Override
            public void onPageStarted(WebView view, String url, Bitmap favicon) {
                super.onPageStarted(view, url, favicon);
                Log.i("", "onPageStarted " + url);
            }

            @Override
            public void onPageFinished(WebView view, String url) {
                super.onPageFinished(view, url);
                Log.i("", "onPageFinished " + url);
            }

            @Override
            public boolean shouldOverrideUrlLoading(WebView view, String url) {
                Log.i("", "shouldOverrideUrlLoading " + url);
                // ...
            }
```

---

When submitting an issue for Link on the web or within a Webview, please include the following information:

|       Name       | Value |
|------------------|-------|
| Link `env`       |  what is it? Didn't modify your example code   |
| Browser          |   you mean WebView engine?    |
| Operating system |   Android 7.0    |

---

When submitting an issue for [**Plaid Link iOS**](https://github.com/plaid/link/tree/master/ios) please include the following information:

| Name            | Value |
|-----------------|-------|
| Link `env`      |       |
| LinkKit version |       |
| iOS version     |       |
| iOS device      |       |

#### List of used 3rd party libraries (e.g. CocoaPods):

* [Plaid](https://cocoapods.org/pods/Plaid)
*
*

**Comment by ravron** [comment]
Hi @ericntw! Are you passing `isWebview=true` in the query string? If not, Link won't issue redirects. The parameter is listed at the bottom of Link's [parameter reference](https://plaid.com/docs/#parameter-reference). 

If you are already passing that parameter or doing so doesn't seem to work, could you please provide the code you're using to integrate with Link?

**Comment by ericntw** [comment]
Thanks @ravron for the super prompt reply, it's working now!
For some reason, LogUtil wasn't printing
