### ISSUE TITLE
How do I test same-day microdeposits in sandbox mode?

### ISSUE THREAD

**Issue by mruhlin** [plaid/link#316]
I'm trying to integrate with the ability to manually enter ACH and routing info, then verify the account with same-day microdeposits, but am unsure what amounts in dev/sandbox environments to verify the account.  

I'm using the Stripe test ACH numbers documented [here](https://support.plaid.com/hc/en-us/articles/360008270974-Testing-Plaid-Stripe).  Once I've entered the account number and reloaded Plaid Link with my new public token, I'm prompted to enter two microdeposit amounts, but obviously I can't look at an account statement for a fake account.  I assume there are specific numbers I can enter to simulate a success, but I don't see them documented anywhere?

It would be good to update that page and [this one](https://plaid.com/docs/#auth) with info on what microdeposit numbers to use.  Thanks

**Comment by mruhlin** [comment]
As soon as I posted this it dawned on me that [Stripe's documentation](https://stripe.com/docs/ach) might have better info, but the numbers they list there (32 and 45) don't seem to work

**Comment by ravron** [comment]
Hi @mruhlin! In the sandbox environment, you can test same-day micro-deposits using the following data:

| Account | Routing number | Account number | Micro-deposit values |
|:-:|:-:|:-:|:-:|
| Either checking or savings | 011401533 | 1111222233330000 | $0.01 and $0.02 |

You can [find these values documented in the sandbox section of our docs](https://plaid.com/docs/#sandbox-auth-testing).

The development environment is different from sandbox in that it operates on real, production data, but is limited in the number of items you can create. Thus there's no special values you can use to quickly test behavior — you'll have to actually send micro-deposits to a real account and verify them as described in the documentation.

**Comment by mruhlin** [comment]
thanks!

**Comment by priyanka-terala** [comment]
Hi @mruhlin,
This question is again in the context of same-day microdeposits in sandbox env. 
I am able to invoke Plaid link and it operates in "Instant Auth" mode.
How do I invoke the other types of Authentication? - Instant Match, same -day micro-deposits.
