### ISSUE TITLE
[Question] Android WebView. How to add user and multiple products params?

### ISSUE THREAD

**Issue by mmachado53** [plaid/link#319]
I am trying to build the link WebView initialization URL in android, but I do not know how to send the parameters "product" and "user". Does anyone have any ideas? Thank you.
```
val builder = Uri.parse("https://cdn.plaid.com/link/v2/stable/link.html")
                .buildUpon()
                .appendQueryParameter("isWebview", "true")
                .appendQueryParameter("isMobile", "true")
                .appendQueryParameter("key","MY_KEY")
                // ITS OK "transactions,auth"?
                .appendQueryParameter("product","transactions,auth") 
                .appendQueryParameter("apiVersion","v2")
                .appendQueryParameter("env","sandbox")
                .appendQueryParameter("clientName","MY_CLIENT_NAME")
                .appendQueryParameter("selectAccount","true")
                .appendQueryParameter("webhook","https://test.com/webhook")
                // HOW TO SEND A user OBJECT?
                .appendQueryParameter("user","{legalName:'name',emailAddress:'hello@hello.com'}") 
```

**Comment by CHico-Lee** [comment]
Try this to send the "user" object:
`val userObj = JSONObject()`
`userObj.put("legalName", "name")`
`userObj.put("emailAddress", "hello@hello.com")`
Then
`.appendQueryParameter("user", userObj.toString())`

**Comment by mmachado53** [comment]
> Try this to send the "user" object:
> `val userObj = JSONObject()`
> `userObj.put("legalName", "name")`
> `userObj.put("emailAddress", "hello@hello.com")`
> Then
> `.appendQueryParameter("user", userObj.toString())`

Thanks, it works!
