### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by c316** [plaid/link#35]
Is this something that Plaid link is doing? If so, it isn't working well. 

![2015-06-03 10 36 32](https://cloud.githubusercontent.com/assets/3142974/7964387/15613f4a-09dd-11e5-852e-c18116536dee.png)

I have Plaid Link running in a Cordova app. If I hold the device in portrait, start the app and launch Plaid Link it works fine. If I then turn it on its side it still works, but when I hold it back into portrait I get the message on that screenshot. The only way to make it go away is to hold the device in landscape.

**Comment by CrisFeo** [comment]
Hi @c316,
I'm taking a look into this now. I'll let you know what I find.
-Cris

**Comment by CrisFeo** [comment]
Hey @c316,

So that modal _is_ created by Link, however there was some broken logic related to when it was displayed. I have a completed fix and it is in the pipeline for released.

I let you know when the fix goes live so you can verify that it is working.

Thank you for your patience,
Cris

**Comment by c316** [comment]
Thanks

**Comment by CrisFeo** [comment]
@c316, the fix is deployed, the modal should now function as expected!

**Comment by c316** [comment]
Yes, works. Thanks
