### ISSUE TITLE
Please generate random data

### ISSUE THREAD

**Issue by c316** [plaid/link#36]
When using tartan;

Please generate random _id, _item and _user id's. Right now these are identical across all institutions, which means I can't store multiple institutions in my MongoDB database if I use _id as the primary key. And, there are other problems related to duplicate _item and _user ids.

Thanks

**Comment by michaelckelly** [comment]
Copying from https://github.com/plaid/support/issues/159 and @susanfowler:

> Hello @c316!

> Thanks for bringing this to our attention! We realize this could be an issue, so we will be changing it in the next version of the API, which will be available in the next few months.

> Let us know if you have any questions!
