### ISSUE TITLE
formating issues on iPhone 4, 5, and 6

### ISSUE THREAD

**Issue by mattch** [plaid/link#38]
I took the sample code and dropped it into a fullscreen webview on IOS.  Everything works great on all devices, and it even looks good on iPad screen sizes. But on all iPhones, the formatting is distorted (see screenshot below).

I tried modifying the institution-button element, but it had no effect.

Is there something I need to do to get the formatting to work for iPhone or are there some formating parameters that I can adjust ?

Ideally, the institution screen should be a single scrollable column on the iPhone.

![ios simulator screen shot jun 21 2015 6 08 31 pm](https://cloud.githubusercontent.com/assets/963058/8274220/cbb77e36-1841-11e5-8b20-c580541abe19.png)

**Comment by michaelckelly** [comment]
@mattch

No changes should be required for iPhone support at all. Are you using Safari on iOS or a different browser?

Apologies for the issue - we'll get to the bottom of this as quickly as possible!

**Comment by mattch** [comment]
Thanks, Michael.  I actually got it to work by tweaking the WebView properties.  WebView is a way to show HTML/Javascript inside a native IOS app.

**Comment by mattch** [comment]
Plaid/Link seems to be truncating part of the screen in very specific situations.  See screenshots in the previous post.

**Comment by michaelckelly** [comment]
@mattch 

Thanks for the screenshots - we'll look into those and get back to you shortly!

I'm glad you got Link working within a webview - out of curiosity, what options did you have to change in order to get it working properly? Hopefully we can document those steps in the [README](https://github.com/plaid/link/blob/master/README.md) so that it'll be easier for others to get going in the future.

**Comment by mattch** [comment]
Thanks !  I changed several properties, but I believe the one that fixed the formatting was disabling the Scale To Fit.

I'm noticing that institution page is sporadically being truncated on the sides, but if I select an institution and then return back to the institution page, it looks good.  There seems to be a race condition with the initial setup of the institution page.

**Comment by mattch** [comment]
Let me know if you need any more info

This is a show stopper for me. When do you think this issue will get worked on ?

**Comment by michaelckelly** [comment]
@mattch 

Sorry for the slow response - we're looking into this now and will keep this issue updated with our progress.

Michael

**Comment by pbernasconi** [comment]
@mattch I've just tested the link-client inside of a webview on my iPhone 6 and the iOS simulator and I haven't encountered any visual issues with the sizing (using cordova to build the app natively).  Can you provide some more details for the specific environment you're using in the WebView (IE are you using cordova + some framework, or a custom webview?) What version of iOS are you using?

My guess is that it's a fixable CSS issue on your side, but if I can reproduce your error in your environment we might be able to see what's going wrong.

In general we'd like to support WebViews for mobile, but we're still in the process of testing and hammering out the bugs.

**Comment by mattch** [comment]
@pbernasconi  I'm just using a bare bones vanilla WebView from Apple (e.g. no cordova).  It's a WebView inside of a UIViewController that has constraints on it so that it's the full size of the screen. 

I'm not specifying any CSS.  My html code looks almost identical to the sample custom integration except I go directly to the Bank Selection Page (e.g. linkHandler.open()).  

I've noticed that the institution screen looks good when returning to it a second time.  It only seems to have the wrong screen size on the initial load, suggesting some race condition.   So here are the steps:
1) Open WebView and load Link html code in viewDidAppear
2) Bank Selection Page is truncating edges
3) Pick a bank (e.g. Chase)
4) Return to the Bank Selection Page
5) Bank Selection Page looks good


Here's my html code that is loaded in the webview:
```
	<body bgcolor="black">
		<script src="https://cdn.plaid.com/link/stable/link-initialize.js"></script>
		<script>
			function callObjC(functionName) {
				//code to call Objective-c
			}
		
			var linkHandler = Plaid.create({
				   env: 'tartan',
				   clientName: 'Client Name',
				   key: 'test_key',
				   product: 'auth',
				   onLoad: function() {
						// The Link module finished loading.
						callObjC("onLoad");
				   },
				   onSuccess: function(public_token) {
						// Send your public_token to your app server here.
						callObjC("onSuccess:" + public_token);
				   },
				   onExit: function() {
						// The user exited the Link flow.
						callObjC("onExit");
				   },
			});

			// Trigger the BofA login view
			//document.getElementById('bofaButton').onclick = function() {linkHandler.open('bofa');};

		// Trigger the standard institution select view
		linkHandler.open();

		</script>
	</body>

**Comment by mattch** [comment]
@pbernasconi  Do you have enough info to fix the problem ?

**Comment by pbernasconi** [comment]
@mattch I can now confirm that this is an issue -- took me a while to replicate it and find the bug, but I've tested the next release of Link and it should definitely be fixed. 

**The issue**: UIWebView is different than the mobile Safari browser, *but in strange and unknown ways* -- so upon initialization of Link, something was happening where a function was not called in time, resulting in the lack of a `mobile` class being appended to the link-container.

We're hoping to release the next version by the end of the week, so stay tuned.

**Comment by mattch** [comment]
@pbernasconi  Thanks !!

**Comment by mattch** [comment]
Any updates on this issue ?

**Comment by pbernasconi** [comment]
Hey @mattch we're still fixing a few other bugs in Link which we're trying to push out very soon. The minute we do, I'll let you know!

**Comment by pbernasconi** [comment]
Hey @mattch we pushed out the latest version of Link with several improvements for mobile and UIWebView-- your issues should be fixed, thanks for your patience!

If you are still encountering issues please let us know.
