### ISSUE TITLE
Is there a way to get the institution type that a user added ?

### ISSUE THREAD

**Issue by mattch** [plaid/link#39]
After a user adds an institution, I'd like to get the name of the institution associated with the public_token.  In the sandbox, I'm getting a public_token of "test,bofa,connected", but I'm assuming the real public_tokens won't have the institution name in the token.

Is there a way to get the institution type from the token or when the user selects one during the Link flow ?

I realize I can get the institution when I retrieve the transactions as part of the Accounts, but I'd like to get it before I make that call.

**Comment by michaelckelly** [comment]
@mattch 

There is not currently a way to get the institution type without doing what you mentioned. Are you using [custom initializers](https://github.com/plaid/link#step-2-custom-integration) or the [simple](https://github.com/plaid/link#step-2-simple-integration) Link integration?

**Comment by mattch** [comment]
Thanks. I'm using the custom integration.

**Comment by djlovegrind** [comment]
You have to handle that yourself somehow, I just built my own step to select their institution (similar to the first step of "simple" Link integration). Pass a value in there, corresponding to which institution they select. @mattch

**Comment by idris** [comment]
Yeah, getting the type along with the token would be nice.  Currently I'm just immediately fetching the accounts and pulling the type from the first account.

**Comment by todd-mulholland-avalara** [comment]
@djlovegrind what are you passing into your open() call?  The docs point you to institution.type, however, the institutions/search doesn't return type - only id.  Thanks for the help.

**Comment by tmulholl** [comment]
As a workaround, I've done what @djlovegrind  suggested.  Works good, however, in certain cases Link shows a "Restart" button which resets the state and takes you back to the institution selection view.  If a user then selects a different institution, the wrong institution id gets associated with the access token.

**Comment by michaelckelly** [comment]
@tmulholl @idris @djlovegrind @mattch 

I realize we've been slow to get this integrated to Link, but we're actively working on this feature and plan to make the institution type available within the next week or two. I'll keep this issue up-to-date as well. Thank you to everyone for your patience!

**Comment by traviscollins** [comment]
Very much looking forward to this feature. If at all possible, could you include the institutions full name, and the icon data?

**Comment by michaelckelly** [comment]
@traviscollins 

> If at all possible, could you include the institutions full name, and the icon data?

Keep an eye out for this feature to be released shortly, but the institution data will be an object in the form of:

```
{name: 'Bank of America', type: 'bofa'}
```

**Comment by traviscollins** [comment]
Good enough. I assume we can get the icon data from the long tail end point?

Travis Collins
(703)980-3804

**Comment by michaelckelly** [comment]
@tmulholl @idris @djlovegrind @mattch @traviscollins 

This feature is now live:

```
<button id='linkButton'>Open Plaid Link</button>
<script src="https://cdn.plaid.com/link/stable/link-initialize.js"></script>
<script>
var linkHandler = Plaid.create({
  env: 'tartan',
  clientName: 'Test Client',
  key: 'test_key',
  product: 'auth',
  onSuccess: function(public_token, metadata) {
    // Send your public_token to your app server here.
    console.log(
      'public_token: %s, institution type: %s, institution name: %s',
      public_token, metadata.institution.type, metadata.institution.name)
    ;
  },
});

// Trigger the Link UI
document.getElementById('linkButton').onclick = function() {
  linkHandler.open();
};
</script>
```

We'll update the docs shortly - thanks for everyone's patience!

**Comment by traviscollins** [comment]
This is working great! Thanks!

**Comment by michaelckelly** [comment]
Great, @traviscollins!

I'm going to ahead and close this issue - please reopen if needed! We'll update the Link docs in the coming days, too.
