### ISSUE TITLE
USAA display issues

### ISSUE THREAD

**Issue by Alexolp** [plaid/link#42]
If a user closes the USAA popup after failing a security question, and then re-opens the USAA popup the submit button ends up partial out of the frame.

**Comment by pbernasconi** [comment]
Thanks for raising this issue @Alexolp - I can reproduce and confirm it, and we'll look to get a fix out by the beginning of next week.

<img width="316" alt="screen shot 2015-08-06 at 1 47 29 pm" src="https://cloud.githubusercontent.com/assets/1716394/9121770/b145545a-3c41-11e5-9673-67b58f84549c.png">

**Comment by pbernasconi** [comment]
@Alexolp we just released an updated version of Link, and it includes a fix to this issue - thanks for raising it!
