### ISSUE TITLE
Multiple Accounts 

### ISSUE THREAD

**Issue by Prince2k3** [plaid/link#45]
This is more a question really. Does Plaid Link Support if a user has more than one account? I didn't really see it in the demo or readme that could answer this question.

Thanks

**Comment by pbernasconi** [comment]
@Prince2k3  Even though you closed this issue, I feel it deserves an answer:

We are currently building a new feature into Link, which will enable users to select a specific sub-account after they have connected their bank account (look for this in the coming two weeks). At the moment however, we return a `public_token`from Link, which then must be exchanged for an `access_token` sever-side. Once you've done this exchange you'll have access to a list of the user's sub-accounts, and can prompt your user client-side to select which account they wish to use.

**Comment by rishikumar** [comment]
Hi @pbernasconi  - has this feature been implemented? I don't see it as part of the demo app on https://demo.plaid.com, but perhaps its not setup to display multiple accounts in this fashion.

Thanks for putting this tool together!
