### ISSUE TITLE
Plaid-Link Custom linkHandler error on second page render from within application

### ISSUE THREAD

**Issue by PilotCurly99** [plaid/link#50]
**RAILS APPLICATION**

When the page that contains my custom Plaid-Link button renders for a second time, I am unable to open Plaid-Link.  This only happens when returning to the page where I call Plaid-Link and rendering for a second time in the application.  A full page reload works as expected with no issues and I am able to call Plaid-Link multiple times.

*Not the strongest at Javascript, so don't be afraid to dumb the answer down.  Everything else on the integration is working 4.0.*

I have tried using:

     document.getElementById('#linkButton').onclick = function() {
        linkHandler.open();
but get the same result.  I have also tried disabling turbolinks on the button, same thing.

Javascript error: 
     
     Uncaught TypeError: Cannot read property 'postMessage' of null
     l	                                @	link-initialize.js:1
     a.define.C.exports.create.a.open	@	link-initialize.js:1
      document.getElementById.onclick	@	VM44852:25

Here is the button I am using to call Plaid-Link:

     <%= image_tag("https://www.example.com/*********************/bank-icon.png", 
                  id: "linkButton", onclick: "linkHandler.open();", style: "cursor: pointer", 
                  class: "controls") %>

Here is the custom Plaid-Link:

      <script src="https://cdn.plaid.com/link/stable/link-initialize.js"></script>

      <script>
      var linkHandler = Plaid.create({
        env: 'production',
        clientName: '**************',
        key: '****************************',
        product: 'connect',
        longTail: true,
        webhook: "https://www.example.com/***********",
        
        onLoad: function() {
          // The Link module finished loading.
        },
        onSuccess: function(public_token) {
          // Send your public_token to your app server here.
          window.location.replace('<%= root_url %>users/<%= user.id %>?public_token=' + public_token);
          
        },
        onExit: function() {
          // The user exited the Link flow.
        },
      });
      
      // Trigger the standard institution select view
      document.getElementById('linkButton').onclick = function() {
        linkHandler.open();
      };
      </script>

**Comment by michaelckelly** [comment]
@PilotCurly99 

Thanks for the heads up and the detailed code snippets / overview -- we'll dig into this and follow up once we have additional information! Let us know if you have any additional questions in the meantime.

**Comment by CrisFeo** [comment]
Hi @PilotCurly99!

So I'm not a Rails expert but I took a quick look into Turbolinks and I'm suspicious that it might be causing the behavior you are seeing.

Is the code you posted above in the ```<body>```, or the ```<head>```? If its in the ```<body>``` then Turbolinks might be loading the Link script multiple times. Could you try moving that code into your ```<head>``` tag?

If that doesn't work could you post a stripped-down version of your page that only includes the elements which cause the error? I can try to work backwards from there.

**Comment by PilotCurly99** [comment]
I've tried disabling turbolinks on the custom button I am using for Plaid-Link.  No joy.

The code I posted was contained within the       `<body>`.  I gave it a try to move it into the `<head>`, but that opened up another can of worms as the head is contained in the application.html.erb layout.  That is rendered before '@user' which creates problems for the 'replace' function.

I need to go through and do a bunch of refactoring in my views and I suspect that once I do, that I will find a workaround for the problem.  If you come across a solution, I'm all ears.  But I think when I move that portion into a partial that does not get re-rendered as the user moves through the different views, it will take care of the problem.

So if you want to close the issue for now that works for me.  I'll open a new issue if that doesn't fix it.

**Comment by PilotCurly99** [comment]
Update - Yes, it is a turbolinks issue.  So I'll chew on how to fix it.  Thanks.

**Comment by CrisFeo** [comment]
Ok that all sounds good, definitely let us know if you are still having problems with Link after sorting out Turbolinks!

**Comment by PilotCurly99** [comment]
Figured this one out.  You have to disable the turbolink that takes you to the page with the Plaid Link Button.  The turbolink on the Plaid Link button has not effect.  Seems obvious now, but was not obvious when I opened this issue originally.  Hope this saves someone else some time.
