### ISSUE TITLE
Timeline for native iOS/Android bindings

### ISSUE THREAD

**Issue by pandringa** [plaid/link#51]
The README says that "Plaid Link will offer native iOS and Android bindings in the coming months", but that commit (https://github.com/plaid/link/commit/60a6efc8423ed603df293773709f02e9e4261050) was written back in early May, about 5 months ago. Are there any updates to the timeline for native bindings?

I'd be happy to help test/contribute bug fixes if that would speed things along. 

Thanks!

**Comment by michaelckelly** [comment]
Thanks for nudge, @pandringa! We're hard at work on native bindings for Link - I don't have any firm launch dates to share at this time, but we'll be sure to update the README as soon as we do! We'll be sure to reach out if we're in need of beta testers as well - thanks for the offer. :)

**Comment by tunam3lt** [comment]
Any update on this? Also interested in helping test.

**Comment by damianesteban** [comment]
I would also be happy to test.

**Comment by Taakn** [comment]
+1 :)

**Comment by travisvalentine** [comment]
Adding another 👍 to this.

**Comment by michaelckelly** [comment]
@pandringa @tunam3lt  @damianesteban @travisvalentine -

Thanks for your continued patience - we're hoping to start beta testing native Link bindings for iOS by end of year! We'll be sure to share information here as soon as we're ready!

**Comment by michaelckelly** [comment]
@pandringa @tunam3lt @damianesteban @travisvalentine 

Check out [Link iOS](https://github.com/plaid/link/tree/master/ios)!
