### ISSUE TITLE
Link Dialog too big for iPhone 5?

### ISSUE THREAD

**Issue by idris** [plaid/link#53]
We have a user who is on an iPhone 5c and sent a screenshot (below) of the link widget.

![plaid-link-iphone5s](https://cloud.githubusercontent.com/assets/13989/10709992/607611c8-7a43-11e5-977c-d525651c4bf5.png)

As you can see, the banks are cut off at the bottom and the long tail search link overlaps the bottom row.  Also, this user reported that she was unable to scroll down to fully see those bottom buttons.

**Comment by michaelckelly** [comment]
@idris - are you still experiencing this issue? We regularly test Link on iPhone 5 and have not encountered any visual display issues recently. Happy to dig into this further if you are!

**Comment by idris** [comment]
We only had one user report this a while back.  I'm going to close this and will re-open if we see it again.

**Comment by michaelckelly** [comment]
Great, thanks @idris - we appreciate the feedback!
