### ISSUE TITLE
After using search, UI for USAA is wrong 

### ISSUE THREAD

**Issue by traviscollins** [plaid/link#55]
See the attached image for the issue. 

Steps to reproduce:

1) Open Plaid Link with connect and long tail enabled
2) Click View More
3) Search for USAA
4) Click USAA
5) See that PIN code is covered by submit button. 

![screen shot 2015-11-13 at 10 46 10 am](https://cloud.githubusercontent.com/assets/923065/11150083/04700e0e-89f4-11e5-900b-18fe6184b497.png)

**Comment by michaelckelly** [comment]
@traviscollins - thanks for the heads up, we'll get this sorted out quickly. I'll keep this issue updated!

**Comment by michaelckelly** [comment]
@traviscollins - thanks again for bringing this to our attention. The fix for this bug has been released!

**Comment by traviscollins** [comment]
I see it fixed as well. Very cool release process you have here.
