### ISSUE TITLE
Fixing an errored account

### ISSUE THREAD

**Issue by idris** [plaid/link#56]
When an account is in an error status, the docs say to pass the public token to Plaid Link using the `token` option.  That seems to work, but how do we know that the account is no longer in error?

After going through plaid link with an errored account, I got no webhooks for the account letting me know that things were okay again.  Is it safe to assume that if `onSuccess` is called, everything is fine now?  And will there be a new public token passed to `onSuccess`?

**Comment by michaelckelly** [comment]
@idris 

Good question - the `onSuccess` callback is an indicator that the account is back in a good state. I'm sorry if that was not clear - we'll work on updating the docs to make it so.

There will not be a new public token - it will be the same public token.

**Comment by idris** [comment]
Thanks! Very helpful
