### ISSUE TITLE
Encrypted JSON response from getAuthUser

### ISSUE THREAD

**Issue by mpk2** [plaid/link#57]
When calling `plaid.client.getAuthUser(access_token)`, information is returned in plain JSON. Is there currently no way to request information encrypted by a specified public key? Was hoping there was support for `plaid.client.getAuthUser(access_token, public_key)` and an encrypted JSON response or a JSON response with encrypted sensitive fields (e.g. account number) would be returned.

**Comment by michaelckelly** [comment]
@mpk2 

We do not support encrypted bodies at this time - I'll pass that feedback along to our API team, though!
