### ISSUE TITLE
Unable to use plaid link in update mode (Invalid public_token on all requests)

### ISSUE THREAD

**Issue by t3jem** [plaid/link#58]
I'm attempting to use the plaid link plugin in update mode in order to update an account; however, all requests are resulting in the following response: {"error":"Invalid public_token","request_id":"oKm31"}

I've tested both with a real tartan public token and with the provided test tokens (i.e. test,wells,connected).

Sample request:
curl 'https://link-tartan.plaid.com/institution/token' -H 'Origin: https://cdn.plaid.com' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: */*' -H 'Referer: https://cdn.plaid.com/link/0.1.11/link.html' -H 'Connection: keep-alive' --data-binary '{"public_key":"<my public key>","public_token":"test,wells,connected"}' --compressed

Sample response:
{"error":"Invalid public_token","request_id":"oKm31"}

Sample code used:
```html
<script src="https://cdn.plaid.com/link/stable/link-initialize.js"></script>
<script>
linkHandler = Plaid.create({
          env: 'tartan',
          clientName: 'Test Credential Update',
          key: '...',
          product: 'connect',
          webhook: '...',
          token: 'test,wells,connected',
          onLoad: function() {console.log("loaded");},
          onSuccess: function(newPublicToken) {
            $scope.selectedPublicToken = newPublicToken;
          }
        });
      }

      updateLogin = function() {
        linkHandler.open();
      }
</script>
<button ng-click='updateLogin()'>
```

**Comment by t3jem** [comment]
Upon further investigation I found that the update flow works for active public keys; however, for keys associated with users that have had their credentials invalidated (in this case, the user's bank password changed), I receive the reported error above.

Is this a bug or by design?  I need to update this user's credentials so the transaction and account id's do not change since I use them as keys in my datastore.

**Comment by t3jem** [comment]
FYI, for those stumbling on this later.  I emailed support and it turns out I was using the private access_token rather than the public_token with the plaid link update mode.

**Comment by michaelckelly** [comment]
@t3jem - apologies for not replying directly here (we spoke via support). Thanks for providing the resolution, though - I'm sure this will be useful for other developers!
