### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by guyellis** [plaid/link#59]
I'm using https://github.com/csbarnes/angular-plaid-link which appears to make a call which references this file: https://cdn.plaid.com/link/0.1.11/link.js and then this snippet is executed:

```
this.props.institution.fields.map(function(a){...
```

The `fields` property is obviously not set.

In my HTML I'm referencing: https://cdn.plaid.com/link/stable/link-initialize.js

**Comment by guyellis** [comment]
Turns out that it was a problem on my end for using an incorrect bank code.

I'll leave this open in case you want to add some defensive code in there and return an error like 'xxxx is not a valid bank code' instead of letting this get hit.

**Comment by davidchambers** [comment]
Thanks for raising this issue, @guyellis. We could certainly make this error easier to debug. :)

**Comment by pbernasconi** [comment]
I believe this issue has been resolved in a recent release of Link. Going to close this issue, but please re-open @guyellis if you are seeing this error again.
