### ISSUE TITLE
Button for executing action outside of Link

### ISSUE THREAD

**Issue by c316** [plaid/link#61]
If my users search Link and their bank isn't displayed (because Auth isn't available for that bank). I believe the user should be able to click a button, "My bank isn't listed" and then I can tie a specific action to that button. I want to be able to handle this outside of link, but right now they would have to close link and then find something on my page or I'd have to prompt them before they start searching to let them know what to do if they can't find their bank. 

Any chance we could get a way to execute a custom action when no banks are listed?

**Comment by michaelckelly** [comment]
@c316 - That's a great suggestion, thanks for taking the time to write it up. Although all of us at Plaid are working hard to eliminate the 'no supported bank' scenario, we realize it does happen and that it can be difficult to handle elegantly with Link as it is today.

I've opened up an issue internally and shared this feature suggestion with the rest of the Link team!

**Comment by michaelckelly** [comment]
@c316 -

We do plan on incorporating this feature into Link. More info to come over the coming weeks!

**Comment by c316** [comment]
Thanks for the update

**Comment by c316** [comment]
Any update here?

**Comment by MaximusMcCann** [comment]
Agreed.  This is a clear need. Cheers.

**Comment by MaximusMcCann** [comment]
After they click the "Bank not present" button, should simply return a new case: 'exitNoBank' event or w/e

**Comment by michaelckelly** [comment]
@c316 @MaximusMcCann - the `onExit` status now supports an `institution_not_found` status. This is returned when the user unsuccessfully searches for an institution and clicks a "Don't see your bank?" prompt!
