### ISSUE TITLE
Opt out of mixpanel tracking

### ISSUE THREAD

**Issue by c316** [plaid/link#62]
Can you give us an option to opt out of mixpanel tracking when using Link? 

Thanks

**Comment by jcockhren** [comment]
:+1:

**Comment by kienpham2000** [comment]
+1

**Comment by pbernasconi** [comment]
@c316 @jcockhren @kienpham2000 

Thanks for opening this ticket regarding Mixpanel opt out, and please excuse the delayed reply. We've actually recently removed our Mixpanel library from Link and are now sending analytics events to our own internal `https://analytics.plaid.com` service.

Analytics are a key metric for us to continue to improve and fine-tune the Link experience for your end-users, however we hope this addresses some of your concerns raised in this issue.
