### ISSUE TITLE
onLoad handler does not get called if another Link instance is initialized

### ISSUE THREAD

**Issue by remotezygote** [plaid/link#66]
It seems that the onLoad callback is only called the first time a Link handler is created. If you initialize another later within the same page (for example for coming back to a page within a single-page app), the onLoad handler is never called, even though a new Link handler is initialized.

**Comment by sjmiles** [comment]
Similarly, it seems the onLoad handler is never called if the 'link' iframe should happen to load before a Link handler is created.

**Comment by michaelckelly** [comment]
@remotezygote @sjmiles -

Thanks for reporting this issue - the team is looking into this now!

**Comment by rtteal** [comment]
@michaelckelly, any update on this?

**Comment by EvanHahn** [comment]
I am also seeing this issue.

**Comment by pbernasconi** [comment]
@remotezygote I believe this issue was fixed in a recent deployment of Plaid Link, however please feel free to re-open this issue if you're still seeing this issue!
