### ISSUE TITLE
Plaid not playing well with turbolinks

### ISSUE THREAD

**Issue by nolman** [plaid/link#67]
Related to https://github.com/plaid/link/issues/50 - I think there is a problem here. I would like to keep using turbolinks to avoid the page flash on reload however plaid does not play nicely with them.
## Plaid's link-initialize.js in head

Plaid's link-initialize.js cannot be placed in the head:

```
Uncaught TypeError: Cannot read property 'appendChild' of null(anonymous function)
```
## Turbolinks:

Even when the script is placed in body and has a `data-turbolinks-eval='false'` to prevent the script reloading when the body reloads the following error will be seen:

`Uncaught TypeError: Cannot read property 'postMessage' of null`

The problem arrises because turbolinks has replaced the document body and thus the iframe that plaid relies upon.

The variable that defines the iframe is still defined but since the iframe has been removed from the dom and thus the following method call fails:

```
b.contentWindow.postMessage(JSON.stringify(g.merge({
```

I have tried to work around this a few ways:
1. Putting the javascript in the head. See the above error, although after finding the cause of the problem this approach would not have worked.
2. Adding a `data-turbolinks-permanent` attribute to the iframe or putting the iframe into a div that has a `data-turbolinks-permanent`

None of these approaches worked. I am likely going to disable the turbolinks to these pages for now however it would be nice if plaid played nicely with body reloading.

**Comment by ritec** [comment]
I was also playing with Link on a Rails project using the code from https://plaid.com/docs/link/#step-2-simple-integration (after using my public Api key) and ran into a bit of a similar issue, not sure if it's related to Turbolinks. My error was as follows: `Uncaught Error: Failed to find script(anonymous function) @ link-initialize.js?_=1454801068297:1`

Sorry to hijack this if it's not indeed related to the turbolink issues people seem to be having.

**Comment by michaelckelly** [comment]
@nolman - 

Thanks for the detailed issue - we will see what we can do to sort this out!

Michael

**Comment by pbernasconi** [comment]
Hey @nolman – since this issue was created almost 1.5 years ago and many changes have shipped in Link I'm going to close this as a stale issue, but please do open it again if you are still seeing an issue with Turbolink + Link.
