### ISSUE TITLE
Post to /exchange_token end point returns not allowed

### ISSUE THREAD

**Issue by hsmith825** [plaid/link#70]
We have spent days trying to exchange the publictoken for an access token.  We continually get an Unauthorized error. We  received an error object: {"readyState":4,"responseText":"{\n \"code\": 1702,\n \"message\": \"plaid error\",\n \"resolve\": \"An unexpected error has occurred on our systems; we've been notified and are looking into it!\"\n}","responseJSON":{"code":1702,"message":"plaid error","resolve":"An unexpected error has occurred on our systems; we've been notified and are looking into it!"},"status":500,"statusText":"Internal Server Error"}.

Our server is a .net server.  The post is as follows:
var httpWebRequest = (HttpWebRequest)WebRequest.Create("https://api.plaid.com/exchange_token");
            httpWebRequest.ContentType = "application/json";
            httpWebRequest.Method = "POST";

            using (var streamWriter = new StreamWriter(httpWebRequest.GetRequestStream()))
            {
                string json = new JavaScriptSerializer().Serialize(new
                {
                    client_id = [My client_id],
                    public_token = public_token,
                    secret = [My secret],
                    account_id = account_id
                });

                streamWriter.Write(json);
            }

            var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();
            using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))
            {
                try
                {
                    result = streamReader.ReadToEnd();
                }
                catch(Exception ex)
                {
                    return Ok(ex.Message);
                }
            }
             return Ok("{\"result\":\"" + result + "\"}");
        }
Also, we found in Nuget a package called Plaid - .net bindings for plaid API and Plaid - c# Driver for Plaid.  Is there any documentation for these tools? Just one example of a successful post to Plaid from .net c# would be wonderful.

Thanks!!!

**Comment by michaelckelly** [comment]
@hsmith825 - 

Are you still experiencing trouble? We have not suffered any system issues with the `/exchange_token` endpoint in recent weeks. If you are encountering issues, please get in touch with support@plaid.com.

**Comment by hsmith825** [comment]
Hi Michael,

 

Thanks for someone finally getting back.  Please do not close this issue.  I am having very significant problems.  Let me take you through the closest we have gotten to getting this to work.

 

Background:

My server is Microsoft .Net server.

Using the plaid-net

 

 

Code is as follows:

var client = new PlaidUserClient(“My client_id”, "secret”, PlaidClient.EnvironmentDevelopment);

            

            try

              {

                var response = await  client.ExchangeToken(Uri.UnescapeDataString(plaid_public_token), plaid_account_id);

                 var json_response = new JavaScriptSerializer().Serialize(response);

                return json_response;

              }

              catch (PlaidException e)

              

 

                  var json_error = new JavaScriptSerializer().Serialize(e.Error);

                return json_error;

              }

              catch (Exception e)

              {

                return e.Message;

             }

 

Result Error Object: 

*	{"Code":1702,"Message":"plaid error","Resolve":"An unexpected error has occurred on our systems; we\u0027ve been notified and are looking into it!","StatusCode":500}

Any help is desperately needed.

Thanks!

Howard

Ps:  Please leave this open until it is resolved.  I will close it.

 

 

 

Howard Smith

Flickitt

 <http://www.flickitt.com/> www.flickitt.com

“Failing to prepare is preparing to fail” –John Wooden

**Comment by michaelckelly** [comment]
@hsmith825 - Please send a note to support@plaid.com with the `public_token` that you're attempting to exchange!
