### ISSUE TITLE
bad public_token issue

### ISSUE THREAD

**Issue by johnwang21** [plaid/link#73]
Hello Support,

I'm following the stripe + ach guide at: https://stripe.com/docs/ach
Everything is working out so far until the step:

curl https://api.plaid.com/exchange_token \
   -d client_id="[Plaid client ID]" \
   -d secret="[Plaid secret]" \
   -d public_token="[Plaid Link public_token]" \
   -d account_id="[Plaid Link account_id]"
I am getting the response:
{"code"=>1106, "message"=>"bad public_token", "resolve"=>"This public_token is corrupt or does not exist in our database. See https://plaid.com/docs/link for docs."} 

Here is a bin paste to further details:
http://pastebin.com/a958Lwss

Is this happening because my account status is pending? 

Thanks,
John

Raw text in case you can't access bin paste:

I am using the below 3 values from https://dashboard.plaid.com/#/account
[client_id]
[secret]
[public_key]

--------------------------------------------------------------------------------
javascript for plaid link
--------------------------------------------------------------------------------

script type="text/javascript" src="https://cdn.plaid.com/link/stable/link-initialize.js"

javascript:
    jQuery(document).ready(function() {
        var linkHandler = Plaid.create({
            selectAccount: true,
            env: 'tartan',
            clientName: 'Stripe / Plaid Test',
            key: '[public_key]',
            product: 'auth',
            onLoad: function() {
              // The Link module finished loading.
            },
            onSuccess: function(public_token, metadata) {
              // The onSuccess function is called when the user has successfully
              // authenticated and selected an account to use.
              //
              // When called, you will send the public_token and the selected
              // account ID, metadata.account_id, to your backend app server.
              //
              // sendDataToBackendServer({
              //   public_token: public_token,
              //   account_id: metadata.account_id
              // });
              console.log('Public Token: ' + public_token);
              console.log('Customer-selected account ID: ' + metadata.account_id);
            },
            onExit: function() {
              // The user exited the Link flow.
            },
        });  

--------------------------------------------------------------------------------
plaid exchange call (backend)
--------------------------------------------------------------------------------
@response = HTTParty.post "https://api.plaid.com/exchange_token?client_id=[client_id]&secret=[secret]&public_token=[returned from plaid link]&account_id=[returned from plaid link]"

-------------------------------------------
response
-------------------------------------------

{"code"=>1106, "message"=>"bad public_token", "resolve"=>"This public_token is corrupt or does not exist in our database. See https://plaid.com/docs/link for docs."}

-------------------------------------------
Notes
-------------------------------------------
Plaid account status is pending? (not sure if this is causing the error)
using account
plaid_test//plaid_good
code: 1234

**Comment by michaelckelly** [comment]
@johnwang21  - if you are still having trouble, please [open a support case][1]!

**Comment by maksimsemenov** [comment]
Has the same issue.

Client code:
```
this.bankClickHandler = Plaid.create({
    env: plaidEnv,
    clientName: provider.name,
    key: plaidKey,
    product: 'auth',
    onSuccess: (public_token, metadata) => {
      // Send token to server
    },
    onExit: (err, metadata) => {
      if (err != null) {
        console.log(err, metadata)
      }
    }
  })
```

On server we use ruby-plaid gem.

Error:
```
Plaid::UnauthorizedError (Code 1106: bad public_token. This public_token is corrupt or does not exist in our database. See https://plaid.com/docs/link for docs.)
```
