### ISSUE TITLE
onExit event after password / before account selection

### ISSUE THREAD

**Issue by drs-nyc** [plaid/link#74]
I've noticed that exiting after the password is confirmed but before an account is selected will result in an "onSuccess" event with the account_id populated as well as public token.

The expected behavior might be an onExit event because this might mean that the user failed to select the proper account which might result in future charges being placed against an unintended account.

Anyone have some guidance on this?

**Comment by boxymoron** [comment]
I'm facing a similar issue. The user enters his/her crendentials, but exits before selecting an account. In this case my webhook is POSTed to by plaid with the newly created access_token, but the onSuccess() callback never get called, so we never get the public_token in our database.
