### ISSUE TITLE
what credentials do I use for testing in sandbox mode?

### ISSUE THREAD

**Issue by jakeonrails** [plaid/link#76]
For instance, on Stripe I can put in a credit card number of 4242424242424242 to simulate a visa card.

Do I really need to actually connect a real bank account to Plaid for testing development mode?

**Comment by c316** [comment]
plaid_test
plaid_good

Pin is 1234

https://plaid.com/docs

**Comment by jakeonrails** [comment]
Thanks - for anyone searching for more specifics: https://plaid.com/docs/#sandbox - accidentally found this linked to from the demo page on Plaid. Was searching all over for "testing plaid signup" and "plaid test accounts" or "plaid test credentials" and this section of the docs did not come up.

**Comment by elhanan-mishraky** [comment]
"When using our Sandbox environment, use user_good as the username and pass_good for the password." (from https://plaid.com/docs/quickstart/)
