### ISSUE TITLE
Connect Institution More Than Once (Duplicate Institutions But Different access_token)

### ISSUE THREAD

**Issue by thorsonmscott** [plaid/link#78]
Hey there, just started playing around with Plaid and Plaid Link, super slick, thanks!

Wondering how people are handling this scenario that I'm knocking my head against:

My setup: I'm building an ultra basic budgeting app to get familiar with Plaid.  My site has a user model, to which are associated a bank/institution/access_token after the user connects their bank via Plaid Link.  Now I can display their accounts, balance, transactions, etc, after persisting that data when Plaid hit's my webhook endpoint with an update.

The problem: Let's say I have added my Bank of America account via Plaid Link.  I want the user to be able to connect multiple banks if they have them, so they can launch Plaid Link again to do that.  But if they do so and enter the same Bank of America credentials again, I end up with duplicate banks and accounts and transactions and everything because I get a different access_token the second time, which is what I'm using as a unique key for the bank.

How would I prevent a user on my site from connecting the same bank account more than once?  Is there a different key I can use to see if they have already added it?  I have a few ideas around checking each account individually for _id keys, instead of the bank the accounts belong to.

I'm pretty sure I can figure something out from my end to prevent them from duplicating in my app, but is there any way to prevent this from the Plaid Link level?  Those banks would still get connected to my Plaid account, webhook setup, etc, I would just prevent the duplications from persisting and displaying on my site.  But my Plaid account would still be deducted 1 'item created' and I'd have more requests hitting my webhook endpoint than necessary.

Anybody else run into something similar and have any bright ideas?

Thanks for any help, and the work on Plaid, much appreciated!
- M

**Comment by ritec** [comment]
You could dynamically remove that bank from the list of banks provided if the user has already connected said bank. Plaid allows you to determine which banks you want to connect to in Link, just remove the one that has already been connected and you should have no problem with the user connecting it again, because it's no longer accessible.

So you could have a list of banks Link supports and remove the one that has already been connected and then pass that value to Link like so:

    // Trigger the BofA login view
    document.getElementById('bofaButton').onclick = function() {
      linkHandler.open('bofa');
    };

 There might be an easier way of doing this, but that is one possibility I can think of right now.

**Comment by rubendinho** [comment]
Another option could be to build a validation for a duplicate (say account number, name, institution and balance) and then if the new account is a duplicate, send a request to Plaid to delete that access token. That way it never gets added to your database and is immediately deleted from your Plaid account right after creation. 

You'd have to be a little careful if that access token has multiple accounts.

**Comment by GeorgeA93** [comment]
Hey @thorsonmscott it's a bit of a long shot seeing as you opened this a few years ago.... But what solution did you go with in the end?

**Comment by punitsoni** [comment]
I am interested in the solution as well. Which approach worked best for you guys?
