### ISSUE TITLE
Link bank selector window not drawing on Chrome

### ISSUE THREAD

**Issue by rubendinho** [plaid/link#81]
I recently started experiencing an issue rendering Link on Chrome.  It briefly shows the list/pictures of the banks but then seems to slide behind the main frame. You're still able to click on the banks though you obviously can't see them.  

I'm using Version 49.0.2623.110 (64-bit) of Chrome on OSX 10.11.3.  

Everything is working correctly on Safari.  I tinkered with the button and it looks like in some parts of my page (before some Materialize containers) it was working, but not on others. 

Has anyone experienced this?

<img width="384" alt="screen shot 2016-04-08 at 5 18 52 am" src="https://cloud.githubusercontent.com/assets/12505660/14365666/d441b812-fd49-11e5-92ac-be6612903801.png">

**Comment by pbernasconi** [comment]
Thanks for raising this issue @rubendinho!

I'm struggling to reproduce your error however, on the same Chrome stack that you're on – could you provide some more details as to the steps/process you took to create this error? 
- Are you getting any errors in your console? 
- Are you using any Chrome extensions that may possibly affect the Institution buttons/images? 
- What exactly is the `Materialize containers` that you mentioned?
- How are you initializing Link - via the simple or custom integration?

**Comment by rubendinho** [comment]
Hi Paolo - 

Sorry for the delay here. It seems that the problem has disappeared and I’m not experiencing it anymore. 

By Materialize containers I meant I’m using the http://materializecss.com framework and in particular had my plaid link button inside a http://materializecss.com/collapsible.html.    I am using the simple integration.  I’ll reopen this if it recurs. 

Ruben
