### ISSUE TITLE
Loading link-initialize.js with AMD like requireJS

### ISSUE THREAD

**Issue by sico** [plaid/link#83]
I've been trying to load the Link library with requireJS similarly to how Facebook recommends here: https://developers.facebook.com/docs/javascript/howto/requirejs, but on load the script throws an error because it can't find the `<script>` tag in the DOM source. (`'Failed to find script'`)

Is support for loading the JS via require something planned in the future, or something that's been handled before?

**Comment by pbernasconi** [comment]
@sico thanks for raising this issue. 

We've built [an example implementation of Plaid Link + RequireJS](https://github.com/plaid/link/tree/master/examples/requirejs) in our `/examples` folder, to get you started and for future reference.

Breifly this shim below allows you to `require` Plaid as if it were a local library (please look at the example for further details however).
```js
// configure RequireJS to load the link-initialize script
// *NOTE: the '*.js' extension is ommittedg
requirejs.config({
  paths: {
    'Plaid': 'https://cdn.plaid.com/link/stable/link-initialize'
  },
  // Plaid Link doesn't current support AMD
  // therefore we must create a shim to expose the global handler
  shim: {
    'Plaid': {
      exports: 'window.Plaid'
    }
  }
});
```

**Comment by sico** [comment]
Completely missed that example on first pass through. Thanks, this was enough to get me going!
