### ISSUE TITLE
Keyboard issues implementing with Ionic

### ISSUE THREAD

**Issue by tyvdh** [plaid/link#84]
I'm currently in the process of implementing this into an ionic iOS application but as it stands the iframe inputs are unusable. Key presses aren't submitting and you can't paste (helpful for long passwords).

Here's a handy demo app for testing: https://github.com/pbernasconi/plaid-link-ionic-example

Be sure to `npm install` and put this plugin folder at the root: http://tyler.link/g0t9

If you need any more help debugging I'm glad to provide all the info I can.

**Comment by tyvdh** [comment]
FYI your own webview app suffers from the issue.

**Comment by kainolophobia** [comment]
I'm running into the same issue. The input selection works if I do a "long click" as opposed to a tap on the input box. I don't remember running into this issue with a webapp, only when integrated with Cordova.
 
Looking for a fix!

**Comment by kainolophobia** [comment]
Update:
I've tried this with fastclick and without fastclick. 
I've tried iOS 8.3 and 9.3
I've tried modifing `-webkit-user-select` in the inspector to account for any weird differences
  
The issue does not occur in the Safari browser, only from within iFrame in the Cordova application.

**Comment by pbernasconi** [comment]
@tyvdh @kainolophobia  – We've been working to overhaul Plaid Link on mobile devices and would appreciate your feedback on the [Link mobile beta][1].

If you have any further questions - please feel to continue communication in this issue!

[1]: https://github.com/plaid/link/blob/master/mobile-beta/README.md

**Comment by pbernasconi** [comment]
@tyvdh @kainolophobia – Link mobile has now been released with a completely revamped mobile web experience. We're already starting to see high mobile conversion rates, and will no longer be officially support the older versions of Link. Please checkout our [blog post](https://blog.plaid.com/announcing-a-new-mobile-experience-for-link/) and the [Link docs](https://plaid.com/docs/quickstart/#getting-started) for more information and integrating!
