### ISSUE TITLE
Multiple product access when initializing Link with one product

### ISSUE THREAD

**Issue by iaghidro** [plaid/link#89]
For about 10 institutions which are listed for the auth product I can use both auth and connect server side routes if I initialize the Plaid Link with either auth or connect.
For certain institutions, Charles Schwab for example, Capital one 360, ect, if I initialize Plaid Link with auth, I can only use auth server side routes, and if I initialize with connect I can only use connect server side routes. 
I get an error saying product is not enabled or does not exist.

This is an issue, because we’d like to have the client use the Plaid Link widget and initialize either with auth or connect (both would be great but that’s not an option).
Then on the server side we’d like to make calls to both auth and connect at the same time because we need account/ routing numbers and bank transactions.

I noticed that the institution type/ institution id changes when I search for Charles Schwab between the auth and connect products.

Is there a way I could achieve this without forcing the client to re login twice into their account once with initializing plaid Link with auth and once with connect?
I saw there’s another option by not using Plaid Link and use the client’s credentials directly and add an Auth user and add a Connect user. I’d like to avoid this as well because we’d like to not store the client’s credentials, and not have to deal with the different verification methods that certain banks require.

I contacted support and was told to use the upgrade route, I have tried this and I receive the same error  "This product is not yet available for this institution”. But it is available if I initialize plaid link with the appropriate product.

-Thanks

**Comment by michaelckelly** [comment]
@iaghidro - You can now initialize Link with more than one product when using our [new API](https://blog.plaid.com/improving-our-api/), just initialize Link's `product` parameter as:

```
product: ['transactions', 'auth'],
```

**Comment by wfgilman** [comment]
@michaelckelly does this also work for WKWebView? I'm trying to initialize link with multiple products but the request won't load unless I specify a single product.

```
    func generateLinkInitializationURL() -> String {
        var plaidProducts = [String]()
        plaidProducts.append("transactions")
        plaidProducts.append("auth")
        
        let config = [
            "key": "[PLAID_PUBLIC_KEY]",
            "apiVersion": "v2",
            "env": "sandbox",
            "product": products,
            "selectAccount": "false",
            "clientName": "Example App",
            "isMobile": "true",
            "isWebview": "true",
            "webhook": "https://requestb.in",
            "institution": "ins_1"
            ] as [String : Any]

        var components = URLComponents()
        components.scheme = "https"
        components.host = "cdn.plaid.com"
        components.path = "/link/v2/stable/link.html"
        components.queryItems = config.map { URLQueryItem(name: "\($0)", value: "\($1)") }
        return components.string!
    }
```
