### ISSUE TITLE
close button (x) does not always work

### ISSUE THREAD

**Issue by benissimo** [plaid/link#91]
When I load the Plaid dialog, if I click the (x) in general it closes the dialog as I would expect.
If I'm in the process of logging in it asks me if I'm sure. So far so good.
But if I have logged in and the dialog now asks me about secondary authentication (for example if I login using the tartan version of Plaid and select Chase as the bank and enter username and password and am then prompted about sending a code to email or phone), clicking the (x) no longer works.

I'm using Chrome, JS console does not show any errors. Clicking the div with class "exit-button" does nothing; the dialog remains open.

**Comment by guimonz** [comment]
I'm having a similar issue. 
With long_tail: true, when I click "View more" and then I try to close the window, a JS error shows up in the console and the popup doesn't close.

![selection_026](https://cloud.githubusercontent.com/assets/599844/16199147/597ea3c6-36bd-11e6-8aa4-b43bc1729d77.png)

But then if I click on a bank (any bank) and try to close it after, it works.

**Comment by pbernasconi** [comment]
Thanks for raising this issue @benissimo @guimonz !
We just issued a fix for this bug, and it should be live as of now. Closing this issue for now, however please feel free to re-open if you continue to see this issue.
