### ISSUE TITLE
In test mode, Plaid link and Stripe use inconsistent account information

### ISSUE THREAD

**Issue by betesh** [plaid/link#92]
When testing Plaid Link, with both Plaid and Stripe in test mode, Stripe returns their usual test bank account, as described here: https://stripe.com/docs/testing#how-do-i-test-sending-transfers.  However, Plaid returns a different account number and routing number, creating quite a bit of confusion.  Presumably, in production, this is never an issue, as Stripe and Plaid are exchanging real data.  In test mode, there should also be consistency between the account information returned by Stripe and Plaid.
##### Step 1: Exchange Plaid token

```
uri: https://tartan.plaid.com/exchange_token
```

Response contains:

```
    {
      "account_id": "nban4wnPKE................D7pnCaeDBMy", # Redacted
      "stripe_bank_account_token": "btok_8gLJwc5pGSl3jw",
      "sandbox": true,
      "access_token": "test_wells"
    }
```
##### Step 2: Get Plaid Auth

```
uri: https://tartan.plaid.com/auth/get
```

Response contains:

```
{
  "_id":  "nban4wnPKE................D7pnCaeDBMy", # Account ID from part 1, redacted
  "numbers": {
    "routing": "021000021", # JP Morgan Chase's routing number.  Should be Stripe's test routing number.
    "account": "9900001702" # Some fictitious account number.  Should be Stripe's test account number.
  }
}
```
##### Step 3: Associate the account with my customer

```
uri: https://api.stripe.com/v1/customers/cus_xxxxxxxxxxxxxx/sources
body: "source=btok_8gLJwc5pGSl3jw" # stripe_bank_account_token from part 1
```

Response contains: 

```
{
  "bank_name": "STRIPE TEST BANK",
  "last4": "6789", # Stripe's official test account number
  "routing_number": "110000000" # Stripe's official test routing number
}
```

**Comment by betesh** [comment]
Why was this closed?  Was it fixed so that plaid and stripe provide consistent account information in test mode?

**Comment by benissimo** [comment]
So that sounds like the bug is still present? 

> In test mode, there should also be consistency between the account information returned by Stripe and Plaid.

This has not been addressed.
