### ISSUE TITLE
Invalid security certificate

### ISSUE THREAD

**Issue by thomasbottonari** [plaid/link#93]
I am getting the following error in Mac Firefox v42.0 when trying to fetch the link script (https://cdn.plaid.com/link/stable/link-initialize.js). I don't have any problems in Chrome, and even Firefox for Windows.

**An error occorred:**
cdn.plaid.com uses an invalid security certificate.

The certificate is not trusted because the issuer certificate is unknown.
The server might not be sending the appropriate intermediate certificates.
An additional root certificate may need to be imported.

(Error code: sec_error_unknown_issuer)

**Comment by amcbride** [comment]
cdn.plaid.com uses SNI (Subject Name Indication) where a webserver, or Cloudfront in this case, can serve lots of different https endpoints using different certificates without having a dedicated IP address for each unique certificate.

Old browsers don't support SNI

Firefox 47 on my mac works fine.

We have the option of having a dedicated IP in Cloudfront for $7200/yr, so if this becomes an issue we can check that $7200 box.

**Comment by michaelckelly** [comment]
@thomasbottonari  - I apologize for the delayed response. If you're still experiencing trouble, please [open a support ticket][1] so that we can help resolve this issue for you.

[1]: https://dashboard.plaid.com/support/new
