### ISSUE TITLE
Make `link-initialize` availabel through `npm` or a git endpoint

### ISSUE THREAD

**Issue by arjshiv** [plaid/link#94]
If you could make `link-initialize` available through `npm` or a git endpoint, this would be immensely helpful in organizing client-side code. 

I've already tried installing it from the CDN as follows:

``` json
"dependencies": {
    "plaid-link": "http://cdn.plaid.com/link/stable"
  },
```

But since it's just a script and not an `npm` package (specifically it doesn't include a `package.json`), that fails with the following error:

``` bash
npm ERR! path /var/folders/fz/0zf83nb52zqgzhnwdjdnkv1m0000gn/T/npm-57064-7daf1226/unpack-b3ad3d1b8e24/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/var/folders/fz/0zf83nb52zqgzhnwdjdnkv1m0000gn/T/npm-57064-7daf1226/unpack-b3ad3d1b8e24/package.json'
```

The fix for this is to add a `package.json` (as documented in [this StackOverflow answer and its comments](http://stackoverflow.com/a/17509764) ) , but at that point, it would be trivial to just add it to `npm` - let me know if this sounds right, I'm happy to help you take a crack at it too.

**Comment by michaelckelly** [comment]
Thanks for the feedback @arjshiv (and others) -- making Link available via NPM or other means is not on our current roadmap. If that changes, we'll be sure to update this issue.

**Comment by kienpham2000** [comment]
We are interested in this as well instead of always loading it from CDN which we can't control.

**Comment by iqnivek** [comment]
Just adding another +1 here - other improvements being more explicit versioning and not having to deal with an implicit global `Plaid` variable.
