### ISSUE TITLE
Make close button more accessible in mobile view

### ISSUE THREAD

**Issue by mpk2** [plaid/link#95]
In mobile versions of plaid link, the x button in the upper right corner can be very small and difficult to press. 

Oddly, it seems that at least on iOS, the actual press location of the button is displaced slightly below and to the left. While this admittedly seems to do a good job capturing carless presses, it is surprisingly frustrating to try to press the button only to find that it will not trigger.

I would suggest increasing the radius of the button to at least 40px to improve usability.

**Comment by pbernasconi** [comment]
Thanks for the feedback @mpk2 – We'll look into this this week and get back to you shortly!

**Comment by pbernasconi** [comment]
@mpk2 We've been working to overhaul Plaid Link on mobile devices and would appreciate your feedback on the [Link mobile beta][1].

The exit button is now more inline with common mobile styles on iOS and Android so I believe the new redesign will solve this issue!

[1]: https://github.com/plaid/link/blob/master/mobile-beta/README.md
