### ISSUE TITLE
Several styling + Usability Issues

### ISSUE THREAD

**Issue by obibring** [plaid/link#96]
Hey there,

I'm seeing several issues that are blocking us from using your product.

1) In Chrome on Mac, as the modal is animating into view, my page content becomes only partially rendered for about a second prior the modal and it's backdrop becoming visible. During this time that neither the modal nor its backdrop are visible, only a fraction of the content is rendered. In my case, just the page header is visible while the rest of the content vanishes. The header is a fixed position element, so this may have something to do with it. After about a second, the modal backdrop covers the viewport and the partially rendered version of my page is no longer visible.

2) In iOS Safari, once the modal appears and an institution is chosen, the username / password form is displayed. As soon as the username field is tapped, the modal "jumps" to the top of the page which is _not_ currently within the bounds of the viewport. Hence, the user is left seeing the backdrop, but no modal. From the user's perspective, it is not clear what just happened. The page appears to be broken. To find the modal, the user must scroll to the top of the page. As he does so, the new page content that enters the bounds of the viewport is not concealed by the backdrop for at least 200 ms, until the backdrop finally adjusts itself to cover the content.

3) In iOS Safari, the modal "fade in" animation is buggy. The backdrop first appears without animation, and then the modal appears, abruptly covering the backdrop without an animation.

**Comment by nickpad** [comment]
We're also seeing a usability issue where opening the modal alters the scroll position on the page, which means the user has moved out of the context they opened the dialog from when the exit.

**Comment by pbernasconi** [comment]
@obibring @nickpad – Sorry for the delayed response! We've been working to overhaul Plaid Link on mobile devices and would appreciate your feedback on the [Link mobile beta][1].

This should hopefully solve issues 2 and 3 for you. With regards, could you provide a screenshot to help us understand a bit better what's going on with your page content?

[1]: https://github.com/plaid/link/blob/master/mobile-beta/README.md

**Comment by pbernasconi** [comment]
@obibring @nickpad – Link mobile has now been released with a completely revamped mobile web experience. We're already starting to see high mobile conversion rates, and will no longer be officially support the older versions of Link. Please checkout our [blog post](https://blog.plaid.com/announcing-a-new-mobile-experience-for-link/) and the [Link docs](https://plaid.com/docs/quickstart/#getting-started) for more information and integrating!

**Comment by nickpad** [comment]
Thanks @pbernasconi, we've implemented the v2 widget and it's a big improvement!
