### ISSUE TITLE
institution search API only returns 10 results

### ISSUE THREAD

**Issue by sumade** [plaid/link#97]
Is there documentation that describes how many results can be returned by the [institution search API](https://plaid.com/docs/api/#institution-search)? For example, [this query for the "1st"](https://tartan.plaid.com/institutions/search?q=1st) only returns 10 results.

However, if I retrieve the first 500 results from `/institutions/longtail`, I see there are 100+ institutions whose name starts with "1st": [longtail.txt](https://github.com/plaid/link/files/379449/longtail.txt)

Is there a way to control the number of institutions returned by the search API? Or a mechanism to page through results if they can't be returned from a single call?

Or is there a reason why the search query "1st" doesn't match any of the institutions returned by the `/institutions/longtail` API?

Thanks.

**Comment by sumade** [comment]
oops. wrong repo.

**Comment by pbernasconi** [comment]
@sumade Thanks for raising this issue! I recommend you contact our support team at support@plaid.com if you have any other questions relating to integrating with Link!
