### ISSUE TITLE
examples in other languages

### ISSUE THREAD

**Issue by jon-choi** [plaid/link#98]
friendly request for an example in python please! maybe rust as well? 😁

**Comment by pbernasconi** [comment]
Thanks for your interest in other languages @jon-choi – we realise the importance of showing multiple example and will look into creating some example code in the near future.

If you have any examples that you'd like to share, please feel free to submit a Pull Request to this project!

**Comment by jon-choi** [comment]
thanks, will do.

**Comment by michaelckelly** [comment]
https://plaid.com/docs/quickstart should help here - you'll find end-to-end example apps in Python, Node, and Ruby.
